### ISSUE TITLE
Orphaned contact info is left in active/recent contact list after deleting it

### ISSUE THREAD

**Issue by vogel76** [InvictusInnovations/keyhotee#10]
Select some contact, show the contact info. Next delete the contact - it disappears from contact list but still stays on active/recent list in navigation window.

**Comment by grzegorzs** [comment]
Deleting Contact, removes the contact from the left side bar.
https://github.com/InvictusInnovations/keyhotee/commit/7dc44d3ee8069437492dd256878349746872701a
