### ISSUE TITLE
compile error:ui_ContactView.h:30:32: fatal error: LineEditReadOnly.hpp: No such file or directory

### ISSUE THREAD

**Issue by vipjeffreylee** [InvictusInnovations/keyhotee#103]
keyhotee: 2e57b0657db95852f185be64c81dd612828817a0 

/keyhotee/AddressBook/ContactView.cpp:2:0:
/home/jeffrey/Git/keyhotee/build/ui_ContactView.h:30:32: fatal error: LineEditReadOnly.hpp: No such file or directory
compilation terminated.
make[2]: **\* [CMakeFiles/Keyhotee.dir/AddressBook/ContactView.cpp.o] Error 1
make[1]: **\* [CMakeFiles/Keyhotee.dir/all] Error 2
make: **\* [all] Error 2

**Comment by bytemaster** [comment]
I fixed this temporarily by converting it back to a regular line edit.

**Comment by vipjeffreylee** [comment]
thank u

**Comment by vogel76** [comment]
Paul please revert it back to your custom class to get support for public key copying. Also check include paths (probably proper configuration in .ui file is missing).

**Comment by PaulEU** [comment]
Fixed at rev: https://github.com/InvictusInnovations/keyhotee/commit/2867852f02ecf88144e880b21a3ebdb99db602e4

**Comment by vipjeffreylee** [comment]
Hey Daniel,
I know you are very busy now.When you have time, tell me how to get the
AngelShares,please.
Because,my many friends ask me ,but I can't answer them.

2013/12/21 PaulEU notifications@github.com

**Comment by bytemaster** [comment]
https://bitsharestalk.org/index.php?topic=1631.0

**Comment by vipjeffreylee** [comment]
Thank you

2013/12/26 Daniel Larimer notifications@github.com
