### ISSUE TITLE
Application receives fc::canceled_exception at startup and is closing.

### ISSUE THREAD

**Issue by vogel76** [InvictusInnovations/keyhotee#105]
Few minutes ago it worked fine, right now I'm unable to start the application.

```
KeyhoteeD.exe!fc::exception::dynamic_rethrow_exception() Line 280   C++
KeyhoteeD.exe!fc::promise_base::_wait_until(const fc::time_point & timeout_us={...}) Line 60    C++
KeyhoteeD.exe!fc::promise_base::_wait(const fc::microseconds & timeout_us={...}) Line 46    C++
KeyhoteeD.exe!fc::promise<void>::wait(const fc::microseconds & timeout={...}) Line 136  C++
KeyhoteeD.exe!fc::asio::tcp::accept<boost::asio::basic_stream_socket<boost::asio::ip::tcp,boost::asio::stream_socket_service<boost::asio::ip::tcp> >,boost::asio::basic_socket_acceptor<boost::asio::ip::tcp,boost::asio::socket_acceptor_service<boost::asio::ip::tcp> > >(boost::asio::basic_socket_acceptor<boost::asio::ip::tcp,boost::asio::socket_acceptor_service<boost::asio::ip::tcp> > & acc={...}, boost::asio::basic_stream_socket<boost::asio::ip::tcp,boost::asio::stream_socket_service<boost::asio::ip::tcp> > & sock={...}) Line 138   C++
KeyhoteeD.exe!fc::tcp_server::accept(fc::tcp_socket & s={...}) Line 94  C++
KeyhoteeD.exe!bts::rpc::detail::server_impl::accept_loop() Line 33  C++
```

**Comment by vogel76** [comment]
Looks like profile database got corrupted somehow what causes this problem. Recreating profile allows application to start again.
Packed profile db in attachment (renamed to ,jpg because of github limitations).
![invictus innovations inc zip](https://f.cloud.github.com/assets/6086581/1788095/aa39469e-691b-11e3-828c-a9ad3d5bc96b.jpg)

**Comment by dnotestein** [comment]
I looked into this issue some, and I suspect it was database corruption from database structure changes. Anyways, let's close it out for now, since database structures have further changed since then and this profile is no longer interesting, unless someone wants to revert back to earlier code and analyze it.
