### ISSUE TITLE
Backend storage for mail message doesn't include bcc list

### ISSUE THREAD

**Issue by vogel76** [InvictusInnovations/keyhotee#109]
Even this list should not be filled when mail message is sent, it should be stored until message is stored as draft.
Please add storage for it and decide which part should be responsible for clearing bcc list: gui while operating on mail messages or backend when send_email method is called. I'd rather opt to backend solution since this is guarantee same behaviour independently to potential another (GUI/cmdline) client implementation.
When done please assign it back to me since few parts in GUI will need to be changed in relation to it.

**Comment by dnotestein** [comment]
Implemented in https://github.com/InvictusInnovations/keyhotee/commit/578f98193532e782d2a4e39b8c98cd871a6d88cc
