### ISSUE TITLE
Create diagnostic dialog to be showed from Help menu

### ISSUE THREAD

**Issue by vogel76** [InvictusInnovations/keyhotee#11]
Create diagnostic dialog conataining an multiline edit control, allowing to copy its contents.
This diagnostic textual dump should contain some internal state infos dumped by backend engine like block chain etc.
<b> Specify what should be dumped into such diagnostic dump</b>

**Comment by dnotestein** [comment]
This is some information that user can send to us to help us debug if they're not syncing/connecting to blockchain properly.
Current block number and it's hash number of blockchain. # of connections. Last time we received a block. Client name and version number. Timestamp.

**Comment by vogel76** [comment]
Please specify API to access these data.

**Comment by dnotestein** [comment]
I think in first draft of this, we can just have it display the log file. In fact, I think we can use the same dialog we will use for catching fatal exceptions/errors. Later we can add some routine that adds some of the above info at the end of the log.

**Comment by vogel76** [comment]
Please also show this dialog from this method: TKeyhoteeApplication::DisplayFailureInfo (Edit: Done)

**Comment by dnotestein** [comment]
Text editor control in this dialog should expand when dialog is expanded. Also this dialog should be slightly bigger by default I think.

**Comment by yuvarajgogoi** [comment]
Fixed and please let me know your feedback.
