### ISSUE TITLE
bts::network::get_external_ip() failed and hang up on windows

### ISSUE THREAD

**Issue by hackfisher** [InvictusInnovations/keyhotee#110]
It may due to a bug of function in ipecho.cpp, bts::network::get_external_ip(); , on windows platform.

I changed 

request << "Host: ipecho.net\r\n\r\n";

to 

request << "Host: ipecho.net\r\n\r\nConnection:Close\r\n";

and now its working now.

Refer: https://bitsharestalk.org/index.php?topic=1499.msg16378#msg16378

**Comment by dnotestein** [comment]
Implemented above fix in https://github.com/InvictusInnovations/BitShares/commit/6f966d91f6933562827e6f7abb92216de9a3d71d.
