### ISSUE TITLE
Add fatal error dialog to display log when we get a fatal exception or other fatal error.

### ISSUE THREAD

**Issue by dnotestein** [InvictusInnovations/keyhotee#112]
For fatal errors (e.g. fatal exceptions), especially at startup, we need some way to keep the console messages on the screen for Windows platform. On Unix, the console window stays around, so it's not such an issue, but for Windows it's a problem.  First, we should probably change logging to always log to file, even when logging to console also. fc logging has features for this already.

Also, let's add a "Fatal Error" dialog that displays the the log in a text editor window with an ok button to close it. This dialog would be opened in QApplication::notify whenever we detect any so-far unhandled exception there (first we should log the info in the exception before displaying the dialog, of course) . Once OK is pressed, we would exit the application with return code of 1 to indicate an error.

**Comment by dnotestein** [comment]
I can get eric to enable the logging part of this issue, he's already messed with fc logging code in past, and it's a bit complicated if I remember correctly.

**Comment by dnotestein** [comment]
Let's get this done ASAP as it will be very helpful for diagnosing connection errors and database corruption issues due to changes in database structure sizes.

**Comment by vogel76** [comment]
Implemented dedicated QApplication subclass catching exceptions. Still dedicated diagnostic dialog must be added and displayed inside TKeyhoteeApplication::DisplayFailureInfo method.

**Comment by vogel76** [comment]
Added a comment to https://github.com/InvictusInnovations/keyhotee/issues/11 issue to supplement function mentioned above by new dialog.
