### ISSUE TITLE
Delete option should be disabled when 'New contact' view is active.

### ISSUE THREAD

**Issue by vogel76** [InvictusInnovations/keyhotee#113]
Right now, when user opens 'new contact' view all other content is hidden (as agreed). But in some previous view (ie Contact list) could be left some selected items. When user use 'Delete' option these selected (but invisible) items will be deleted.

**Comment by PaulEU** [comment]
Fixed at rev: https://github.com/InvictusInnovations/keyhotee/commit/d74aa7eed621d95be876ef2b7ba022814c857105
