### ISSUE TITLE
Copy/paste from ContactListEdit control works improperly

### ISSUE THREAD

**Issue by vogel76** [InvictusInnovations/keyhotee#116]
Since internally ContactListEdit stores added contact info as image (what is generally wrong) copying it puts into clipboard image data instead of required text. Trying to paste it to some another edit box (ie public key in Contact Edit view) causes an assertion failure and probably crash in release build.
The control behaviour must be changed to put displayed text (displayed name or public key) into the clipboard.

**Comment by PaulEU** [comment]
Fixed in: https://github.com/InvictusInnovations/keyhotee/commit/ece5a98e567557f75672a7507d28898ac89be7c7
