### ISSUE TITLE
LINUX: Mail popup windows doesn't have 'close' button on the frame.

### ISSUE THREAD

**Issue by vogel76** [InvictusInnovations/keyhotee#117]

**Comment by yuvarajgogoi** [comment]
I have some query regarding this. Please provide me your skype id. mine is yuvaraj.gogoi

**Comment by vogel76** [comment]
As far as I analyzed it, flags passed to QMainWindow constructor (in class MailEditorMainWindow) are wrong. There is passed Qt::WindowType::Dialog. Please try to pass default value - it should help.

**Comment by yuvarajgogoi** [comment]
In my Ubuntu machine, With Qt::WindowType::Dialog, only the minimize button is disabled. The close button is enabled and working fine. 

With Qt::WindowType::window flag, close, minimize and maximize buttons, all are enabled. And with default flag also close, minimize and maximize are enabled. So setting it to default to enable the minimize button.
