### ISSUE TITLE
Profile name in the title bar

### ISSUE THREAD

**Issue by PaulEU** [InvictusInnovations/keyhotee#118]
Few revisions ago there was displayed profile name (e.g. second) in the title bar. It was helpful for testing communication.

**Comment by dnotestein** [comment]
I think it got lost in vogel's last commit, I'll check into it, I'm missing it too.

**Comment by dnotestein** [comment]
Fixed in https://github.com/InvictusInnovations/keyhotee/commit/9c6ced58661d08625cd72c1583b4d803a2716afa
