### ISSUE TITLE
toStdString() should be converted to ...toUtf8().constData()

### ISSUE THREAD

**Issue by bytemaster** [InvictusInnovations/keyhotee#122]
toStdString() will cause problems because it converts to ascii and chinese characters would be lost.   

Please verify all instances of toStdString() are properly handled.

**Comment by dnotestein** [comment]
some questions have come up about this issue, so unassigning for now

**Comment by dnotestein** [comment]
implementation of toStdString seems to do correct thing:
inline std::string QString::toStdString() const
{ const QByteArray asc = toUtf8(); return std::string(asc.constData(), asc.length()); 
So this issue is being closed.
