### ISSUE TITLE
Composing new mail message is crashing now

### ISSUE THREAD

**Issue by dnotestein** [InvictusInnovations/keyhotee#125]
This only happens when connected via server. I'm able to send email when connected between two clients locally (although some assertions are thrown, which I ignored). Maybe this bug is because we have old server code running, hopefully it will go away soon with replacement with new server version.

**Comment by vogel76** [comment]
The GUI code is crashing since bts::profile::identities() returns empty list. So it is backend related then.

**Comment by dnotestein** [comment]
New profile functionality means we have no initial identity created. If we want to keep with this, we'll need to disable a lot of GUI elements until user creates an identity (e.g. Composing new mail message, Sending chat messages to contacts). Probably this needs to be done in any case, if we allow user to delete all his identities in a profile.

**Comment by vogel76** [comment]
I think it should be impossible to start KH without any identity created, or delete all of them while using it. This will solve all of problems which could be hard to locate.

**Comment by vogel76** [comment]
I have patched it in crashing part but as described above this scenario generally should be impossible since started application is anyway unusable.
