### ISSUE TITLE
Strange bug with login password

### ISSUE THREAD

**Issue by dnotestein** [InvictusInnovations/keyhotee#128]
Twice I've had a problems logging into a profile (maybe it was newly created one). Restarting program, I've been able to login with same password.

**Comment by PaulEU** [comment]
related with Issue #184
If firstly you set wrong password, you can not login into a profile even if you set right password.

**Comment by vogel76** [comment]
Maybe this bug is also related to: https://github.com/InvictusInnovations/keyhotee/issues/210

**Comment by vogel76** [comment]
Fixed at rev: https://github.com/InvictusInnovations/BitShares/commit/c8f64faca9a8e2e2d4efc321974f365413cfdfd8
