### ISSUE TITLE
Crash while exiting the app

### ISSUE THREAD

**Issue by vogel76** [InvictusInnovations/keyhotee#129]
bts::detail::application_impl::_quit_promise member looks like already deleted.
Crash callstack below.

>   KeyhoteeD.exe!bts::detail::application_impl::connect_loop() Line 54 C++
>     KeyhoteeD.exe!<lambda_f304f7e4c942895f8799c7521062ca78>::operator()() Line 174  C++
>     KeyhoteeD.exe!fc::detail::void_functor_run<<lambda_f304f7e4c942895f8799c7521062ca78> >::run(void \* functor=0x043ef960, void \* prom=0x043ef9e8) Line 53  C++
>     KeyhoteeD.exe!fc::task_base::run() Line 17  C++
>     KeyhoteeD.exe!fc::thread_d::run_next_task() Line 348    C++
>     KeyhoteeD.exe!fc::thread_d::process_tasks() Line 370    C++
>     KeyhoteeD.exe!fc::thread_d::start_process_tasks(int my=11712848) Line 328   C++
>     boost_context-vc110-mt-gyd-1_53.dll!make_fcontext() Line 107    Unknown
>     KeyhoteeD.exe!fc::thread_d::start_next_fiber(bool reschedule=false) Line 283    C++

**Comment by dnotestein** [comment]
I think this error could possibly have been fixed by https://github.com/InvictusInnovations/keyhotee/commit/175b954cb433d899816d0f94e2577110f6ea05d5. I'm closing for now, and someone can reopen if it occurs any more.
