### ISSUE TITLE
Can you help me resolve,upnp.cpp:78: undefined reference to `upnpDiscover'

### ISSUE THREAD

**Issue by vipjeffreylee** [InvictusInnovations/keyhotee#13]
OS:Ubuntu 12.04
How to resolve this compile error?
BitShares/libbshare.a(upnp.cpp.o): In function `operator()':
/home/jeffrey/Git/keyhotee/BitShares/src/network/upnp.cpp:78: undefined reference to`upnpDiscover'
/home/jeffrey/Git/keyhotee/BitShares/src/network/upnp.cpp:86: undefined reference to `UPNP_GetValidIGD'
/home/jeffrey/Git/keyhotee/BitShares/src/network/upnp.cpp:145: undefined reference to`freeUPNPDevlist'
/home/jeffrey/Git/keyhotee/BitShares/src/network/upnp.cpp:148: undefined reference to `FreeUPNPUrls'
/home/jeffrey/Git/keyhotee/BitShares/src/network/upnp.cpp:96: undefined reference to`UPNP_GetExternalIPAddress'
/home/jeffrey/Git/keyhotee/BitShares/src/network/upnp.cpp:125: undefined reference to `strupnperror'
/home/jeffrey/Git/keyhotee/BitShares/src/network/upnp.cpp:120: undefined reference to`UPNP_AddPortMapping'
/home/jeffrey/Git/keyhotee/BitShares/src/network/upnp.cpp:136: undefined reference to `UPNP_DeletePortMapping'
/home/jeffrey/Git/keyhotee/BitShares/src/network/upnp.cpp:138: undefined reference to`freeUPNPDevlist'
/home/jeffrey/Git/keyhotee/BitShares/src/network/upnp.cpp:139: undefined reference to `FreeUPNPUrls'
collect2: error: ld returned 1 exit status
make[2]: **\* [Keyhotee] Error 1

**Comment by vogel76** [comment]
Could you provide full build log in the attachement ?

**Comment by vipjeffreylee** [comment]
I fix this bug
https://github.com/InvictusInnovations/keyhotee/pull/29

but this pull is closed by Daniel Larimer.
Does anyone encountered this bug?

**Comment by bytemaster** [comment]
I clicked the wrong item, I meant to merge it.
