### ISSUE TITLE
Save main window size/position

### ISSUE THREAD

**Issue by PaulEU** [InvictusInnovations/keyhotee#134]
Application should save main window size/position before closing. And restore it while starting.

**Comment by vogel76** [comment]
As I see application contains code to do it (inside SelfSizingWindow class), so this is a bug, not new feature.

**Comment by vogel76** [comment]
Paul please check why it doesn't work.

**Comment by vipjeffreylee** [comment]
bug reason:
KeyhoteeMainWindow virtual closeEvent overide SelfSizingMainWindow  virtual closeEvent.
I have pull fixed code 
https://github.com/InvictusInnovations/keyhotee/pulls

**Comment by PaulEU** [comment]
Fixed by vipjeffreylee
