### ISSUE TITLE
Identify contact ownership in the Contact list 

### ISSUE THREAD

**Issue by vogel76** [InvictusInnovations/keyhotee#14]
Application should identify contacts with own identities by user logged into current profile. Such identification should be implemented basing on private key availibity in the kID object.
The presentation layer should display such information in additional column with title 'Own' and some boolean value (yes/no) or some read-only check-box form. This column should allows to sort records using it.

**Comment by grzegorzs** [comment]
Added identify ownership in the Contact list
4c77f979a814d357f6fd028f5ef341e7c451deba
