### ISSUE TITLE
Implement Mail/Forward, Mail/reply, Mail/Reply all main menu options

### ISSUE THREAD

**Issue by vogel76** [InvictusInnovations/keyhotee#140]
Please connect actions to these main menu options to behave the same as these available on mail viewer toolbar.
These main menu options should be grayed out when given operation is impossible:
- no mailbox page is active
- there is no row selected
- multiple rows have been selected

**Comment by grzegorzs** [comment]
Implemented Forward, Reply, Reply All in main menu
8fd894a4885ca49ffb2cc02a6e400352f6c9bc98
