### ISSUE TITLE
Application crashes when mail is opened in standalone window

### ISSUE THREAD

**Issue by vogel76** [InvictusInnovations/keyhotee#144]
Go to any mailbox folder (ie inbox). Double click on any mail message stored there. Crash occurs.
The cause of a crash is wrong parrent passed to MailEditorMainWindow (after latest changes it should be KeyhoteeMainWindow instance).

**Comment by dnotestein** [comment]
I tried a quick workaround of passing the KeyhoteeMainWindow parent pointer, but it didn't work for me (I didn't analyze, I just made quick attempt). I needed to get around issue 145, so I temporarily #if 0 the code that was crashing, so it needs to be restored as part of proper fix. I left //DLNFIX in ATopLevelWindow.cpp to make the #if 0 easy to spot.

**Comment by grzegorzs** [comment]
Fixed
0ea5118d185cc8dc6d7f257e71950983d48b8435
