### ISSUE TITLE
To field is not working properly in draft messages

### ISSUE THREAD

**Issue by dnotestein** [InvictusInnovations/keyhotee#152]
"To" field's values shown don't reflect my expectations after I save a draft email, especially on the drafts mailbox table, but also to some extent seems wrong in draft mail editor as well if I double click to reopen the draft email.

**Comment by dnotestein** [comment]
Create a profile with at least two contacts (one being self plus some other guy). Save a draft message to the other guy. Double click and open draft, add your self to the To field and save draft again. Double click again and delete one of the contacts and save draft again. Within a few repetitions of the these steps, I get wrong results shown in drafts email table (i.e. not the correct results in "to" field, based on what I saved). I created a new profile just now to confirm that this bug still happens.

**Comment by vogel76** [comment]
Fixed at rev. https://github.com/InvictusInnovations/keyhotee/commit/a2141af9a41875e47881556e215170cac3855116
