### ISSUE TITLE
inserting a long string to public key on add new contact leads to crash

### ISSUE THREAD

**Issue by yuvarajgogoi** [InvictusInnovations/keyhotee#155]
Steps to reproduce the issue:
1) start a client.
2) start another client.
3) Do add new contact on either client:
add a long string to public key. e.g. akuwyrfewaefykawgfeawkfygef4akwfyekykfawywefykff

crash is seen

Tested on Ubuntu

**Comment by vogel76** [comment]
I've just built application on linux (Debian) and checked this issue - application works fine. Please check if you have correctly built application (clean everything and rebuild).

**Comment by yuvarajgogoi** [comment]
I made a new repository now and pasted this string on the public key field of new contact

akuwyrfewaefykawgfeawkfygef4akwfyekykfawywefykffff

It crashed. Tested again on Ubuntu. Will send the callstack in a while.

log:426270ms       th_a              startup ] .            KeyhoteeApplication.cpp:263
426271ms       th_a         get_profiles ] profiles []          application.cpp:217
426271ms       th_a displayProfileWizard ] .            KeyhoteeApplication.cpp:186
459253ms       th_a       create_profile ] config_file: /home/yuvi/.local/share/Keyhotee/profiles/Y G/config.json           application.cpp:258
473733ms       th_a            configure ] external IP 106.51.180.42            application.cpp:139
473733ms       th_a            configure ] listening for stcp connections on port 0         server.cpp:206
475130ms       th_a         load_indexes ] load indexes         bitname_db.cpp:92
475131ms       th_a         load_indexes ] load indexes         bitname_db.cpp:107
475148ms       th_a      init_timekeeper ] ...init stats...         bitname_db.cpp:162
475148ms       th_a      init_timekeeper ] ...done init timekeeper...           bitname_db.cpp:164
475148ms       th_a                 open ] open name db         bitname_db.cpp:214
479051ms       th_a            configure ] listening for rpc connections on port 0          rpc_server.cpp:245
479052ms       th_a            configure ] listening for rpc connections on port 48728          rpc_server.cpp:247
479385ms       th_a   KeyhoteeMainWindow ] idents: []           KeyhoteeMainWindow.cpp:252
479465ms       th_a         connect_loop ] 162.243.67.4:9876            application.cpp:59
479465ms       th_a           connect_to ] connect to 162.243.67.4:9876         server.cpp:243
480135ms       th_a         connect_loop ] unspecified
Broken pipe 
    {"message":"Broken pipe"}
    asio  asio.cpp:28 read_write_handler
error connecting to 162.243.67.4:9876
    {"ep":"162.243.67.4:9876"}
    th_a  connection.cpp:194 connect
unable to connect to 162.243.67.4:9876
    {"ep":"162.243.67.4:9876"}
    th_a  server.cpp:256 connect_to         application.cpp:64
483135ms       th_a         connect_loop ] 162.243.67.4:9876            application.cpp:59
483136ms       th_a           connect_to ] connect to 162.243.67.4:9876         server.cpp:243
483383ms       th_a         connect_loop ] unspecified
Broken pipe 
    {"message":"Broken pipe"}
    asio  asio.cpp:28 read_write_handler
error connecting to 162.243.67.4:9876
    {"ep":"162.243.67.4:9876"}
    th_a  connection.cpp:194 connect
unable to connect to 162.243.67.4:9876
    {"ep":"162.243.67.4:9876"}
    th_a  server.cpp:256 connect_to         application.cpp:64
486384ms       th_a         connect_loop ] 162.243.67.4:9876            application.cpp:59
486384ms       th_a           connect_to ] connect to 162.243.67.4:9876         server.cpp:243
486710ms       th_a         connect_loop ] unspecified
Broken pipe 
    {"message":"Broken pipe"}
    asio  asio.cpp:28 read_write_handler
error connecting to 162.243.67.4:9876
    {"ep":"162.243.67.4:9876"}
    th_a  connection.cpp:194 connect
unable to connect to 162.243.67.4:9876
    {"ep":"162.243.67.4:9876"}
    th_a  server.cpp:256 connect_to         application.cpp:64
489711ms       th_a         connect_loop ] 162.243.67.4:9876            application.cpp:59
489711ms       th_a           connect_to ] connect to 162.243.67.4:9876         server.cpp:243
489943ms       th_a         connect_loop ] unspecified
Broken pipe 
    {"message":"Broken pipe"}
    asio  asio.cpp:28 read_write_handler
error connecting to 162.243.67.4:9876
    {"ep":"162.243.67.4:9876"}
    th_a  connection.cpp:194 connect
unable to connect to 162.243.67.4:9876
    {"ep":"162.243.67.4:9876"}
    th_a  server.cpp:256 connect_to         application.cpp:64
492943ms       th_a         connect_loop ] 162.243.67.4:9876            application.cpp:59
492943ms       th_a           connect_to ] connect to 162.243.67.4:9876         server.cpp:243
493189ms       th_a         connect_loop ] unspecified
Broken pipe 
    {"message":"Broken pipe"}
    asio  asio.cpp:28 read_write_handler
error connecting to 162.243.67.4:9876
    {"ep":"162.243.67.4:9876"}
    th_a  connection.cpp:194 connect
unable to connect to 162.243.67.4:9876
    {"ep":"162.243.67.4:9876"}
    th_a  server.cpp:256 connect_to         application.cpp:64
496190ms       th_a         connect_loop ] 162.243.67.4:9876            application.cpp:59
496190ms       th_a           connect_to ] connect to 162.243.67.4:9876         server.cpp:243
496433ms       th_a         connect_loop ] unspecified
Broken pipe 
    {"message":"Broken pipe"}
    asio  asio.cpp:28 read_write_handler
error connecting to 162.243.67.4:9876
    {"ep":"162.243.67.4:9876"}
    th_a  connection.cpp:194 connect
unable to connect to 162.243.67.4:9876
    {"ep":"162.243.67.4:9876"}
    th_a  server.cpp:256 connect_to         application.cpp:64
499434ms       th_a         connect_loop ] 162.243.67.4:9876            application.cpp:59
499434ms       th_a           connect_to ] connect to 162.243.67.4:9876         server.cpp:243
499676ms       th_a         connect_loop ] unspecified
Broken pipe 
    {"message":"Broken pipe"}
    asio  asio.cpp:28 read_write_handler
error connecting to 162.243.67.4:9876
    {"ep":"162.243.67.4:9876"}
    th_a  connection.cpp:194 connect
unable to connect to 162.243.67.4:9876
    {"ep":"162.243.67.4:9876"}
    th_a  server.cpp:256 connect_to         application.cpp:64
502677ms       th_a         connect_loop ] 162.243.67.4:9876            application.cpp:59
502677ms       th_a           connect_to ] connect to 162.243.67.4:9876         server.cpp:243
502928ms       th_a         connect_loop ] unspecified
Broken pipe 
    {"message":"Broken pipe"}
    asio  asio.cpp:28 read_write_handler
error connecting to 162.243.67.4:9876
    {"ep":"162.243.67.4:9876"}
    th_a  connection.cpp:194 connect
unable to connect to 162.243.67.4:9876
    {"ep":"162.243.67.4:9876"}
    th_a  server.cpp:256 connect_to         application.cpp:64
504195ms       th_a   displayFailureInfo ] unspecified
error decoding public key
    {"s":"error:100B2043:elliptic curve routines:EC_KEY_copy:passed a null parameter"}
    th_a  elliptic.cpp:416 public_key           KeyhoteeApplication.cpp:205
504195ms       th_a   displayFailureInfo ] fatal error unspecified
error decoding public key
    {"s":"error:100B2043:elliptic curve routines:EC_KEY_copy:passed a null parameter"}
    th_a  elliptic.cpp:416 public_key           KeyhoteeApplication.cpp:207

**Comment by dnotestein** [comment]
I can dup this error, seems like problem in public key handling functions, looking at the log.

**Comment by yuvarajgogoi** [comment]
callstack:

0   fc::promise_base::ready future.cpp  32  0x6838c0  
1   bts::detail::application_impl::connect_loop application.cpp 54  0x5a7fab  
2   operator()  application.cpp 174 0x5a22df  
3   fc::detail::void_functor_runbts::application::connect_to_network()::<lambda() >::run(void *, void *)  task.hpp    52  0x5a22df  
4   fc::task_base::run  task.cpp    17  0x6843f2  
5   run_next_task   thread_d.hpp    347 0x682b99  
6   fc::thread_d::process_tasks thread_d.hpp    370 0x682b99  
7   fc::thread_d::start_process_tasks   thread_d.hpp    328 0x683159  
8   make_fcontext           0x710ade  
9   ??          0xdb5210  
10  ??

**Comment by vogel76** [comment]
https://github.com/InvictusInnovations/keyhotee/commit/75df75ddb3687558c7565bb1400401eee65518f4
