### ISSUE TITLE
crash seen on creating new identity with similar names

### ISSUE THREAD

**Issue by yuvarajgogoi** [InvictusInnovations/keyhotee#156]
steps to reproduce:
1) start two clients.
2) enable mining
3) create similar identity in one client one after another:
jjjjj , j ,  jjjjjjj, jjjj 

crash is seen

Tested on Ubuntu

log:

1764708ms       th_a              startup ] .           KeyhoteeApplication.cpp:265
1764708ms       th_a         get_profiles ] /home/yuvi/.local/share/Keyhotee/profiles/Y G           application.cpp:212
1764708ms       th_a         get_profiles ] /home/yuvi/.local/share/Keyhotee/profiles/J G           application.cpp:212
1764708ms       th_a         get_profiles ] profiles ["Y G","J G"]          application.cpp:217
1764708ms       th_a         displayLogin ] .           KeyhoteeApplication.cpp:173
1764738ms       th_a         get_profiles ] /home/yuvi/.local/share/Keyhotee/profiles/Y G           application.cpp:212
1764738ms       th_a         get_profiles ] /home/yuvi/.local/share/Keyhotee/profiles/J G           application.cpp:212
1764738ms       th_a         get_profiles ] profiles ["Y G","J G"]          application.cpp:217
1764738ms       th_a          LoginDialog ] profiles Y G            LoginDialog.cpp:23
1764738ms       th_a          LoginDialog ] profiles J G            LoginDialog.cpp:23
1774138ms       th_a            configure ] external IP 106.51.180.42           application.cpp:139
1774138ms       th_a            configure ] listening for stcp connections on port 9876         server.cpp:206
1775467ms       th_a         load_indexes ] load indexes            bitname_db.cpp:92
1775467ms       th_a         load_indexes ] load indexes            bitname_db.cpp:107
1775470ms       th_a      init_timekeeper ] ...init stats...            bitname_db.cpp:162
1775470ms       th_a      init_timekeeper ] ...done init timekeeper...          bitname_db.cpp:164
1775470ms       th_a                 open ] open name db            bitname_db.cpp:214
1778964ms       th_a            configure ] listening for rpc connections on port 9877          rpc_server.cpp:245
1778965ms       th_a            configure ] listening for rpc connections on port 9877          rpc_server.cpp:247
1782681ms       th_a   KeyhoteeMainWindow ] idents: []          KeyhoteeMainWindow.cpp:246
1794588ms       th_a    accept_connection ] accepted connection from 127.0.0.1:48542            server.cpp:114
1794588ms       th_a         on_connected ] on connected...         peer_channel.cpp:162
1794589ms       th_a     handle_subscribe ] 127.0.0.1:48542: {"channels":[{"proto":"chat_proto","chan":0},{"proto":"name_proto","chan":0},{"proto":"peer_proto","chan":0}]}         peer_channel.cpp:339
1794589ms       th_a request_block_header ] requesting block headers from 127.0.0.1:48542           bitname_channel.cpp:498
1794590ms       th_a       handle_message ] get_headers_msg         bitname_channel.cpp:444
1794590ms       th_a       handle_message ] headers_msg         bitname_channel.cpp:444
1794590ms       th_a       handle_headers ] received ${x} block headers         bitname_channel.cpp:727
1795095ms       th_a                 stop ] stopping at block version 0         bitname_miner.cpp:194
1806437ms       th_a      start_new_block ] start_new_block()           bitname_miner.cpp:131
1806437ms   bitname1 start_mining_in_mini ] start_mining_in_mining_thread           bitname_miner.cpp:68
1806482ms       th_a        store_contact ] to_string()         addressbook.cpp:110
1806497ms       th_a        store_contact ] ... did it work?            addressbook.cpp:112
1807152ms   bitname1 start_mining_in_mini ] ++++   2  ++++++++++++found: {"nonce":31038,"age":1,"utc_sec":"20131230T142959","trxs_hash":"162018234875081307372861003289426008907","name_hash":8980070599008415687,"repute_points":1,"master_key":"037a7820fe3aff86667521c9389a04147ec2e86a9e518f64c4ec4cb2a3803f6fa6","active_key":"037a7820fe3aff86667521c9389a04147ec2e86a9e518f64c4ec4cb2a3803f6fa6","change_sig":null,"prev":"df12d19b07ca6dfcc179adfb48ab4f0350882e9d84c735119b647f4f","name_trxs":[]}    20131230T143007.152222  difficulty: 9795718          bitname_miner.cpp:85
1807152ms   bitname1 start_mining_in_mini ] RETURN start_mining_in_mining_thread  2         bitname_miner.cpp:97
1807152ms       th_a     found_name_block ] found block 000001b6741b40805d511afd47d1d3009c7eba64a10a0d7da3b9b860  difficulty: 9795718 
{"nonce":31038,"age":1,"utc_sec":"20131230T142959","trxs_hash":"162018234875081307372861003289426008907","name_hash":8980070599008415687,"repute_points":1,"master_key":"037a7820fe3aff86667521c9389a04147ec2e86a9e518f64c4ec4cb2a3803f6fa6","active_key":"037a7820fe3aff86667521c9389a04147ec2e86a9e518f64c4ec4cb2a3803f6fa6","change_sig":null,"prev":"df12d19b07ca6dfcc179adfb48ab4f0350882e9d84c735119b647f4f","name_trxs":[]}          bitname_client.cpp:34
1807153ms       th_a         submit_block ] target diff: 1048576  block diff 9795718 prev block:df12d19b07ca6dfcc179adfb48ab4f0350882e9d84c735119b647f4f            bitname_channel.cpp:858
1807214ms       th_a            validated ] 000001b6741b40805d511afd47d1d3009c7eba64a10a0d7da3b9b860   {"header":{"nonce":31038,"age":1,"utc_sec":"20131230T142959","trxs_hash":"162018234875081307372861003289426008907","name_hash":8980070599008415687,"repute_points":1,"master_key":"037a7820fe3aff86667521c9389a04147ec2e86a9e518f64c4ec4cb2a3803f6fa6","active_key":"037a7820fe3aff86667521c9389a04147ec2e86a9e518f64c4ec4cb2a3803f6fa6","change_sig":null,"prev":"df12d19b07ca6dfcc179adfb48ab4f0350882e9d84c735119b647f4f"},"name_trxs":[]}   true         broadcast_manager.hpp:129
1807216ms       th_a     name_block_added ] name block added
{
  "nonce": 31038,
  "age": 1,
  "utc_sec": "20131230T142959",
  "trxs_hash": "162018234875081307372861003289426008907",
  "name_hash": 8980070599008415687,
  "repute_points": 1,
  "master_key": "037a7820fe3aff86667521c9389a04147ec2e86a9e518f64c4ec4cb2a3803f6fa6",
  "active_key": "037a7820fe3aff86667521c9389a04147ec2e86a9e518f64c4ec4cb2a3803f6fa6",
  "change_sig": null,
  "prev": "df12d19b07ca6dfcc179adfb48ab4f0350882e9d84c735119b647f4f",
  "name_trxs": []
}           bitname_client.cpp:60
1807216ms       th_a      start_new_block ] start_new_block()           bitname_miner.cpp:131
1807216ms   bitname1 start_mining_in_mini ] start_mining_in_mining_thread           bitname_miner.cpp:68
1807222ms       th_a      start_new_block ] start_new_block()           bitname_miner.cpp:131
1807222ms   bitname1 start_mining_in_mini ] EXIT start_mining_in_mining_thread  4           bitname_miner.cpp:104
1807222ms   bitname1 start_mining_in_mini ] start_mining_in_mining_thread           bitname_miner.cpp:68
1807222ms       th_a       handle_message ] get_block_index_msg         bitname_channel.cpp:444
1807223ms       th_a handle_get_block_ind ] {"block_id":"000001b6741b40805d511afd47d1d3009c7eba64a10a0d7da3b9b860"}         bitname_channel.cpp:588
1809409ms       th_a   displayFailureInfo ] unspecified
name jj has already been reserved as {"last_update":"20131230T142959","master_key":"037a7820fe3aff86667521c9389a04147ec2e86a9e518f64c4ec4cb2a3803f6fa6","active_key":"037a7820fe3aff86667521c9389a04147ec2e86a9e518f64c4ec4cb2a3803f6fa6","revoked":false,"age":1,"repute":1,"name_hash":"c76fd39fa19e9f7c","name":"jj"}
    {"bitname_id":"jj","record":{"last_update":"20131230T142959","master_key":"037a7820fe3aff86667521c9389a04147ec2e86a9e518f64c4ec4cb2a3803f6fa6","active_key":"037a7820fe3aff86667521c9389a04147ec2e86a9e518f64c4ec4cb2a3803f6fa6","revoked":false,"age":1,"repute":1,"name_hash":"c76fd39fa19e9f7c","name":"jj"}}
    th_a  bitname_client.cpp:225 mine_name
name: jj key: 021a1847058a604f5d396dca0d374431502714d63d72b6e2b08284824f4ae54130
    {"name":"jj","key":"021a1847058a604f5d396dca0d374431502714d63d72b6e2b08284824f4ae54130"}
    th_a  bitname_client.cpp:229 mine_name
name: jj
    {"name":"jj"}
    th_a  application.cpp:304 mine_name         KeyhoteeApplication.cpp:207
1809409ms       th_a   displayFailureInfo ] fatal error unspecified
name jj has already been reserved as {"last_update":"20131230T142959","master_key":"037a7820fe3aff86667521c9389a04147ec2e86a9e518f64c4ec4cb2a3803f6fa6","active_key":"037a7820fe3aff86667521c9389a04147ec2e86a9e518f64c4ec4cb2a3803f6fa6","revoked":false,"age":1,"repute":1,"name_hash":"c76fd39fa19e9f7c","name":"jj"}
    {"bitname_id":"jj","record":{"last_update":"20131230T142959","master_key":"037a7820fe3aff86667521c9389a04147ec2e86a9e518f64c4ec4cb2a3803f6fa6","active_key":"037a7820fe3aff86667521c9389a04147ec2e86a9e518f64c4ec4cb2a3803f6fa6","revoked":false,"age":1,"repute":1,"name_hash":"c76fd39fa19e9f7c","name":"jj"}}
    th_a  bitname_client.cpp:225 mine_name
name: jj key: 021a1847058a604f5d396dca0d374431502714d63d72b6e2b08284824f4ae54130
    {"name":"jj","key":"021a1847058a604f5d396dca0d374431502714d63d72b6e2b08284824f4ae54130"}
    th_a  bitname_client.cpp:229 mine_name
name: jj
    {"name":"jj"}
    th_a  application.cpp:304 mine_name         KeyhoteeApplication.cpp:209

**Comment by vogel76** [comment]
Looks like there is some inconsistency between bts::profile::get_identity (returning null) and fc::optional<name_record> name_channel::lookup_name( const std::string& name ) called from void client::mine_name( const std::string& bitname_id, const fc::ecc::public_key& name_key).
Second function returns found object, but with different public key what is firing an exception:
     if( current_record  && current_record->master_key != name_key )
     {
        FC_THROW_EXCEPTION( exception, "name ${bitname_id} has already been reserved as ${record}",
                                         ("bitname_id",bitname_id)("record",*current_record) );
     }

**Comment by dnotestein** [comment]
Yes,  sounds like problem is that get_identity doesn't properly treat ids such as "aaa" and "aaaa" as same identity (so it is then allowed to create two identities when really they should be the same as far as keyhotee system is concerned). Keyhotee treats these names as same to avoid phishing attacks related to the similar looking names. mine_name function does properly recognize they are same name and throws an error that name is already registered.

**Comment by dnotestein** [comment]
Simple solution was just to catch the exception and let user try to register already registered IDs. This is reasonable, since at some point the ID may be abandoned or revoked. The status in the New Identity dialog reports if the ID is already registered to someone.
