### ISSUE TITLE
Selecting multiple contacts and press "DELETE" leads to crash

### ISSUE THREAD

**Issue by yuvarajgogoi** [InvictusInnovations/keyhotee#157]
Steps to reproduce:
1) select multiple contacts.
2) press DELETE
crash is seen

Tested on Ubuntu

log:
3015178ms       th_a              startup ] .           KeyhoteeApplication.cpp:265
3015178ms       th_a         get_profiles ] /home/yuvi/.local/share/Keyhotee/profiles/Y G           application.cpp:212
3015178ms       th_a         get_profiles ] /home/yuvi/.local/share/Keyhotee/profiles/J G           application.cpp:212
3015178ms       th_a         get_profiles ] profiles ["Y G","J G"]          application.cpp:217
3015178ms       th_a         displayLogin ] .           KeyhoteeApplication.cpp:173
3015208ms       th_a         get_profiles ] /home/yuvi/.local/share/Keyhotee/profiles/Y G           application.cpp:212
3015208ms       th_a         get_profiles ] /home/yuvi/.local/share/Keyhotee/profiles/J G           application.cpp:212
3015208ms       th_a         get_profiles ] profiles ["Y G","J G"]          application.cpp:217
3015208ms       th_a          LoginDialog ] profiles Y G            LoginDialog.cpp:23
3015208ms       th_a          LoginDialog ] profiles J G            LoginDialog.cpp:23
3022898ms       th_a            configure ] external IP 106.51.180.42           application.cpp:139
3022898ms       th_a            configure ] listening for stcp connections on port 10876            server.cpp:206
3024537ms       th_a         load_indexes ] load indexes            bitname_db.cpp:92
3024537ms       th_a         load_indexes ] load indexes            bitname_db.cpp:107
3024540ms       th_a      init_timekeeper ] ...init stats...            bitname_db.cpp:162
3024540ms       th_a      init_timekeeper ] ...done init timekeeper...          bitname_db.cpp:164
3024540ms       th_a                 open ] open name db            bitname_db.cpp:214
3027544ms       th_a            configure ] listening for rpc connections on port 10877         rpc_server.cpp:245
3027545ms       th_a            configure ] listening for rpc connections on port 10877         rpc_server.cpp:247
3028311ms       th_a                 open ] loading contact {"public_key":"02ca203b68a9d040acff38132aa06570d720d620495eb645b85b3a1e2b1540d594","dac_id_hash":3559173316646878897,"dac_id_string":"fffff","properties":[],"wallet_index":0,"privacy_setting":"secret_contact","first_name":"","last_name":"","icon_png":"","notes":"","next_send_trx_id":0,"send_trx_address":{"pub_key":"000000000000000000000000000000000000000000000000000000000000000000","chain_code":"0000000000000000000000000000000000000000000000000000000000000000"},"bitchat_recv_channels":[],"bitchat_broadcast_channels":[],"bitchat_recv_broadcast_key":"0000000000000000000000000000000000000000000000000000000000000000"}           addressbook.cpp:58
3028312ms       th_a                 open ] loading contact {"public_key":"029e31f57b71ab8f31fdafbc876219bd19eb7ed8a6c08a020367be3a883fe8b3ab","dac_id_hash":3559173316646878897,"dac_id_string":"fffffff","properties":[],"wallet_index":1,"privacy_setting":"secret_contact","first_name":"","last_name":"","icon_png":"","notes":"","next_send_trx_id":0,"send_trx_address":{"pub_key":"000000000000000000000000000000000000000000000000000000000000000000","chain_code":"0000000000000000000000000000000000000000000000000000000000000000"},"bitchat_recv_channels":[],"bitchat_broadcast_channels":[],"bitchat_recv_broadcast_key":"0000000000000000000000000000000000000000000000000000000000000000"}         addressbook.cpp:58
3028313ms       th_a                 open ] loading contact {"public_key":"037c7679f8dfee2bf386a84275468268b3424937a098017c35f3021cf8b006fa52","dac_id_hash":3559173316646878897,"dac_id_string":"fffffffff","properties":[],"wallet_index":2,"privacy_setting":"secret_contact","first_name":"","last_name":"","icon_png":"","notes":"","next_send_trx_id":0,"send_trx_address":{"pub_key":"000000000000000000000000000000000000000000000000000000000000000000","chain_code":"0000000000000000000000000000000000000000000000000000000000000000"},"bitchat_recv_channels":[],"bitchat_broadcast_channels":[],"bitchat_recv_broadcast_key":"0000000000000000000000000000000000000000000000000000000000000000"}           addressbook.cpp:58
3028314ms       th_a                 open ] loading contact {"public_key":"03327826901572fc7292e1b552ea1e6d016da5dc70f9c088352d74f7b7ae9c5c3e","dac_id_hash":3559173316646878897,"dac_id_string":"ff","properties":[],"wallet_index":3,"privacy_setting":"secret_contact","first_name":"","last_name":"","icon_png":"","notes":"","next_send_trx_id":0,"send_trx_address":{"pub_key":"000000000000000000000000000000000000000000000000000000000000000000","chain_code":"0000000000000000000000000000000000000000000000000000000000000000"},"bitchat_recv_channels":[],"bitchat_broadcast_channels":[],"bitchat_recv_broadcast_key":"0000000000000000000000000000000000000000000000000000000000000000"}          addressbook.cpp:58
3028315ms       th_a                 open ] loading contact {"public_key":"03aefbd8edd18d69259f25c829bf35da9b333bd761fc3aa61a1a501f05e82a5552","dac_id_hash":3559173316646878897,"dac_id_string":"fffffffffffffffffff","properties":[],"wallet_index":4,"privacy_setting":"secret_contact","first_name":"","last_name":"","icon_png":"","notes":"","next_send_trx_id":0,"send_trx_address":{"pub_key":"000000000000000000000000000000000000000000000000000000000000000000","chain_code":"0000000000000000000000000000000000000000000000000000000000000000"},"bitchat_recv_channels":[],"bitchat_broadcast_channels":[],"bitchat_recv_broadcast_key":"0000000000000000000000000000000000000000000000000000000000000000"}         addressbook.cpp:58
3028316ms       th_a                 open ] loading contact {"public_key":"03cf2516fe8e3c4c81a5bda741147204ed4801794d97613113923da600705e5a36","dac_id_hash":3559173316646878897,"dac_id_string":"fffffffffffffff","properties":[],"wallet_index":5,"privacy_setting":"secret_contact","first_name":"","last_name":"","icon_png":"","notes":"","next_send_trx_id":0,"send_trx_address":{"pub_key":"000000000000000000000000000000000000000000000000000000000000000000","chain_code":"0000000000000000000000000000000000000000000000000000000000000000"},"bitchat_recv_channels":[],"bitchat_broadcast_channels":[],"bitchat_recv_broadcast_key":"0000000000000000000000000000000000000000000000000000000000000000"}         addressbook.cpp:58
3028317ms       th_a                 open ] loading contact {"public_key":"02c2b1851b422d9a5df3ea09b228421873e8f251a26b3d747ee6b5ac17d25cd45f","dac_id_hash":3559173316646878897,"dac_id_string":"f","properties":[],"wallet_index":6,"privacy_setting":"secret_contact","first_name":"","last_name":"","icon_png":"","notes":"","next_send_trx_id":0,"send_trx_address":{"pub_key":"000000000000000000000000000000000000000000000000000000000000000000","chain_code":"0000000000000000000000000000000000000000000000000000000000000000"},"bitchat_recv_channels":[],"bitchat_broadcast_channels":[],"bitchat_recv_broadcast_key":"0000000000000000000000000000000000000000000000000000000000000000"}           addressbook.cpp:58
3032224ms       th_a       reloadContacts ] loading contacts...         AddressBookModel.cpp:326
3032224ms       th_a       reloadContacts ] loading contacts...         AddressBookModel.cpp:326
3032224ms       th_a       reloadContacts ] loading contacts...         AddressBookModel.cpp:326
3032224ms       th_a       reloadContacts ] loading contacts...         AddressBookModel.cpp:326
3032224ms       th_a       reloadContacts ] loading contacts...         AddressBookModel.cpp:326
3032225ms       th_a       reloadContacts ] loading contacts...         AddressBookModel.cpp:326
3032225ms       th_a       reloadContacts ] loading contacts...         AddressBookModel.cpp:326
3032229ms       th_a   KeyhoteeMainWindow ] idents: [{"public_key":"02c2b1851b422d9a5df3ea09b228421873e8f251a26b3d747ee6b5ac17d25cd45f","dac_id_hash":3559173316646878897,"dac_id_string":"f","properties":[],"wallet_ident":"f","mining_effort":1,"first_name":"","last_name":"","private_icon_png":""},{"public_key":"03327826901572fc7292e1b552ea1e6d016da5dc70f9c088352d74f7b7ae9c5c3e","dac_id_hash":3559173316646878897,"dac_id_string":"ff","properties":[],"wallet_ident":"ff","mining_effort":0,"first_name":"","last_name":"","private_icon_png":""},{"public_key":"02ca203b68a9d040acff38132aa06570d720d620495eb645b85b3a1e2b1540d594","dac_id_hash":3559173316646878897,"dac_id_string":"fffff","properties":[],"wallet_ident":"fffff","mining_effort":0,"first_name":"","last_name":"","private_icon_png":""},{"public_key":"029e31f57b71ab8f31fdafbc876219bd19eb7ed8a6c08a020367be3a883fe8b3ab","dac_id_hash":3559173316646878897,"dac_id_string":"fffffff","properties":[],"wallet_ident":"fffffff","mining_effort":0,"first_name":"","last_name":"","private_icon_png":""},{"public_key":"037c7679f8dfee2bf386a84275468268b3424937a098017c35f3021cf8b006fa52","dac_id_hash":3559173316646878897,"dac_id_string":"fffffffff","properties":[],"wallet_ident":"fffffffff","mining_effort":0,"first_name":"","last_name":"","private_icon_png":""},{"public_key":"03cf2516fe8e3c4c81a5bda741147204ed4801794d97613113923da600705e5a36","dac_id_hash":3559173316646878897,"dac_id_string":"fffffffffffffff","properties":[],"wallet_ident":"fffffffffffffff","mining_effort":0,"first_name":"","last_name":"","private_icon_png":""},{"public_key":"03aefbd8edd18d69259f25c829bf35da9b333bd761fc3aa61a1a501f05e82a5552","dac_id_hash":3559173316646878897,"dac_id_string":"fffffffffffffffffff","properties":[],"wallet_ident":"fffffffffffffffffff","mining_effort":0,"first_name":"","last_name":"","private_icon_png":""}]         KeyhoteeMainWindow.cpp:246
3032294ms       th_a         connect_loop ] 127.0.0.1:9876          application.cpp:59
3032294ms       th_a           connect_to ] connect to 127.0.0.1:9876           server.cpp:243
3032297ms       th_a         connect_loop ] unspecified
Broken pipe 
    {"message":"Broken pipe"}
    asio  asio.cpp:28 read_write_handler
error connecting to 127.0.0.1:9876
    {"ep":"127.0.0.1:9876"}
    th_a  connection.cpp:194 connect
unable to connect to 127.0.0.1:9876
    {"ep":"127.0.0.1:9876"}
    th_a  server.cpp:256 connect_to         application.cpp:64
3035298ms       th_a         connect_loop ] 127.0.0.1:9876          application.cpp:59
3035298ms       th_a           connect_to ] connect to 127.0.0.1:9876           server.cpp:243
3035301ms       th_a         connect_loop ] unspecified
Broken pipe 
    {"message":"Broken pipe"}
    asio  asio.cpp:28 read_write_handler
error connecting to 127.0.0.1:9876
    {"ep":"127.0.0.1:9876"}
    th_a  connection.cpp:194 connect
unable to connect to 127.0.0.1:9876
    {"ep":"127.0.0.1:9876"}
    th_a  server.cpp:256 connect_to         application.cpp:64
3038301ms       th_a         connect_loop ] 127.0.0.1:9876          application.cpp:59
3038301ms       th_a           connect_to ] connect to 127.0.0.1:9876           server.cpp:243
3038376ms       th_a         connect_loop ] unspecified
Broken pipe 
    {"message":"Broken pipe"}
    asio  asio.cpp:28 read_write_handler
error connecting to 127.0.0.1:9876
    {"ep":"127.0.0.1:9876"}
    th_a  connection.cpp:194 connect
unable to connect to 127.0.0.1:9876
    {"ep":"127.0.0.1:9876"}
    th_a  server.cpp:256 connect_to         application.cpp:64
3040480ms       th_a   displayFailureInfo ] Unknown exception caught            KeyhoteeApplication.cpp:207
3040481ms       th_a   displayFailureInfo ] fatal error Unknown exception caught            KeyhoteeApplication.cpp:209

**Comment by yuvarajgogoi** [comment]
Tested in a new clean repo.
crash is seen in the same scenario:

log:

1286874ms       th_a              startup ] .           KeyhoteeApplication.cpp:263
1286875ms       th_a         get_profiles ] /home/yuvi/.local/share/Keyhotee/profiles/Y G           application.cpp:212
1286875ms       th_a         get_profiles ] /home/yuvi/.local/share/Keyhotee/profiles/J G           application.cpp:212
1286875ms       th_a         get_profiles ] profiles ["Y G","J G"]          application.cpp:217
1286875ms       th_a         displayLogin ] .           KeyhoteeApplication.cpp:171
1286907ms       th_a         get_profiles ] /home/yuvi/.local/share/Keyhotee/profiles/Y G           application.cpp:212
1286907ms       th_a         get_profiles ] /home/yuvi/.local/share/Keyhotee/profiles/J G           application.cpp:212
1286907ms       th_a         get_profiles ] profiles ["Y G","J G"]          application.cpp:217
1286907ms       th_a          LoginDialog ] profiles Y G            LoginDialog.cpp:27
1286907ms       th_a          LoginDialog ] profiles J G            LoginDialog.cpp:27
1295813ms       th_a            configure ] external IP 106.51.180.42           application.cpp:139
1295813ms       th_a            configure ] listening for stcp connections on port 9876         server.cpp:206
1297069ms       th_a         load_indexes ] load indexes            bitname_db.cpp:92
1297070ms       th_a         load_indexes ] load indexes            bitname_db.cpp:107
1297072ms       th_a      init_timekeeper ] ...init stats...            bitname_db.cpp:162
1297072ms       th_a      init_timekeeper ] ...done init timekeeper...          bitname_db.cpp:164
1297073ms       th_a                 open ] open name db            bitname_db.cpp:214
1300307ms       th_a            configure ] listening for rpc connections on port 9877          rpc_server.cpp:245
1300307ms       th_a            configure ] listening for rpc connections on port 9877          rpc_server.cpp:247
1304764ms       th_a   KeyhoteeMainWindow ] idents: []          KeyhoteeMainWindow.cpp:252
1310335ms       th_a    accept_connection ] accepted connection from 127.0.0.1:41871            server.cpp:114
1310399ms       th_a         on_connected ] on connected...         peer_channel.cpp:162
1310411ms       th_a     handle_subscribe ] 127.0.0.1:41871: {"channels":[{"proto":"chat_proto","chan":0},{"proto":"name_proto","chan":0},{"proto":"peer_proto","chan":0}]}         peer_channel.cpp:339
1310439ms       th_a request_block_header ] requesting block headers from 127.0.0.1:41871           bitname_channel.cpp:498
1310453ms       th_a       handle_message ] get_headers_msg         bitname_channel.cpp:444
1310470ms       th_a       handle_message ] headers_msg         bitname_channel.cpp:444
1310470ms       th_a       handle_headers ] received ${x} block headers         bitname_channel.cpp:727
1319308ms       th_a        store_contact ] to_string()         addressbook.cpp:110
1319320ms       th_a        store_contact ] ... did it work?            addressbook.cpp:112
1325194ms       th_a        store_contact ] to_string()         addressbook.cpp:110
1325194ms       th_a        store_contact ] ... did it work?            addressbook.cpp:112
1338373ms       th_a   displayFailureInfo ] Unknown exception caught            KeyhoteeApplication.cpp:205
1338373ms       th_a   displayFailureInfo ] fatal error Unknown exception caught            KeyhoteeApplication.cpp:207

**Comment by yuvarajgogoi** [comment]
Tested on Ubuntu only.
will provide the callstack in a while.

**Comment by dnotestein** [comment]
I can dup this on windows. In my test case, I deleted my own contact and other guys contact and it crashed.

**Comment by yuvarajgogoi** [comment]
Also some more info on the steps to reproduce:

please delete more than identity from the contact list to reproduce the issue.

callstack :

0   KeyhoteeMainWindow::deleteContactGui    KeyhoteeMainWindow.cpp  732 0x55d078  
1   call    qobjectdefs_impl.h  508 0x5619e9  
2   callQtPrivate::List<int, void>    qobjectdefs_impl.h  527 0x5619e9  
3   impl    qobject_impl.h  147 0x5619e9  
4   QtPrivate::QSlotObject<void (KeyhoteeMainWindow::*)(int), QtPrivate::List<int>, void>::impl qobject_impl.h  140 0x5619e9  
5   QMetaObject::activate(QObject_, int, int, void__)   /home/yuvi/software/install/qt5.1.1/5.1.1/gcc_64/lib/libQt5Core.so.5        0x7ffff6304415  
6   ContactsTable::contactDeleted   moc_ContactsTable.cpp   171 0x575921  
7   ContactsTable::onDeleteContact  ContactsTable.cpp   112 0x508b69  
8   QMetaObject::activate(QObject_, int, int, void*_)   /home/yuvi/software/install/qt5.1.1/5.1.1/gcc_64/lib/libQt5Core.so.5        0x7ffff6304261  
9   QAction::triggered(bool)    /home/yuvi/software/install/qt5.1.1/5.1.1/gcc_64/lib/libQt5Widgets.so.5     0x7ffff76e5ba2  
10  QAction::activate(QAction::ActionEvent) /home/yuvi/software/install/qt5.1.1/5.1.1/gcc_64/lib/libQt5Widgets.so.5     0x7ffff76e79d7  
11  QAction::event(QEvent_) /home/yuvi/software/install/qt5.1.1/5.1.1/gcc_64/lib/libQt5Widgets.so.5     0x7ffff76e7ccf  
12  QApplicationPrivate::notify_helper(QObject_, QEvent_)   /home/yuvi/software/install/qt5.1.1/5.1.1/gcc_64/lib/libQt5Widgets.so.5     0x7ffff76f0b54  
13  QApplication::notify(QObject_, QEvent_) /home/yuvi/software/install/qt5.1.1/5.1.1/gcc_64/lib/libQt5Widgets.so.5     0x7ffff76f3fe6  
14  TKeyhoteeApplication::notify    KeyhoteeApplication.cpp 216 0x552639  
15  QCoreApplication::notifyInternal(QObject_, QEvent_) /home/yuvi/software/install/qt5.1.1/5.1.1/gcc_64/lib/libQt5Core.so.5        0x7ffff62dcdd4  
16  QShortcutMap::dispatchEvent(QKeyEvent_) /home/yuvi/software/install/qt5.1.1/5.1.1/gcc_64/lib/libQt5Gui.so.5     0x7ffff6809e91  
17  QShortcutMap::tryShortcutEvent(QObject_, QKeyEvent_)    /home/yuvi/software/install/qt5.1.1/5.1.1/gcc_64/lib/libQt5Gui.so.5     0x7ffff680ad8a  
18  QApplication::notify(QObject_, QEvent_) /home/yuvi/software/install/qt5.1.1/5.1.1/gcc_64/lib/libQt5Widgets.so.5     0x7ffff76f3f88  
19  TKeyhoteeApplication::notify    KeyhoteeApplication.cpp 216 0x552639  
20  QCoreApplication::notifyInternal(QObject_, QEvent_) /home/yuvi/software/install/qt5.1.1/5.1.1/gcc_64/lib/libQt5Core.so.5        0x7ffff62dcdd4  
21  QGuiApplicationPrivate::processKeyEvent(QWindowSystemInterfacePrivate::KeyEvent_)   /home/yuvi/software/install/qt5.1.1/5.1.1/gcc_64/lib/libQt5Gui.so.5     0x7ffff67df714  
22  QGuiApplicationPrivate::processWindowSystemEvent(QWindowSystemInterfacePrivate::WindowSystemEvent*) /home/yuvi/software/install/qt5.1.1/5.1.1/gcc_64/lib/libQt5Gui.so.5     0x7ffff67e892d  
23  QWindowSystemInterface::sendWindowSystemEventsImplementation(QFlagsQEventLoop::ProcessEventsFlag) /home/yuvi/software/install/qt5.1.1/5.1.1/gcc_64/lib/libQt5Gui.so.5     0x7ffff67d1a98  
24  ??  /home/yuvi/software/install/qt5.1.1/5.1.1/gcc_64/plugins/platforms/libqxcb.so       0x7ffff0342940  
25  g_main_context_dispatch /lib/x86_64-linux-gnu/libglib-2.0.so.0      0x7ffff4f99f05  
26  ??  /lib/x86_64-linux-gnu/libglib-2.0.so.0      0x7ffff4f9a248  
27  g_main_context_iteration    /lib/x86_64-linux-gnu/libglib-2.0.so.0      0x7ffff4f9a304  
28  QEventDispatcherGlib::processEvents(QFlagsQEventLoop::ProcessEventsFlag)  /home/yuvi/software/install/qt5.1.1/5.1.1/gcc_64/lib/libQt5Core.so.5        0x7ffff6327314  
29  QEventLoop::exec(QFlagsQEventLoop::ProcessEventsFlag) /home/yuvi/software/install/qt5.1.1/5.1.1/gcc_64/lib/libQt5Core.so.5        0x7ffff62dbb6b  
30  QCoreApplication::exec()    /home/yuvi/software/install/qt5.1.1/5.1.1/gcc_64/lib/libQt5Core.so.5        0x7ffff62dfbbe  
31  TKeyhoteeApplication::run   KeyhoteeApplication.cpp 154 0x552a84  
32  TKeyhoteeApplication::run   KeyhoteeApplication.cpp 72  0x55395e  
33  main    main.cpp    26  0x4fcb22

**Comment by vogel76** [comment]
Fixed at rev: https://github.com/InvictusInnovations/keyhotee/commit/75df75ddb3687558c7565bb1400401eee65518f4
