### ISSUE TITLE
New Contact and Show Contact becomes permanently deactivated in this scenario.

### ISSUE THREAD

**Issue by yuvarajgogoi** [InvictusInnovations/keyhotee#159]
Steps:
1) create multiple identities.
2) select multiple identities in contact list
3) go for menu option contact -> New Contact.
4) Now press CNTL + select any identity in the contact list.

Menu Option "New Contact" and "Show contacts" becomes permanently disabled

Tested on Ubuntu and is always reproducible.

log:
3129610ms       th_a              startup ] .           KeyhoteeApplication.cpp:263
3129610ms       th_a         get_profiles ] /home/yuvi/.local/share/Keyhotee/profiles/Y G           application.cpp:212
3129610ms       th_a         get_profiles ] profiles ["Y G"]            application.cpp:217
3129610ms       th_a         displayLogin ] .           KeyhoteeApplication.cpp:171
3129642ms       th_a         get_profiles ] /home/yuvi/.local/share/Keyhotee/profiles/Y G           application.cpp:212
3129642ms       th_a         get_profiles ] profiles ["Y G"]            application.cpp:217
3129642ms       th_a          LoginDialog ] profiles Y G            LoginDialog.cpp:27
3134794ms       th_a            configure ] external IP 106.51.180.42           application.cpp:139
3134794ms       th_a            configure ] listening for stcp connections on port 0            server.cpp:206
3135551ms       th_a         load_indexes ] load indexes            bitname_db.cpp:92
3135551ms       th_a         load_indexes ] load indexes            bitname_db.cpp:107
3135554ms       th_a      init_timekeeper ] ...init stats...            bitname_db.cpp:162
3135554ms       th_a      init_timekeeper ] ...done init timekeeper...          bitname_db.cpp:164
3135554ms       th_a                 open ] open name db            bitname_db.cpp:214
3138834ms       th_a            configure ] listening for rpc connections on port 0         rpc_server.cpp:245
3138834ms       th_a            configure ] listening for rpc connections on port 60490         rpc_server.cpp:247
3139167ms       th_a                 open ] loading contact {"public_key":"03ceb96ab683c843ed340dec703f62e28f94b228dd22187beac921d37dbe5f7ab9","dac_id_hash":0,"dac_id_string":"yuv1","properties":[],"wallet_index":0,"privacy_setting":"secret_contact","first_name":"","last_name":"","icon_png":"","notes":"","next_send_trx_id":0,"send_trx_address":{"pub_key":"000000000000000000000000000000000000000000000000000000000000000000","chain_code":"0000000000000000000000000000000000000000000000000000000000000000"},"bitchat_recv_channels":[],"bitchat_broadcast_channels":[],"bitchat_recv_broadcast_key":"0000000000000000000000000000000000000000000000000000000000000000"}          addressbook.cpp:58
3139168ms       th_a                 open ] loading contact {"public_key":"03bdb3e151c5deb2df21c4999580c7953e1fbda90f79d3f5a5db828aab6d10bac6","dac_id_hash":0,"dac_id_string":"yuv","properties":[],"wallet_index":1,"privacy_setting":"secret_contact","first_name":"","last_name":"","icon_png":"","notes":"","next_send_trx_id":0,"send_trx_address":{"pub_key":"000000000000000000000000000000000000000000000000000000000000000000","chain_code":"0000000000000000000000000000000000000000000000000000000000000000"},"bitchat_recv_channels":[],"bitchat_broadcast_channels":[],"bitchat_recv_broadcast_key":"0000000000000000000000000000000000000000000000000000000000000000"}           addressbook.cpp:58
3139169ms       th_a                 open ] loading contact {"public_key":"03ffb54083698232db5f9cc7d228037eb2e3784c7d37374681d34d12a8ddc7dfb1","dac_id_hash":0,"dac_id_string":"yuva","properties":[],"wallet_index":2,"privacy_setting":"secret_contact","first_name":"","last_name":"","icon_png":"","notes":"","next_send_trx_id":0,"send_trx_address":{"pub_key":"000000000000000000000000000000000000000000000000000000000000000000","chain_code":"0000000000000000000000000000000000000000000000000000000000000000"},"bitchat_recv_channels":[],"bitchat_broadcast_channels":[],"bitchat_recv_broadcast_key":"0000000000000000000000000000000000000000000000000000000000000000"}          addressbook.cpp:58
3139170ms       th_a                 open ] loading contact {"public_key":"035728b2a70638a1c58ec1ce35f04e74175eaf7124ed38f8c20115159679da178d","dac_id_hash":12774264012029919657,"dac_id_string":"q","properties":[],"wallet_index":3,"privacy_setting":"secret_contact","first_name":"","last_name":"","icon_png":"","notes":"","next_send_trx_id":0,"send_trx_address":{"pub_key":"000000000000000000000000000000000000000000000000000000000000000000","chain_code":"0000000000000000000000000000000000000000000000000000000000000000"},"bitchat_recv_channels":[],"bitchat_broadcast_channels":[],"bitchat_recv_broadcast_key":"0000000000000000000000000000000000000000000000000000000000000000"}          addressbook.cpp:58
3139171ms       th_a                 open ] loading contact {"public_key":"03622c7ddba9f486382c4bf4206328dd2e0d0a9ff50ccdeb5900ca5bc694fbd8df","dac_id_hash":3488067140818228783,"dac_id_string":"as","properties":[],"wallet_index":4,"privacy_setting":"secret_contact","first_name":"","last_name":"","icon_png":"","notes":"","next_send_trx_id":0,"send_trx_address":{"pub_key":"000000000000000000000000000000000000000000000000000000000000000000","chain_code":"0000000000000000000000000000000000000000000000000000000000000000"},"bitchat_recv_channels":[],"bitchat_broadcast_channels":[],"bitchat_recv_broadcast_key":"0000000000000000000000000000000000000000000000000000000000000000"}          addressbook.cpp:58
3139172ms       th_a                 open ] loading contact {"public_key":"0381df89a893f0fe5a119822474dcf107ba880aa085388253f5384627a9a1ce2db","dac_id_hash":3559173316646878897,"dac_id_string":"fffff","properties":[],"wallet_index":5,"privacy_setting":"secret_contact","first_name":"","last_name":"","icon_png":"","notes":"","next_send_trx_id":0,"send_trx_address":{"pub_key":"000000000000000000000000000000000000000000000000000000000000000000","chain_code":"0000000000000000000000000000000000000000000000000000000000000000"},"bitchat_recv_channels":[],"bitchat_broadcast_channels":[],"bitchat_recv_broadcast_key":"0000000000000000000000000000000000000000000000000000000000000000"}           addressbook.cpp:58
3139173ms       th_a                 open ] loading contact {"public_key":"03d568643402eceade3c507ac3854f5e31899e1ac50b95024ac16c5cf76c6d6d53","dac_id_hash":3559173316646878897,"dac_id_string":"ffffff","properties":[],"wallet_index":6,"privacy_setting":"secret_contact","first_name":"","last_name":"","icon_png":"","notes":"","next_send_trx_id":0,"send_trx_address":{"pub_key":"000000000000000000000000000000000000000000000000000000000000000000","chain_code":"0000000000000000000000000000000000000000000000000000000000000000"},"bitchat_recv_channels":[],"bitchat_broadcast_channels":[],"bitchat_recv_broadcast_key":"0000000000000000000000000000000000000000000000000000000000000000"}          addressbook.cpp:58
3139173ms       th_a                 open ] loading contact {"public_key":"02f2261fbe096bda4f8bda71f97019105bf85a52c32de83649cf5b116a5c8a6b9b","dac_id_hash":3559173316646878897,"dac_id_string":"ffff","properties":[],"wallet_index":7,"privacy_setting":"secret_contact","first_name":"","last_name":"","icon_png":"","notes":"","next_send_trx_id":0,"send_trx_address":{"pub_key":"000000000000000000000000000000000000000000000000000000000000000000","chain_code":"0000000000000000000000000000000000000000000000000000000000000000"},"bitchat_recv_channels":[],"bitchat_broadcast_channels":[],"bitchat_recv_broadcast_key":"0000000000000000000000000000000000000000000000000000000000000000"}            addressbook.cpp:58
3142729ms       th_a       reloadContacts ] loading contacts...         AddressBookModel.cpp:326
3142729ms       th_a       reloadContacts ] loading contacts...         AddressBookModel.cpp:326
3142729ms       th_a       reloadContacts ] loading contacts...         AddressBookModel.cpp:326
3142729ms       th_a       reloadContacts ] loading contacts...         AddressBookModel.cpp:326
3142729ms       th_a       reloadContacts ] loading contacts...         AddressBookModel.cpp:326
3142729ms       th_a       reloadContacts ] loading contacts...         AddressBookModel.cpp:326
3142729ms       th_a       reloadContacts ] loading contacts...         AddressBookModel.cpp:326
3142729ms       th_a       reloadContacts ] loading contacts...         AddressBookModel.cpp:326
3142735ms       th_a   KeyhoteeMainWindow ] idents: [{"public_key":"03622c7ddba9f486382c4bf4206328dd2e0d0a9ff50ccdeb5900ca5bc694fbd8df","dac_id_hash":3488067140818228783,"dac_id_string":"as","properties":[],"wallet_ident":"as","mining_effort":0,"first_name":"","last_name":"","private_icon_png":""},{"public_key":"027ce3c1ebe462e035b57a67583aa89de1d41acfa56069b40a5db1e8fd34a64262","dac_id_hash":12774264012029919657,"dac_id_string":"d","properties":[],"wallet_ident":"d","mining_effort":0,"first_name":"","last_name":"","private_icon_png":""},{"public_key":"02f2261fbe096bda4f8bda71f97019105bf85a52c32de83649cf5b116a5c8a6b9b","dac_id_hash":3559173316646878897,"dac_id_string":"ffff","properties":[],"wallet_ident":"ffff","mining_effort":0,"first_name":"","last_name":"","private_icon_png":""},{"public_key":"0381df89a893f0fe5a119822474dcf107ba880aa085388253f5384627a9a1ce2db","dac_id_hash":3559173316646878897,"dac_id_string":"fffff","properties":[],"wallet_ident":"fffff","mining_effort":0,"first_name":"","last_name":"","private_icon_png":""},{"public_key":"03d568643402eceade3c507ac3854f5e31899e1ac50b95024ac16c5cf76c6d6d53","dac_id_hash":3559173316646878897,"dac_id_string":"ffffff","properties":[],"wallet_ident":"ffffff","mining_effort":0,"first_name":"","last_name":"","private_icon_png":""},{"public_key":"035728b2a70638a1c58ec1ce35f04e74175eaf7124ed38f8c20115159679da178d","dac_id_hash":12774264012029919657,"dac_id_string":"q","properties":[],"wallet_ident":"q","mining_effort":0,"first_name":"","last_name":"","private_icon_png":""},{"public_key":"03bdb3e151c5deb2df21c4999580c7953e1fbda90f79d3f5a5db828aab6d10bac6","dac_id_hash":10021889288155974511,"dac_id_string":"yuv","properties":[],"wallet_ident":"yuv","mining_effort":0,"first_name":"","last_name":"","private_icon_png":""},{"public_key":"03ceb96ab683c843ed340dec703f62e28f94b228dd22187beac921d37dbe5f7ab9","dac_id_hash":9606194778457574965,"dac_id_string":"yuv1","properties":[],"wallet_ident":"yuv1","mining_effort":1,"first_name":"","last_name":"","private_icon_png":""},{"public_key":"03ffb54083698232db5f9cc7d228037eb2e3784c7d37374681d34d12a8ddc7dfb1","dac_id_hash":15876008070338674192,"dac_id_string":"yuva","properties":[],"wallet_ident":"yuva","mining_effort":0,"first_name":"","last_name":"","private_icon_png":""}]         KeyhoteeMainWindow.cpp:252
3142738ms       th_a   KeyhoteeMainWindow ] unspecified
name d has already been reserved as {"last_update":"20131230T182918","master_key":"035728b2a70638a1c58ec1ce35f04e74175eaf7124ed38f8c20115159679da178d","active_key":"035728b2a70638a1c58ec1ce35f04e74175eaf7124ed38f8c20115159679da178d","revoked":false,"age":9,"repute":2,"name_hash":"a9811920704d47b1","name":"d"}
    {"bitname_id":"d","record":{"last_update":"20131230T182918","master_key":"035728b2a70638a1c58ec1ce35f04e74175eaf7124ed38f8c20115159679da178d","active_key":"035728b2a70638a1c58ec1ce35f04e74175eaf7124ed38f8c20115159679da178d","revoked":false,"age":9,"repute":2,"name_hash":"a9811920704d47b1","name":"d"}}
    th_a  bitname_client.cpp:225 mine_name
name: d key: 027ce3c1ebe462e035b57a67583aa89de1d41acfa56069b40a5db1e8fd34a64262
    {"name":"d","key":"027ce3c1ebe462e035b57a67583aa89de1d41acfa56069b40a5db1e8fd34a64262"}
    th_a  bitname_client.cpp:229 mine_name
name: d
    {"name":"d"}
    th_a  application.cpp:304 mine_name         KeyhoteeMainWindow.cpp:262
3142799ms       th_a         connect_loop ] 162.243.67.4:9876           application.cpp:59
3142799ms       th_a           connect_to ] connect to 162.243.67.4:9876            server.cpp:243
3143076ms       th_a         connect_loop ] unspecified
Broken pipe 
    {"message":"Broken pipe"}
    asio  asio.cpp:28 read_write_handler
error connecting to 162.243.67.4:9876
    {"ep":"162.243.67.4:9876"}
    th_a  connection.cpp:194 connect
unable to connect to 162.243.67.4:9876
    {"ep":"162.243.67.4:9876"}
    th_a  server.cpp:256 connect_to         application.cpp:64
3146076ms       th_a         connect_loop ] 162.243.67.4:9876           application.cpp:59
3146076ms       th_a           connect_to ] connect to 162.243.67.4:9876            server.cpp:243
3146325ms       th_a         connect_loop ] unspecified
Broken pipe 
    {"message":"Broken pipe"}
    asio  asio.cpp:28 read_write_handler
error connecting to 162.243.67.4:9876
    {"ep":"162.243.67.4:9876"}
    th_a  connection.cpp:194 connect
unable to connect to 162.243.67.4:9876
    {"ep":"162.243.67.4:9876"}
    th_a  server.cpp:256 connect_to         application.cpp:64
3149325ms       th_a         connect_loop ] 162.243.67.4:9876           application.cpp:59
3149325ms       th_a           connect_to ] connect to 162.243.67.4:9876            server.cpp:243
3149564ms       th_a         connect_loop ] unspecified
Broken pipe 
    {"message":"Broken pipe"}
    asio  asio.cpp:28 read_write_handler
error connecting to 162.243.67.4:9876
    {"ep":"162.243.67.4:9876"}
    th_a  connection.cpp:194 connect
unable to connect to 162.243.67.4:9876
    {"ep":"162.243.67.4:9876"}
    th_a  server.cpp:256 connect_to         application.cpp:64
3152564ms       th_a         connect_loop ] 162.243.67.4:9876           application.cpp:59
3152565ms       th_a           connect_to ] connect to 162.243.67.4:9876            server.cpp:243
3152808ms       th_a         connect_loop ] unspecified
Broken pipe 
    {"message":"Broken pipe"}
    asio  asio.cpp:28 read_write_handler
error connecting to 162.243.67.4:9876
    {"ep":"162.243.67.4:9876"}
    th_a  connection.cpp:194 connect
unable to connect to 162.243.67.4:9876
    {"ep":"162.243.67.4:9876"}
    th_a  server.cpp:256 connect_to         application.cpp:64
3155808ms       th_a         connect_loop ] 162.243.67.4:9876           application.cpp:59
3155808ms       th_a           connect_to ] connect to 162.243.67.4:9876            server.cpp:243
3156055ms       th_a         connect_loop ] unspecified
Broken pipe 
    {"message":"Broken pipe"}
    asio  asio.cpp:28 read_write_handler
error connecting to 162.243.67.4:9876
    {"ep":"162.243.67.4:9876"}
    th_a  connection.cpp:194 connect
unable to connect to 162.243.67.4:9876
    {"ep":"162.243.67.4:9876"}
    th_a  server.cpp:256 connect_to         application.cpp:64
3159056ms       th_a         connect_loop ] 162.243.67.4:9876           application.cpp:59
3159056ms       th_a           connect_to ] connect to 162.243.67.4:9876            server.cpp:243
3159289ms       th_a         connect_loop ] unspecified
Broken pipe 
    {"message":"Broken pipe"}
    asio  asio.cpp:28 read_write_handler
error connecting to 162.243.67.4:9876
    {"ep":"162.243.67.4:9876"}
    th_a  connection.cpp:194 connect
unable to connect to 162.243.67.4:9876
    {"ep":"162.243.67.4:9876"}
    th_a  server.cpp:256 connect_to         application.cpp:64
3162290ms       th_a         connect_loop ] 162.243.67.4:9876           application.cpp:59
3162290ms       th_a           connect_to ] connect to 162.243.67.4:9876            server.cpp:243
3162577ms       th_a         connect_loop ] unspecified
Broken pipe 
    {"message":"Broken pipe"}
    asio  asio.cpp:28 read_write_handler
error connecting to 162.243.67.4:9876
    {"ep":"162.243.67.4:9876"}
    th_a  connection.cpp:194 connect
unable to connect to 162.243.67.4:9876
    {"ep":"162.243.67.4:9876"}
    th_a  server.cpp:256 connect_to         application.cpp:64
3165577ms       th_a         connect_loop ] 162.243.67.4:9876           application.cpp:59
3165578ms       th_a           connect_to ] connect to 162.243.67.4:9876            server.cpp:243
3165829ms       th_a         connect_loop ] unspecified
Broken pipe 
    {"message":"Broken pipe"}
    asio  asio.cpp:28 read_write_handler
error connecting to 162.243.67.4:9876
    {"ep":"162.243.67.4:9876"}
    th_a  connection.cpp:194 connect
unable to connect to 162.243.67.4:9876
    {"ep":"162.243.67.4:9876"}
    th_a  server.cpp:256 connect_to         application.cpp:64
3168920ms       th_a         connect_loop ] 162.243.67.4:9876           application.cpp:59
3168920ms       th_a           connect_to ] connect to 162.243.67.4:9876            server.cpp:243
3169157ms       th_a         connect_loop ] unspecified
Broken pipe 
    {"message":"Broken pipe"}
    asio  asio.cpp:28 read_write_handler
error connecting to 162.243.67.4:9876
    {"ep":"162.243.67.4:9876"}
    th_a  connection.cpp:194 connect
unable to connect to 162.243.67.4:9876
    {"ep":"162.243.67.4:9876"}
    th_a  server.cpp:256 connect_to         application.cpp:64
3172158ms       th_a         connect_loop ] 162.243.67.4:9876           application.cpp:59
3172158ms       th_a           connect_to ] connect to 162.243.67.4:9876            server.cpp:243
3172428ms       th_a         connect_loop ] unspecified
Broken pipe 
    {"message":"Broken pipe"}
    asio  asio.cpp:28 read_write_handler
error connecting to 162.243.67.4:9876
    {"ep":"162.243.67.4:9876"}
    th_a  connection.cpp:194 connect
unable to connect to 162.243.67.4:9876
    {"ep":"162.243.67.4:9876"}
    th_a  server.cpp:256 connect_to         application.cpp:64
3175428ms       th_a         connect_loop ] 162.243.67.4:9876           application.cpp:59
3175428ms       th_a           connect_to ] connect to 162.243.67.4:9876            server.cpp:243
3175660ms       th_a         connect_loop ] unspecified
Broken pipe 
    {"message":"Broken pipe"}
    asio  asio.cpp:28 read_write_handler
error connecting to 162.243.67.4:9876
    {"ep":"162.243.67.4:9876"}
    th_a  connection.cpp:194 connect
unable to connect to 162.243.67.4:9876
    {"ep":"162.243.67.4:9876"}
    th_a  server.cpp:256 connect_to         application.cpp:64
3178660ms       th_a         connect_loop ] 162.243.67.4:9876           application.cpp:59
3178661ms       th_a           connect_to ] connect to 162.243.67.4:9876            server.cpp:243
3178894ms       th_a         connect_loop ] unspecified
Broken pipe 
    {"message":"Broken pipe"}
    asio  asio.cpp:28 read_write_handler
error connecting to 162.243.67.4:9876
    {"ep":"162.243.67.4:9876"}
    th_a  connection.cpp:194 connect
unable to connect to 162.243.67.4:9876
    {"ep":"162.243.67.4:9876"}
    th_a  server.cpp:256 connect_to         application.cpp:64
3181894ms       th_a         connect_loop ] 162.243.67.4:9876           application.cpp:59
3181895ms       th_a           connect_to ] connect to 162.243.67.4:9876            server.cpp:243
3182139ms       th_a         connect_loop ] unspecified
Broken pipe 
    {"message":"Broken pipe"}
    asio  asio.cpp:28 read_write_handler
error connecting to 162.243.67.4:9876
    {"ep":"162.243.67.4:9876"}
    th_a  connection.cpp:194 connect
unable to connect to 162.243.67.4:9876
    {"ep":"162.243.67.4:9876"}
    th_a  server.cpp:256 connect_to         application.cpp:64
3185140ms       th_a         connect_loop ] 162.243.67.4:9876           application.cpp:59
3185140ms       th_a           connect_to ] connect to 162.243.67.4:9876            server.cpp:243
3188404ms       th_a         connect_loop ] unspecified
Broken pipe 
    {"message":"Broken pipe"}
    asio  asio.cpp:28 read_write_handler
error connecting to 162.243.67.4:9876
    {"ep":"162.243.67.4:9876"}
    th_a  connection.cpp:194 connect
unable to connect to 162.243.67.4:9876
    {"ep":"162.243.67.4:9876"}
    th_a  server.cpp:256 connect_to         application.cpp:64
3191404ms       th_a         connect_loop ] 162.243.67.4:9876           application.cpp:59
3191405ms       th_a           connect_to ] connect to 162.243.67.4:9876            server.cpp:243
3191655ms       th_a         connect_loop ] unspecified
Broken pipe 
    {"message":"Broken pipe"}
    asio  asio.cpp:28 read_write_handler
error connecting to 162.243.67.4:9876
    {"ep":"162.243.67.4:9876"}
    th_a  connection.cpp:194 connect
unable to connect to 162.243.67.4:9876
    {"ep":"162.243.67.4:9876"}
    th_a  server.cpp:256 connect_to         application.cpp:64
3194656ms       th_a         connect_loop ] 162.243.67.4:9876           application.cpp:59
3194656ms       th_a           connect_to ] connect to 162.243.67.4:9876            server.cpp:243
3194885ms       th_a         connect_loop ] unspecified
Broken pipe 
    {"message":"Broken pipe"}
    asio  asio.cpp:28 read_write_handler
error connecting to 162.243.67.4:9876
    {"ep":"162.243.67.4:9876"}
    th_a  connection.cpp:194 connect
unable to connect to 162.243.67.4:9876
    {"ep":"162.243.67.4:9876"}
    th_a  server.cpp:256 connect_to         application.cpp:64
3197886ms       th_a         connect_loop ] 162.243.67.4:9876           application.cpp:59
3197886ms       th_a           connect_to ] connect to 162.243.67.4:9876            server.cpp:243
3198120ms       th_a         connect_loop ] unspecified
Broken pipe 
    {"message":"Broken pipe"}
    asio  asio.cpp:28 read_write_handler
error connecting to 162.243.67.4:9876
    {"ep":"162.243.67.4:9876"}
    th_a  connection.cpp:194 connect
unable to connect to 162.243.67.4:9876
    {"ep":"162.243.67.4:9876"}
    th_a  server.cpp:256 connect_to         application.cpp:64
3201120ms       th_a         connect_loop ] 162.243.67.4:9876           application.cpp:59
3201121ms       th_a           connect_to ] connect to 162.243.67.4:9876            server.cpp:243
3201359ms       th_a         connect_loop ] unspecified
Broken pipe 
    {"message":"Broken pipe"}
    asio  asio.cpp:28 read_write_handler
error connecting to 162.243.67.4:9876
    {"ep":"162.243.67.4:9876"}
    th_a  connection.cpp:194 connect
unable to connect to 162.243.67.4:9876
    {"ep":"162.243.67.4:9876"}
    th_a  server.cpp:256 connect_to         application.cpp:64
3204360ms       th_a         connect_loop ] 162.243.67.4:9876           application.cpp:59
3204360ms       th_a           connect_to ] connect to 162.243.67.4:9876            server.cpp:243
3204613ms       th_a         connect_loop ] unspecified
Broken pipe 
    {"message":"Broken pipe"}
    asio  asio.cpp:28 read_write_handler
error connecting to 162.243.67.4:9876
    {"ep":"162.243.67.4:9876"}
    th_a  connection.cpp:194 connect
unable to connect to 162.243.67.4:9876
    {"ep":"162.243.67.4:9876"}
    th_a  server.cpp:256 connect_to         application.cpp:64

**Comment by PaulEU** [comment]
I will fix it.

**Comment by PaulEU** [comment]
Fixed at rev: https://github.com/InvictusInnovations/keyhotee/commit/0b9779a6eaf316256c0ece22bfc112df10ae4e39
