### ISSUE TITLE
Details button doesn't seem to work with a scenario of Show Contact

### ISSUE THREAD

**Issue by yuvarajgogoi** [InvictusInnovations/keyhotee#162]
1) create an identity.
2) press contact->show contact.
3) select the contact.
4) Now contact details are seen.
5) Now press Contact->New Contact
6) press inbox.
7) press contact->show contact.
8) Now contact details are seen.
9) press again press inbox.
10) Now press Contact->New Contact.
11) Now again press contact->show contact.
12) select the contact. 
Thereafter no details  of any contact can be seen..... 

Tested on Ubuntu. Can be easily reproducible.

**Comment by yuvarajgogoi** [comment]
Can't add log here because of this issue:
There was an error creating your comment: Body is too long (maximum is 65535 characters)... Please contact me for Diagnostic log details

**Comment by PaulEU** [comment]
Could you send me screenshot of main window ?
pstudnicki@syncad.com

**Comment by yuvarajgogoi** [comment]
![screenshot from 2014-01-01 10 43 30](https://f.cloud.github.com/assets/5823578/1829344/9b87af8c-72a3-11e3-888a-44c6c8daae88.png)
screenshot attached here also. Also sent on your mail. :) And Happy New Year.

**Comment by PaulEU** [comment]
Fixed at rev: https://github.com/InvictusInnovations/keyhotee/commit/79c628c934cd64c2b530038bda703ecfa6c9a7bb
