### ISSUE TITLE
crash on creating profile with no internet connection

### ISSUE THREAD

**Issue by yuvarajgogoi** [InvictusInnovations/keyhotee#164]
Steps to reproduce:
disable Internet.
1) create a profile.
crash is seen

tested on Ubuntu and is always reproducible

log : 
3416090ms       th_a              startup ] .           KeyhoteeApplication.cpp:263
3416090ms       th_a         get_profiles ] profiles []         application.cpp:217
3416090ms       th_a displayProfileWizard ] .           KeyhoteeApplication.cpp:186
3438673ms       th_a       create_profile ] config_file: /home/yuvi/.local/share/Keyhotee/profiles/Y G/config.json          application.cpp:258
3455542ms       th_a   displayFailureInfo ] unspecified
process exited with: Connection refused 
    {"message":"Connection refused"}
    asio  asio.cpp:83 resolve_handler

```
{"config":{"data_dir":"/home/yuvi/.local/share/Keyhotee/profiles/Y G/data","network_port":0,"rpc_config":{"port":0,"user":"","pass":""},"enable_upnp":false,"default_nodes":["162.243.67.4:9876"]}}
th_a  application.cpp:170 configure

{}
th_a  application.cpp:285 create_profile            KeyhoteeApplication.cpp:205
```

3455613ms       th_a   displayFailureInfo ] fatal error unspecified
process exited with: Connection refused 
    {"message":"Connection refused"}
    asio  asio.cpp:83 resolve_handler

```
{"config":{"data_dir":"/home/yuvi/.local/share/Keyhotee/profiles/Y G/data","network_port":0,"rpc_config":{"port":0,"user":"","pass":""},"enable_upnp":false,"default_nodes":["162.243.67.4:9876"]}}
th_a  application.cpp:170 configure

{}
th_a  application.cpp:285 create_profile            KeyhoteeApplication.cpp:207
```

**Comment by dnotestein** [comment]
Problem occurs because exception is thrown when echoip and later the server don't resolve. Planning to add appropriate exception catches around these to let keyhotee profiles get created and load properly.
