### ISSUE TITLE
deleting an identity and trying to add again on the 2nd client is not successful

### ISSUE THREAD

**Issue by yuvarajgogoi** [InvictusInnovations/keyhotee#166]
Steps to reproduce:
1) start one client
2) start another client
3) create identities in the second client.
4) delete an identity
5) now try to add New contact the same identity.
It gives this message.
This contact is already added to the list.

Tested on Ubuntu. and is always reproducible in this particular scenario

**Comment by yuvarajgogoi** [comment]
I also see some inconsistency here. In the first client though, the contact gets added, if we select the contact, we don't get the details of the added contact. It shows details of some other contact

**Comment by dnotestein** [comment]
When deleting a contact record that is also an identity, we just need to add code to remove it from the identity list as well. This probably means we also need add an API call to bitshares to allow deleting an identity record.
