### ISSUE TITLE
is able to add a particular random public key on creating new contact.

### ISSUE THREAD

**Issue by yuvarajgogoi** [InvictusInnovations/keyhotee#168]
Steps tp reproduce
1) start a fresh new client.
2) add this to public key 

5UEj4vMGAvSGtrKnU64zBfn235JEKmhgcyhktchkfhffhffvvh

3) Now I am able to add this key.
 try sending a mail to this contact.
crash is seen

Tested on Ubuntu and is always reproducible.

log:

2925569ms       th_a              startup ] .           KeyhoteeApplication.cpp:263
2925570ms       th_a         get_profiles ] profiles []         application.cpp:217
2925570ms       th_a displayProfileWizard ] .           KeyhoteeApplication.cpp:186
2958065ms       th_a       create_profile ] config_file: /home/yuvi/.local/share/Keyhotee/profiles/Y G/config.json          application.cpp:258
2977047ms       th_a            configure ] external IP 106.51.193.63           application.cpp:139
2977048ms       th_a            configure ] listening for stcp connections on port 0            server.cpp:206
2978337ms       th_a         load_indexes ] load indexes            bitname_db.cpp:92
2978337ms       th_a         load_indexes ] load indexes            bitname_db.cpp:107
2978340ms       th_a      init_timekeeper ] ...init stats...            bitname_db.cpp:162
2978340ms       th_a      init_timekeeper ] ...done init timekeeper...          bitname_db.cpp:164
2978340ms       th_a                 open ] open name db            bitname_db.cpp:214
2982117ms       th_a            configure ] listening for rpc connections on port 0         rpc_server.cpp:245
2982118ms       th_a            configure ] listening for rpc connections on port 37366         rpc_server.cpp:247
2983020ms       th_a   KeyhoteeMainWindow ] idents: []          KeyhoteeMainWindow.cpp:249
2983165ms       th_a         connect_loop ] 162.243.67.4:9876           application.cpp:59
2983165ms       th_a           connect_to ] connect to 162.243.67.4:9876            server.cpp:243
2983473ms       th_a         connect_loop ] unspecified
Broken pipe 
    {"message":"Broken pipe"}
    asio  asio.cpp:28 read_write_handler
error connecting to 162.243.67.4:9876
    {"ep":"162.243.67.4:9876"}
    th_a  connection.cpp:194 connect
unable to connect to 162.243.67.4:9876
    {"ep":"162.243.67.4:9876"}
    th_a  server.cpp:256 connect_to         application.cpp:64
2986473ms       th_a         connect_loop ] 162.243.67.4:9876           application.cpp:59
2986474ms       th_a           connect_to ] connect to 162.243.67.4:9876            server.cpp:243
2986700ms       th_a         connect_loop ] unspecified
Broken pipe 
    {"message":"Broken pipe"}
    asio  asio.cpp:28 read_write_handler
error connecting to 162.243.67.4:9876
    {"ep":"162.243.67.4:9876"}
    th_a  connection.cpp:194 connect
unable to connect to 162.243.67.4:9876
    {"ep":"162.243.67.4:9876"}
    th_a  server.cpp:256 connect_to         application.cpp:64
2989700ms       th_a         connect_loop ] 162.243.67.4:9876           application.cpp:59
2989701ms       th_a           connect_to ] connect to 162.243.67.4:9876            server.cpp:243
2989909ms       th_a         connect_loop ] unspecified
Broken pipe 
    {"message":"Broken pipe"}
    asio  asio.cpp:28 read_write_handler
error connecting to 162.243.67.4:9876
    {"ep":"162.243.67.4:9876"}
    th_a  connection.cpp:194 connect
unable to connect to 162.243.67.4:9876
    {"ep":"162.243.67.4:9876"}
    th_a  server.cpp:256 connect_to         application.cpp:64
2992910ms       th_a         connect_loop ] 162.243.67.4:9876           application.cpp:59
2992910ms       th_a           connect_to ] connect to 162.243.67.4:9876            server.cpp:243
2993155ms       th_a         connect_loop ] unspecified
Broken pipe 
    {"message":"Broken pipe"}
    asio  asio.cpp:28 read_write_handler
error connecting to 162.243.67.4:9876
    {"ep":"162.243.67.4:9876"}
    th_a  connection.cpp:194 connect
unable to connect to 162.243.67.4:9876
    {"ep":"162.243.67.4:9876"}
    th_a  server.cpp:256 connect_to         application.cpp:64
2996163ms       th_a         connect_loop ] 162.243.67.4:9876           application.cpp:59
2996163ms       th_a           connect_to ] connect to 162.243.67.4:9876            server.cpp:243
2996390ms       th_a         connect_loop ] unspecified
Broken pipe 
    {"message":"Broken pipe"}
    asio  asio.cpp:28 read_write_handler
error connecting to 162.243.67.4:9876
    {"ep":"162.243.67.4:9876"}
    th_a  connection.cpp:194 connect
unable to connect to 162.243.67.4:9876
    {"ep":"162.243.67.4:9876"}
    th_a  server.cpp:256 connect_to         application.cpp:64
2996986ms       th_a               onSave ] !current record??
            ContactView.cpp:202
2996986ms       th_a        store_contact ] to_string()         addressbook.cpp:110
2996987ms       th_a        store_contact ] ... did it work?            addressbook.cpp:112
2999391ms       th_a         connect_loop ] 162.243.67.4:9876           application.cpp:59
2999391ms       th_a           connect_to ] connect to 162.243.67.4:9876            server.cpp:243
2999602ms       th_a         connect_loop ] unspecified
Broken pipe 
    {"message":"Broken pipe"}
    asio  asio.cpp:28 read_write_handler
error connecting to 162.243.67.4:9876
    {"ep":"162.243.67.4:9876"}
    th_a  connection.cpp:194 connect
unable to connect to 162.243.67.4:9876
    {"ep":"162.243.67.4:9876"}
    th_a  server.cpp:256 connect_to         application.cpp:64
3006326ms       th_a         connect_loop ] 162.243.67.4:9876           application.cpp:59
3006326ms       th_a           connect_to ] connect to 162.243.67.4:9876            server.cpp:243
3006552ms       th_a         connect_loop ] unspecified
Broken pipe 
    {"message":"Broken pipe"}
    asio  asio.cpp:28 read_write_handler
error connecting to 162.243.67.4:9876
    {"ep":"162.243.67.4:9876"}
    th_a  connection.cpp:194 connect
unable to connect to 162.243.67.4:9876
    {"ep":"162.243.67.4:9876"}
    th_a  server.cpp:256 connect_to         application.cpp:64
3007910ms       th_a   displayFailureInfo ] assert
other.my->_key != nullptr: 
    {}
    th_a  elliptic.cpp:439 get_shared_secret            KeyhoteeApplication.cpp:205
3007910ms       th_a   displayFailureInfo ] fatal error assert
other.my->_key != nullptr: 
    {}
    th_a  elliptic.cpp:439 get_shared_secret            KeyhoteeApplication.cpp:207

**Comment by dnotestein** [comment]
I think this may be fixed, I can't duplicate it anymore, and it seems the public key automatically gets saved to a valid one now. Yuvaraj, can you confirm if you're still able to duplicate this?

**Comment by yuvarajgogoi** [comment]
I see now if I put a new random key. If it shows valid and then we save it into contact, it saves as the most similar public key that is already present.

**Comment by dnotestein** [comment]
Probably we should show such keys as "invalid" keys when entered (maybe turn the text color red in the public key edit box).
