### ISSUE TITLE
crash on saving after editing contact

### ISSUE THREAD

**Issue by yuvarajgogoi** [InvictusInnovations/keyhotee#171]
Steps to reproduce:
1) start a client,
2) create 2 identities.
3) delete the first identity.
4) edit the second identity(write some text on the first name or last name or put an icon)
5) save it 

crash is seen.

Tested on Ubuntu and is always reproducible.

log:

1217262ms       th_a              startup ] .           KeyhoteeApplication.cpp:263
1217263ms       th_a         get_profiles ] profiles []         application.cpp:217
1217263ms       th_a displayProfileWizard ] .           KeyhoteeApplication.cpp:186
1238172ms       th_a       create_profile ] config_file: /home/yuvi/.local/share/Keyhotee/profiles/Y G/config.json          application.cpp:258
1252643ms       th_a            configure ] external IP 106.51.182.164          application.cpp:139
1252644ms       th_a            configure ] listening for stcp connections on port 0            server.cpp:206
1254065ms       th_a         load_indexes ] load indexes            bitname_db.cpp:92
1254066ms       th_a         load_indexes ] load indexes            bitname_db.cpp:107
1254067ms       th_a      init_timekeeper ] ...init stats...            bitname_db.cpp:162
1254067ms       th_a      init_timekeeper ] ...done init timekeeper...          bitname_db.cpp:164
1254067ms       th_a                 open ] open name db            bitname_db.cpp:214
1258042ms       th_a            configure ] listening for rpc connections on port 0         rpc_server.cpp:245
1258042ms       th_a            configure ] listening for rpc connections on port 58036         rpc_server.cpp:247
1258391ms       th_a   KeyhoteeMainWindow ] idents: []          KeyhoteeMainWindow.cpp:250
1258452ms       th_a         connect_loop ] 162.243.67.4:9876           application.cpp:59
1258452ms       th_a           connect_to ] connect to 162.243.67.4:9876            server.cpp:243
1258687ms       th_a         connect_loop ] unspecified
Broken pipe 
    {"message":"Broken pipe"}
    asio  asio.cpp:28 read_write_handler
error connecting to 162.243.67.4:9876
    {"ep":"162.243.67.4:9876"}
    th_a  connection.cpp:194 connect
unable to connect to 162.243.67.4:9876
    {"ep":"162.243.67.4:9876"}
    th_a  server.cpp:256 connect_to         application.cpp:64
1261688ms       th_a         connect_loop ] 162.243.67.4:9876           application.cpp:59
1261688ms       th_a           connect_to ] connect to 162.243.67.4:9876            server.cpp:243
1261928ms       th_a         connect_loop ] unspecified
Broken pipe 
    {"message":"Broken pipe"}
    asio  asio.cpp:28 read_write_handler
error connecting to 162.243.67.4:9876
    {"ep":"162.243.67.4:9876"}
    th_a  connection.cpp:194 connect
unable to connect to 162.243.67.4:9876
    {"ep":"162.243.67.4:9876"}
    th_a  server.cpp:256 connect_to         application.cpp:64
1264928ms       th_a         connect_loop ] 162.243.67.4:9876           application.cpp:59
1264928ms       th_a           connect_to ] connect to 162.243.67.4:9876            server.cpp:243
1265152ms       th_a         connect_loop ] unspecified
Broken pipe 
    {"message":"Broken pipe"}
    asio  asio.cpp:28 read_write_handler
error connecting to 162.243.67.4:9876
    {"ep":"162.243.67.4:9876"}
    th_a  connection.cpp:194 connect
unable to connect to 162.243.67.4:9876
    {"ep":"162.243.67.4:9876"}
    th_a  server.cpp:256 connect_to         application.cpp:64
1265926ms       th_a        store_contact ] to_string()         addressbook.cpp:110
1265927ms       th_a        store_contact ] ... did it work?            addressbook.cpp:112
1268153ms       th_a         connect_loop ] 162.243.67.4:9876           application.cpp:59
1268154ms       th_a           connect_to ] connect to 162.243.67.4:9876            server.cpp:243
1268381ms       th_a         connect_loop ] unspecified
Broken pipe 
    {"message":"Broken pipe"}
    asio  asio.cpp:28 read_write_handler
error connecting to 162.243.67.4:9876
    {"ep":"162.243.67.4:9876"}
    th_a  connection.cpp:194 connect
unable to connect to 162.243.67.4:9876
    {"ep":"162.243.67.4:9876"}
    th_a  server.cpp:256 connect_to         application.cpp:64
1270523ms       th_a        store_contact ] to_string()         addressbook.cpp:110
1270523ms       th_a        store_contact ] ... did it work?            addressbook.cpp:112
1271382ms       th_a         connect_loop ] 162.243.67.4:9876           application.cpp:59
1271382ms       th_a           connect_to ] connect to 162.243.67.4:9876            server.cpp:243
1271621ms       th_a         connect_loop ] unspecified
Broken pipe 
    {"message":"Broken pipe"}
    asio  asio.cpp:28 read_write_handler
error connecting to 162.243.67.4:9876
    {"ep":"162.243.67.4:9876"}
    th_a  connection.cpp:194 connect
unable to connect to 162.243.67.4:9876
    {"ep":"162.243.67.4:9876"}
    th_a  server.cpp:256 connect_to         application.cpp:64
1274621ms       th_a         connect_loop ] 162.243.67.4:9876           application.cpp:59
1274621ms       th_a           connect_to ] connect to 162.243.67.4:9876            server.cpp:243
1274854ms       th_a         connect_loop ] unspecified
Broken pipe 
    {"message":"Broken pipe"}
    asio  asio.cpp:28 read_write_handler
error connecting to 162.243.67.4:9876
    {"ep":"162.243.67.4:9876"}
    th_a  connection.cpp:194 connect
unable to connect to 162.243.67.4:9876
    {"ep":"162.243.67.4:9876"}
    th_a  server.cpp:256 connect_to         application.cpp:64
1277931ms       th_a         connect_loop ] 162.243.67.4:9876           application.cpp:59
1277931ms       th_a           connect_to ] connect to 162.243.67.4:9876            server.cpp:243
1278157ms       th_a         connect_loop ] unspecified
Broken pipe 
    {"message":"Broken pipe"}
    asio  asio.cpp:28 read_write_handler
error connecting to 162.243.67.4:9876
    {"ep":"162.243.67.4:9876"}
    th_a  connection.cpp:194 connect
unable to connect to 162.243.67.4:9876
    {"ep":"162.243.67.4:9876"}
    th_a  server.cpp:256 connect_to         application.cpp:64
1281160ms       th_a         connect_loop ] 162.243.67.4:9876           application.cpp:59
1281160ms       th_a           connect_to ] connect to 162.243.67.4:9876            server.cpp:243
1281386ms       th_a         connect_loop ] unspecified
Broken pipe 
    {"message":"Broken pipe"}
    asio  asio.cpp:28 read_write_handler
error connecting to 162.243.67.4:9876
    {"ep":"162.243.67.4:9876"}
    th_a  connection.cpp:194 connect
unable to connect to 162.243.67.4:9876
    {"ep":"162.243.67.4:9876"}
    th_a  server.cpp:256 connect_to         application.cpp:64
1284387ms       th_a         connect_loop ] 162.243.67.4:9876           application.cpp:59
1284387ms       th_a           connect_to ] connect to 162.243.67.4:9876            server.cpp:243
1284624ms       th_a         connect_loop ] unspecified
Broken pipe 
    {"message":"Broken pipe"}
    asio  asio.cpp:28 read_write_handler
error connecting to 162.243.67.4:9876
    {"ep":"162.243.67.4:9876"}
    th_a  connection.cpp:194 connect
unable to connect to 162.243.67.4:9876
    {"ep":"162.243.67.4:9876"}
    th_a  server.cpp:256 connect_to         application.cpp:64
1287624ms       th_a         connect_loop ] 162.243.67.4:9876           application.cpp:59
1287624ms       th_a           connect_to ] connect to 162.243.67.4:9876            server.cpp:243
1287867ms       th_a         connect_loop ] unspecified
Broken pipe 
    {"message":"Broken pipe"}
    asio  asio.cpp:28 read_write_handler
error connecting to 162.243.67.4:9876
    {"ep":"162.243.67.4:9876"}
    th_a  connection.cpp:194 connect
unable to connect to 162.243.67.4:9876
    {"ep":"162.243.67.4:9876"}
    th_a  server.cpp:256 connect_to         application.cpp:64
1290867ms       th_a         connect_loop ] 162.243.67.4:9876           application.cpp:59
1290868ms       th_a           connect_to ] connect to 162.243.67.4:9876            server.cpp:243
1291103ms       th_a         connect_loop ] unspecified
Broken pipe 
    {"message":"Broken pipe"}
    asio  asio.cpp:28 read_write_handler
error connecting to 162.243.67.4:9876
    {"ep":"162.243.67.4:9876"}
    th_a  connection.cpp:194 connect
unable to connect to 162.243.67.4:9876
    {"ep":"162.243.67.4:9876"}
    th_a  server.cpp:256 connect_to         application.cpp:64
1294104ms       th_a         connect_loop ] 162.243.67.4:9876           application.cpp:59
1294104ms       th_a           connect_to ] connect to 162.243.67.4:9876            server.cpp:243
1294345ms       th_a         connect_loop ] unspecified
Broken pipe 
    {"message":"Broken pipe"}
    asio  asio.cpp:28 read_write_handler
error connecting to 162.243.67.4:9876
    {"ep":"162.243.67.4:9876"}
    th_a  connection.cpp:194 connect
unable to connect to 162.243.67.4:9876
    {"ep":"162.243.67.4:9876"}
    th_a  server.cpp:256 connect_to         application.cpp:64
1297346ms       th_a         connect_loop ] 162.243.67.4:9876           application.cpp:59
1297346ms       th_a           connect_to ] connect to 162.243.67.4:9876            server.cpp:243
1297588ms       th_a         connect_loop ] unspecified
Broken pipe 
    {"message":"Broken pipe"}
    asio  asio.cpp:28 read_write_handler
error connecting to 162.243.67.4:9876
    {"ep":"162.243.67.4:9876"}
    th_a  connection.cpp:194 connect
unable to connect to 162.243.67.4:9876
    {"ep":"162.243.67.4:9876"}
    th_a  server.cpp:256 connect_to         application.cpp:64
1300588ms       th_a         connect_loop ] 162.243.67.4:9876           application.cpp:59
1300589ms       th_a           connect_to ] connect to 162.243.67.4:9876            server.cpp:243
1300816ms       th_a         connect_loop ] unspecified
Broken pipe 
    {"message":"Broken pipe"}
    asio  asio.cpp:28 read_write_handler
error connecting to 162.243.67.4:9876
    {"ep":"162.243.67.4:9876"}
    th_a  connection.cpp:194 connect
unable to connect to 162.243.67.4:9876
    {"ep":"162.243.67.4:9876"}
    th_a  server.cpp:256 connect_to         application.cpp:64
1303816ms       th_a         connect_loop ] 162.243.67.4:9876           application.cpp:59
1303817ms       th_a           connect_to ] connect to 162.243.67.4:9876            server.cpp:243
1304057ms       th_a         connect_loop ] unspecified
Broken pipe 
    {"message":"Broken pipe"}
    asio  asio.cpp:28 read_write_handler
error connecting to 162.243.67.4:9876
    {"ep":"162.243.67.4:9876"}
    th_a  connection.cpp:194 connect
unable to connect to 162.243.67.4:9876
    {"ep":"162.243.67.4:9876"}
    th_a  server.cpp:256 connect_to         application.cpp:64
1307057ms       th_a         connect_loop ] 162.243.67.4:9876           application.cpp:59
1307057ms       th_a           connect_to ] connect to 162.243.67.4:9876            server.cpp:243
1307292ms       th_a         connect_loop ] unspecified
Broken pipe 
    {"message":"Broken pipe"}
    asio  asio.cpp:28 read_write_handler
error connecting to 162.243.67.4:9876
    {"ep":"162.243.67.4:9876"}
    th_a  connection.cpp:194 connect
unable to connect to 162.243.67.4:9876
    {"ep":"162.243.67.4:9876"}
    th_a  server.cpp:256 connect_to         application.cpp:64
1310292ms       th_a         connect_loop ] 162.243.67.4:9876           application.cpp:59
1310293ms       th_a           connect_to ] connect to 162.243.67.4:9876            server.cpp:243
1310521ms       th_a         connect_loop ] unspecified
Broken pipe 
    {"message":"Broken pipe"}
    asio  asio.cpp:28 read_write_handler
error connecting to 162.243.67.4:9876
    {"ep":"162.243.67.4:9876"}
    th_a  connection.cpp:194 connect
unable to connect to 162.243.67.4:9876
    {"ep":"162.243.67.4:9876"}
    th_a  server.cpp:256 connect_to         application.cpp:64
1313522ms       th_a         connect_loop ] 162.243.67.4:9876           application.cpp:59
1313522ms       th_a           connect_to ] connect to 162.243.67.4:9876            server.cpp:243
1313750ms       th_a         connect_loop ] unspecified
Broken pipe 
    {"message":"Broken pipe"}
    asio  asio.cpp:28 read_write_handler
error connecting to 162.243.67.4:9876
    {"ep":"162.243.67.4:9876"}
    th_a  connection.cpp:194 connect
unable to connect to 162.243.67.4:9876
    {"ep":"162.243.67.4:9876"}
    th_a  server.cpp:256 connect_to         application.cpp:64
1316751ms       th_a         connect_loop ] 162.243.67.4:9876           application.cpp:59
1316751ms       th_a           connect_to ] connect to 162.243.67.4:9876            server.cpp:243
1316978ms       th_a         connect_loop ] unspecified
Broken pipe 
    {"message":"Broken pipe"}
    asio  asio.cpp:28 read_write_handler
error connecting to 162.243.67.4:9876
    {"ep":"162.243.67.4:9876"}
    th_a  connection.cpp:194 connect
unable to connect to 162.243.67.4:9876
    {"ep":"162.243.67.4:9876"}
    th_a  server.cpp:256 connect_to         application.cpp:64
1319978ms       th_a         connect_loop ] 162.243.67.4:9876           application.cpp:59
1319979ms       th_a           connect_to ] connect to 162.243.67.4:9876            server.cpp:243
1320222ms       th_a         connect_loop ] unspecified
Broken pipe 
    {"message":"Broken pipe"}
    asio  asio.cpp:28 read_write_handler
error connecting to 162.243.67.4:9876
    {"ep":"162.243.67.4:9876"}
    th_a  connection.cpp:194 connect
unable to connect to 162.243.67.4:9876
    {"ep":"162.243.67.4:9876"}
    th_a  server.cpp:256 connect_to         application.cpp:64
1323223ms       th_a         connect_loop ] 162.243.67.4:9876           application.cpp:59
1323223ms       th_a           connect_to ] connect to 162.243.67.4:9876            server.cpp:243
1323463ms       th_a         connect_loop ] unspecified
Broken pipe 
    {"message":"Broken pipe"}
    asio  asio.cpp:28 read_write_handler
error connecting to 162.243.67.4:9876
    {"ep":"162.243.67.4:9876"}
    th_a  connection.cpp:194 connect
unable to connect to 162.243.67.4:9876
    {"ep":"162.243.67.4:9876"}
    th_a  server.cpp:256 connect_to         application.cpp:64
1326463ms       th_a         connect_loop ] 162.243.67.4:9876           application.cpp:59
1326464ms       th_a           connect_to ] connect to 162.243.67.4:9876            server.cpp:243
1326694ms       th_a         connect_loop ] unspecified
Broken pipe 
    {"message":"Broken pipe"}
    asio  asio.cpp:28 read_write_handler
error connecting to 162.243.67.4:9876
    {"ep":"162.243.67.4:9876"}
    th_a  connection.cpp:194 connect
unable to connect to 162.243.67.4:9876
    {"ep":"162.243.67.4:9876"}
    th_a  server.cpp:256 connect_to         application.cpp:64
1329698ms       th_a         connect_loop ] 162.243.67.4:9876           application.cpp:59
1329699ms       th_a           connect_to ] connect to 162.243.67.4:9876            server.cpp:243
1329939ms       th_a         connect_loop ] unspecified
Broken pipe 
    {"message":"Broken pipe"}
    asio  asio.cpp:28 read_write_handler
error connecting to 162.243.67.4:9876
    {"ep":"162.243.67.4:9876"}
    th_a  connection.cpp:194 connect
unable to connect to 162.243.67.4:9876
    {"ep":"162.243.67.4:9876"}
    th_a  server.cpp:256 connect_to         application.cpp:64
1332939ms       th_a         connect_loop ] 162.243.67.4:9876           application.cpp:59
1332940ms       th_a           connect_to ] connect to 162.243.67.4:9876            server.cpp:243
1333181ms       th_a         connect_loop ] unspecified
Broken pipe 
    {"message":"Broken pipe"}
    asio  asio.cpp:28 read_write_handler
error connecting to 162.243.67.4:9876
    {"ep":"162.243.67.4:9876"}
    th_a  connection.cpp:194 connect
unable to connect to 162.243.67.4:9876
    {"ep":"162.243.67.4:9876"}
    th_a  server.cpp:256 connect_to         application.cpp:64
1336181ms       th_a         connect_loop ] 162.243.67.4:9876           application.cpp:59
1336182ms       th_a           connect_to ] connect to 162.243.67.4:9876            server.cpp:243
1336424ms       th_a         connect_loop ] unspecified
Broken pipe 
    {"message":"Broken pipe"}
    asio  asio.cpp:28 read_write_handler
error connecting to 162.243.67.4:9876
    {"ep":"162.243.67.4:9876"}
    th_a  connection.cpp:194 connect
unable to connect to 162.243.67.4:9876
    {"ep":"162.243.67.4:9876"}
    th_a  server.cpp:256 connect_to         application.cpp:64
1339424ms       th_a         connect_loop ] 162.243.67.4:9876           application.cpp:59
1339425ms       th_a           connect_to ] connect to 162.243.67.4:9876            server.cpp:243
1339664ms       th_a         connect_loop ] unspecified
Broken pipe 
    {"message":"Broken pipe"}
    asio  asio.cpp:28 read_write_handler
error connecting to 162.243.67.4:9876
    {"ep":"162.243.67.4:9876"}
    th_a  connection.cpp:194 connect
unable to connect to 162.243.67.4:9876
    {"ep":"162.243.67.4:9876"}
    th_a  server.cpp:256 connect_to         application.cpp:64
1340086ms       th_a               onSave ] !current record??
            ContactView.cpp:202
1340087ms       th_a   displayFailureInfo ] assert
contact_to_store.wallet_index < int(my->_contacts.size()): 
    {}
    th_a  AddressBookModel.cpp:285 storeContact
onSave
    {}
    th_a  ContactView.cpp:224 onSave            KeyhoteeApplication.cpp:205
1340087ms       th_a   displayFailureInfo ] fatal error assert
contact_to_store.wallet_index < int(my->_contacts.size()): 
    {}
    th_a  AddressBookModel.cpp:285 storeContact
onSave
    {}
    th_a  ContactView.cpp:224 onSave            KeyhoteeApplication.cpp:207

**Comment by grzegorzs** [comment]
In described situation wallet_index when saving contact, is equals contacts size.

> AddressBookModel.cpp: 285
> FC_ASSERT(contact_to_store.wallet_index < int(my->_contacts.size()) );

Similar problem in issue #51

**Comment by pch957** [comment]
I don't know what is wallet_index mean.
If I have 2 contact: Tom(wallet_index is 0), Jerry(wallet_index is 1)
when I delete Tom, Jerry's wallet_index still is 1,
then I add a new contact name Jack, what's the wallet_index? from the code it's still 1?

  if (contact_to_store.wallet_index == WALLET_INVALID_INDEX)
  {
    auto num_contacts = my->_contacts.size();
    beginInsertRows(QModelIndex(), num_contacts, num_contacts);
    my->_contacts.push_back(contact_to_store);
    my->_contacts.back().wallet_index = my->_contacts.size() - 1;
    endInsertRows();
