### ISSUE TITLE
row selected doesn't highlight on delete of a row 

### ISSUE THREAD

**Issue by yuvarajgogoi** [InvictusInnovations/keyhotee#172]
Steps to reproduce:
1) create 4-5 identities.
2) delete the 3rd one from contacts.
3) now try selecting the 3rd one in contacts.
4) 3rd row doesn't highlight, though it is selected.

Tested on Ubuntu and is always reproducible.

**Comment by vogel76** [comment]
Same applies to mailbox list. Anyway always after deleting a row, next/prev row should be selected. Otherwise application usage is inconvienient.

**Comment by yuvarajgogoi** [comment]
For this issue, details are seen in the details form, only highlight doesn't seem to work. For mailbox folders, this kind of issue is not seen. This scenario is different from Issue #179.

**Comment by vogel76** [comment]
Right, it looks problem is different than I expected. It looks like there is some inconsistency between highlighted row and selected one (ie by keys).
