### ISSUE TITLE
Cannot Ctrl+C Public Key (operation not supported error)

### ISSUE THREAD

**Issue by bytemaster** [InvictusInnovations/keyhotee#173]
Why have we overridden the default system behavior?  If you remove the menu items then it works properly.

**Comment by vogel76** [comment]
I've tried and it works correctly (when public key editbox in contact view is focused). When it didn't work ? Option was introduced to have common command for all contexts. Please provide more info to duplicate the problem and reassign it to me.

**Comment by dnotestein** [comment]
I'm closing this issue as it duplicates a more recently filed issue that has a little more detail. It appears this issue is OSX-specific.
