### ISSUE TITLE
FirstName <> when no Keyhotee ID name given should be FirstName <HASH>

### ISSUE THREAD

**Issue by bytemaster** [InvictusInnovations/keyhotee#174]

**Comment by dnotestein** [comment]
Are you sure you want to show hash in this case? It's probably relatively meaningless to user and it will take up a lot of screen real-estate in the address lists.

**Comment by bytemaster** [comment]
Just include the first 8 characters.  Uniquely identify user.

**Comment by dnotestein** [comment]
Ok, but I figured they would set the first/last name that they are specifying as an alias to do that.

**Comment by vogel76** [comment]
As I understand the system (maybe wrong - please correct me) there is possible to create contact without set kID by providing its public key. If so, better display such p.key inside <> OR provide backend functionality to identify kID by given p.key (if I good rememeber bts iface provides such functionality but it is not implemented yet). Anyway any contact defined by p.key could be possible to display in readable form Fn Ln <kId> when system will allow such public key => kId conversion.

**Comment by dnotestein** [comment]
Yep, let's just maybe just display the first 6 chars of the public key in this case. We also need to be sure we're handling the case where the contact has been deleted and only the public key is still around.
