### ISSUE TITLE
Crash When Sending Mail

### ISSUE THREAD

**Issue by bytemaster** [InvictusInnovations/keyhotee#175]
1360645ms       th_a   displayFailureInfo ] assert
other.my->_key != nullptr: 
    {}
    th_a  elliptic.cpp:439 get_shared_secret            KeyhoteeApplication.cpp:205
1360645ms       th_a   displayFailureInfo ] fatal error assert
other.my->_key != nullptr: 
    {}
    th_a  elliptic.cpp:439 get_shared_secret            KeyhoteeApplication.cpp:207

**Comment by vogel76** [comment]
Fixed at rev: https://github.com/InvictusInnovations/keyhotee/commit/932d7fe17d568e7c718e7f079d7e25b901782014
