### ISSUE TITLE
crash seen on creating a new profile with the same first name and last name

### ISSUE THREAD

**Issue by yuvarajgogoi** [InvictusInnovations/keyhotee#177]
Steps to reproduce

1) create a profile
2) create 1 or 2 identities and close it
3) create another profile with the same first name and last name of step 1.
4) go to contacts. 
5) click on the contacts.
6) crash is seen with no diagnostic log .

Tested on Ubuntu and is always reproducible

**Comment by yuvarajgogoi** [comment]
log copied from console:

1956904ms th_a       server.cpp:243                connect_to           ] connect to 162.243.67.4:9876
1957294ms th_a       application.cpp:64            connect_loop         ] unspecified
Broken pipe 
    {"message":"Broken pipe"}
    asio  asio.cpp:28 read_write_handler
error connecting to 162.243.67.4:9876
    {"ep":"162.243.67.4:9876"}
    th_a  connection.cpp:194 connect
unable to connect to 162.243.67.4:9876
    {"ep":"162.243.67.4:9876"}
    th_a  server.cpp:256 connect_to
1960294ms th_a       application.cpp:59            connect_loop         ] 162.243.67.4:9876
1960295ms th_a       server.cpp:243                connect_to           ] connect to 162.243.67.4:9876
1960602ms th_a       application.cpp:64            connect_loop         ] unspecified
Broken pipe 
    {"message":"Broken pipe"}
    asio  asio.cpp:28 read_write_handler
error connecting to 162.243.67.4:9876
    {"ep":"162.243.67.4:9876"}
    th_a  connection.cpp:194 connect
unable to connect to 162.243.67.4:9876
    {"ep":"162.243.67.4:9876"}
    th_a  server.cpp:256 connect_to
1963602ms th_a       application.cpp:59            connect_loop         ] 162.243.67.4:9876
1963603ms th_a       server.cpp:243                connect_to           ] connect to 162.243.67.4:9876
1963902ms th_a       application.cpp:64            connect_loop         ] unspecified
Broken pipe 
    {"message":"Broken pipe"}
    asio  asio.cpp:28 read_write_handler
error connecting to 162.243.67.4:9876
    {"ep":"162.243.67.4:9876"}
    th_a  connection.cpp:194 connect
unable to connect to 162.243.67.4:9876
    {"ep":"162.243.67.4:9876"}
    th_a  server.cpp:256 connect_to
1966903ms th_a       application.cpp:59            connect_loop         ] 162.243.67.4:9876
1966903ms th_a       server.cpp:243                connect_to           ] connect to 162.243.67.4:9876
1967226ms th_a       application.cpp:64            connect_loop         ] unspecified
Broken pipe 
    {"message":"Broken pipe"}
    asio  asio.cpp:28 read_write_handler
error connecting to 162.243.67.4:9876
    {"ep":"162.243.67.4:9876"}
    th_a  connection.cpp:194 connect
unable to connect to 162.243.67.4:9876
    {"ep":"162.243.67.4:9876"}
    th_a  server.cpp:256 connect_to
1970227ms th_a       application.cpp:59            connect_loop         ] 162.243.67.4:9876
1970227ms th_a       server.cpp:243                connect_to           ] connect to 162.243.67.4:9876
1970614ms th_a       application.cpp:64            connect_loop         ] unspecified
Broken pipe 
    {"message":"Broken pipe"}
    asio  asio.cpp:28 read_write_handler
error connecting to 162.243.67.4:9876
    {"ep":"162.243.67.4:9876"}
    th_a  connection.cpp:194 connect
unable to connect to 162.243.67.4:9876
    {"ep":"162.243.67.4:9876"}
    th_a  server.cpp:256 connect_to
1973614ms th_a       application.cpp:59            connect_loop         ] 162.243.67.4:9876
1973614ms th_a       server.cpp:243                connect_to           ] connect to 162.243.67.4:9876
1973993ms th_a       application.cpp:64            connect_loop         ] unspecified
Broken pipe 
    {"message":"Broken pipe"}
    asio  asio.cpp:28 read_write_handler
error connecting to 162.243.67.4:9876
    {"ep":"162.243.67.4:9876"}
    th_a  connection.cpp:194 connect
unable to connect to 162.243.67.4:9876
    {"ep":"162.243.67.4:9876"}
    th_a  server.cpp:256 connect_to
1976993ms th_a       application.cpp:59            connect_loop         ] 162.243.67.4:9876
1976994ms th_a       server.cpp:243                connect_to           ] connect to 162.243.67.4:9876
1977364ms th_a       application.cpp:64            connect_loop         ] unspecified
Broken pipe 
    {"message":"Broken pipe"}
    asio  asio.cpp:28 read_write_handler
error connecting to 162.243.67.4:9876
    {"ep":"162.243.67.4:9876"}
    th_a  connection.cpp:194 connect
unable to connect to 162.243.67.4:9876
    {"ep":"162.243.67.4:9876"}
    th_a  server.cpp:256 connect_to
1980365ms th_a       application.cpp:59            connect_loop         ] 162.243.67.4:9876
1980365ms th_a       server.cpp:243                connect_to           ] connect to 162.243.67.4:9876
1980702ms th_a       application.cpp:64            connect_loop         ] unspecified
Broken pipe 
    {"message":"Broken pipe"}
    asio  asio.cpp:28 read_write_handler
error connecting to 162.243.67.4:9876
    {"ep":"162.243.67.4:9876"}
    th_a  connection.cpp:194 connect
unable to connect to 162.243.67.4:9876
    {"ep":"162.243.67.4:9876"}
    th_a  server.cpp:256 connect_to
1983702ms th_a       application.cpp:59            connect_loop         ] 162.243.67.4:9876
1983703ms th_a       server.cpp:243                connect_to           ] connect to 162.243.67.4:9876
1984028ms th_a       application.cpp:64            connect_loop         ] unspecified
Broken pipe 
    {"message":"Broken pipe"}
    asio  asio.cpp:28 read_write_handler
error connecting to 162.243.67.4:9876
    {"ep":"162.243.67.4:9876"}
    th_a  connection.cpp:194 connect
unable to connect to 162.243.67.4:9876
    {"ep":"162.243.67.4:9876"}
    th_a  server.cpp:256 connect_to
1987028ms th_a       application.cpp:59            connect_loop         ] 162.243.67.4:9876
1987028ms th_a       server.cpp:243                connect_to           ] connect to 162.243.67.4:9876
1987399ms th_a       application.cpp:64            connect_loop         ] unspecified
Broken pipe 
    {"message":"Broken pipe"}
    asio  asio.cpp:28 read_write_handler
error connecting to 162.243.67.4:9876
    {"ep":"162.243.67.4:9876"}
    th_a  connection.cpp:194 connect
unable to connect to 162.243.67.4:9876
    {"ep":"162.243.67.4:9876"}
    th_a  server.cpp:256 connect_to
1990400ms th_a       application.cpp:59            connect_loop         ] 162.243.67.4:9876
1990400ms th_a       server.cpp:243                connect_to           ] connect to 162.243.67.4:9876
1990778ms th_a       application.cpp:64            connect_loop         ] unspecified
Broken pipe 
    {"message":"Broken pipe"}
    asio  asio.cpp:28 read_write_handler
error connecting to 162.243.67.4:9876
    {"ep":"162.243.67.4:9876"}
    th_a  connection.cpp:194 connect
unable to connect to 162.243.67.4:9876
    {"ep":"162.243.67.4:9876"}
    th_a  server.cpp:256 connect_to
1993779ms th_a       application.cpp:59            connect_loop         ] 162.243.67.4:9876
1993779ms th_a       server.cpp:243                connect_to           ] connect to 162.243.67.4:9876
1994157ms th_a       application.cpp:64            connect_loop         ] unspecified
Broken pipe 
    {"message":"Broken pipe"}
    asio  asio.cpp:28 read_write_handler
error connecting to 162.243.67.4:9876
    {"ep":"162.243.67.4:9876"}
    th_a  connection.cpp:194 connect
unable to connect to 162.243.67.4:9876
    {"ep":"162.243.67.4:9876"}
    th_a  server.cpp:256 connect_to
1995387ms th_a       addressbook.cpp:110           store_contact        ] to_string()
1995415ms th_a       addressbook.cpp:112           store_contact        ] ... did it work?
1997158ms th_a       application.cpp:59            connect_loop         ] 162.243.67.4:9876
1997158ms th_a       server.cpp:243                connect_to           ] connect to 162.243.67.4:9876
1997536ms th_a       application.cpp:64            connect_loop         ] unspecified
Broken pipe 
    {"message":"Broken pipe"}
    asio  asio.cpp:28 read_write_handler
error connecting to 162.243.67.4:9876
    {"ep":"162.243.67.4:9876"}
    th_a  connection.cpp:194 connect
unable to connect to 162.243.67.4:9876
    {"ep":"162.243.67.4:9876"}
    th_a  server.cpp:256 connect_to
1999933ms th_a       addressbook.cpp:110           store_contact        ] to_string()
1999934ms th_a       addressbook.cpp:112           store_contact        ] ... did it work?
2000537ms th_a       application.cpp:59            connect_loop         ] 162.243.67.4:9876
2000537ms th_a       server.cpp:243                connect_to           ] connect to 162.243.67.4:9876
2000902ms th_a       application.cpp:64            connect_loop         ] unspecified
Broken pipe 
    {"message":"Broken pipe"}
    asio  asio.cpp:28 read_write_handler
error connecting to 162.243.67.4:9876
    {"ep":"162.243.67.4:9876"}
    th_a  connection.cpp:194 connect
unable to connect to 162.243.67.4:9876
    {"ep":"162.243.67.4:9876"}
    th_a  server.cpp:256 connect_to
2001788ms th_a       rpc_server.cpp:37             accept_loop          ] fatal: error opening socket for rpc connection: canceled
Operation canceled 
    {"message":"Operation canceled"}
    asio  asio.cpp:44 error_handler
Unable to accept connection on socket.
    {}
    th_a  tcp_socket.cpp:95 accept
2001789ms th_a       rpc_server.cpp:57             register_methods     ] login!
2001789ms th_a       json_connection.cpp:269       add_method           ] add method login
2001789ms th_a       json_connection.cpp:269       add_method           ] add method lookup_name
2001789ms th_a       json_connection.cpp:269       add_method           ] add method reverse_name_lookup
2001790ms th_a       json_connection.cpp:269       add_method           ] add method verify_signature
2001790ms th_a       json_connection.cpp:269       add_method           ] add method sign_message
2001790ms th_a       json_connection.cpp:269       add_method           ] add method load_profile
2001790ms th_a       json_connection.cpp:269       add_method           ] add method mine_name
2001790ms th_a       json_connection.cpp:269       add_method           ] add method add_nodes
2001791ms th_a       json_connection.cpp:269       add_method           ] add method get_connections
2001791ms th_a       thread.cpp:85                 quit                 ] joining... upnp
2001791ms th_a       thread.cpp:89                 quit                 ] done joining...upnp
2001792ms th_a       bitchat_client.cpp:70         ~client              ] 
2001792ms th_a       json_connection.cpp:225       close                ] close unspecified
Bad file descriptor 
    {"message":"Bad file descriptor"}
    asio  asio.cpp:28 read_write_handler
2001799ms th_a       thread.cpp:85                 quit                 ] joining... bitname1
2001799ms th_a       thread.cpp:89                 quit                 ] done joining...bitname1
2001806ms th_a       server.cpp:32                 close                ] closing connections...
2001807ms th_a       server.cpp:160                accept_loop          ] accept loop canceled
yuvi@ubuntu:~/project/test/keyhotee$ ./bin/Keyhotee 
2003570ms th_a       KeyhoteeApplication.cpp:263   startup              ] .
2003570ms th_a       application.cpp:212           get_profiles         ] /home/yuvi/.local/share/Keyhotee/profiles/Y G
2003570ms th_a       application.cpp:212           get_profiles         ] /home/yuvi/.local/share/Keyhotee/profiles/J G
2003570ms th_a       application.cpp:217           get_profiles         ] profiles ["Y G","J G"]
2003570ms th_a       KeyhoteeApplication.cpp:171   displayLogin         ] .
2003600ms th_a       application.cpp:212           get_profiles         ] /home/yuvi/.local/share/Keyhotee/profiles/Y G
2003600ms th_a       application.cpp:212           get_profiles         ] /home/yuvi/.local/share/Keyhotee/profiles/J G
2003600ms th_a       application.cpp:217           get_profiles         ] profiles ["Y G","J G"]
2003600ms th_a       LoginDialog.cpp:27            LoginDialog          ] profiles Y G
2003601ms th_a       LoginDialog.cpp:27            LoginDialog          ] profiles J G
2005411ms th_a       KeyhoteeApplication.cpp:186   displayProfileWizard ] .
2023341ms th_a       application.cpp:258           create_profile       ] config_file: /home/yuvi/.local/share/Keyhotee/profiles/Y G/config.json
2032365ms th_a       addressbook.cpp:58            open                 ] loading contact {"public_key":"0345f42cf16f99ecef9415e93463cbaafa0991c54f1fdf5ef1b0f42baa39a348da","dac_id_hash":16509934557292852967,"dac_id_string":"a","properties":[],"wallet_index":0,"privacy_setting":"secret_contact","first_name":"","last_name":"","icon_png":"","notes":"","next_send_trx_id":0,"send_trx_address":{"pub_key":"000000000000000000000000000000000000000000000000000000000000000000","chain_code":"0000000000000000000000000000000000000000000000000000000000000000"},"bitchat_recv_channels":[],"bitchat_broadcast_channels":[],"bitchat_recv_broadcast_key":"0000000000000000000000000000000000000000000000000000000000000000"}
2032366ms th_a       addressbook.cpp:58            open                 ] loading contact {"public_key":"0223ffec73f2f75b961a0f5054576a8b92f5c45c06319e3c4a133a9dd2b8fe7946","dac_id_hash":12774264012029919657,"dac_id_string":"b","properties":[],"wallet_index":1,"privacy_setting":"secret_contact","first_name":"","last_name":"","icon_png":"","notes":"","next_send_trx_id":0,"send_trx_address":{"pub_key":"000000000000000000000000000000000000000000000000000000000000000000","chain_code":"0000000000000000000000000000000000000000000000000000000000000000"},"bitchat_recv_channels":[],"bitchat_broadcast_channels":[],"bitchat_recv_broadcast_key":"0000000000000000000000000000000000000000000000000000000000000000"}
2036307ms th_a       application.cpp:139           configure            ] external IP 106.51.163.20
2036308ms th_a       server.cpp:206                configure            ] listening for stcp connections on port 0
2037092ms th_a       bitname_db.cpp:92             load_indexes         ] load indexes
2037093ms th_a       bitname_db.cpp:107            load_indexes         ] load indexes
2037095ms th_a       bitname_db.cpp:162            init_timekeeper      ] ...init stats...
2037095ms th_a       bitname_db.cpp:164            init_timekeeper      ] ...done init timekeeper...
2037095ms th_a       bitname_db.cpp:214            open                 ] open name db
chain time: 20130822T183833
expected time: 20130822T183833
target difficulty: 1048576
target name difficulty: 1048576
2039948ms th_a       rpc_server.cpp:245            configure            ] listening for rpc connections on port 0
2039948ms th_a       rpc_server.cpp:247            configure            ] listening for rpc connections on port 55461
QMetaObject::connectSlotsByName: No matching signal for on_actionShow_details_toggled(bool)
QLayout: Attempting to add QLayout "" to Mailbox "inbox_page", which already has a layout
QMetaObject::connectSlotsByName: No matching signal for on_actionShow_details_toggled(bool)
QMetaObject::connectSlotsByName: No matching signal for on_actionShow_details_toggled(bool)
QMetaObject::connectSlotsByName: No matching signal for on_actionShow_details_toggled(bool)
QMetaObject::connectSlotsByName: No matching signal for on_actionShow_details_toggled(bool)
QLayout: Attempting to add QLayout "" to ContactsTable "contacts_page", which already has a layout
2040191ms th_a       AddressBookModel.cpp:334      reloadContacts       ] loading contacts...
2040192ms th_a       AddressBookModel.cpp:334      reloadContacts       ] loading contacts...
2040196ms th_a       KeyhoteeMainWindow.cpp:250    KeyhoteeMainWindow   ] idents: [{"public_key":"0345f42cf16f99ecef9415e93463cbaafa0991c54f1fdf5ef1b0f42baa39a348da","dac_id_hash":16509934557292852967,"dac_id_string":"a","properties":[],"wallet_ident":"a","mining_effort":0,"first_name":"","last_name":"","private_icon_png":""},{"public_key":"0223ffec73f2f75b961a0f5054576a8b92f5c45c06319e3c4a133a9dd2b8fe7946","dac_id_hash":12774264012029919657,"dac_id_string":"b","properties":[],"wallet_ident":"b","mining_effort":0,"first_name":"","last_name":"","private_icon_png":""}]
2040325ms th_a       application.cpp:59            connect_loop         ] 162.243.67.4:9876
2040325ms th_a       server.cpp:243                connect_to           ] connect to 162.243.67.4:9876
2040750ms th_a       application.cpp:64            connect_loop         ] unspecified
Broken pipe 
    {"message":"Broken pipe"}
    asio  asio.cpp:28 read_write_handler
error connecting to 162.243.67.4:9876
    {"ep":"162.243.67.4:9876"}
    th_a  connection.cpp:194 connect
unable to connect to 162.243.67.4:9876
    {"ep":"162.243.67.4:9876"}
    th_a  server.cpp:256 connect_to
2043750ms th_a       application.cpp:59            connect_loop         ] 162.243.67.4:9876
2043751ms th_a       server.cpp:243                connect_to           ] connect to 162.243.67.4:9876
2044110ms th_a       application.cpp:64            connect_loop         ] unspecified
Broken pipe 
    {"message":"Broken pipe"}
    asio  asio.cpp:28 read_write_handler
error connecting to 162.243.67.4:9876
    {"ep":"162.243.67.4:9876"}
    th_a  connection.cpp:194 connect
unable to connect to 162.243.67.4:9876
    {"ep":"162.243.67.4:9876"}
    th_a  server.cpp:256 connect_to
Segmentation fault (core dumped)
yuvi@ubuntu:~/project/test/keyhotee$ ./bin/Keyhotee 
2319781ms th_a       KeyhoteeApplication.cpp:263   startup              ] .
2319782ms th_a       application.cpp:212           get_profiles         ] /home/yuvi/.local/share/Keyhotee/profiles/Y G
2319782ms th_a       application.cpp:212           get_profiles         ] /home/yuvi/.local/share/Keyhotee/profiles/J G
2319782ms th_a       application.cpp:217           get_profiles         ] profiles ["Y G","J G"]
2319782ms th_a       KeyhoteeApplication.cpp:171   displayLogin         ] .
2319820ms th_a       application.cpp:212           get_profiles         ] /home/yuvi/.local/share/Keyhotee/profiles/Y G
2319820ms th_a       application.cpp:212           get_profiles         ] /home/yuvi/.local/share/Keyhotee/profiles/J G
2319820ms th_a       application.cpp:217           get_profiles         ] profiles ["Y G","J G"]
2319820ms th_a       LoginDialog.cpp:27            LoginDialog          ] profiles Y G
2319820ms th_a       LoginDialog.cpp:27            LoginDialog          ] profiles J G
2325007ms th_a       application.cpp:139           configure            ] external IP 106.51.163.20
2325007ms th_a       server.cpp:206                configure            ] listening for stcp connections on port 0
2325939ms th_a       bitname_db.cpp:92             load_indexes         ] load indexes
2325939ms th_a       bitname_db.cpp:107            load_indexes         ] load indexes
2325941ms th_a       bitname_db.cpp:162            init_timekeeper      ] ...init stats...
2325942ms th_a       bitname_db.cpp:164            init_timekeeper      ] ...done init timekeeper...
2325942ms th_a       bitname_db.cpp:214            open                 ] open name db
chain time: 20130822T183833
expected time: 20130822T183833
target difficulty: 1048576
target name difficulty: 1048576
2329070ms th_a       rpc_server.cpp:245            configure            ] listening for rpc connections on port 0
2329070ms th_a       rpc_server.cpp:247            configure            ] listening for rpc connections on port 35575
2329488ms th_a       addressbook.cpp:58            open                 ] loading contact {"public_key":"0345f42cf16f99ecef9415e93463cbaafa0991c54f1fdf5ef1b0f42baa39a348da","dac_id_hash":16509934557292852967,"dac_id_string":"a","properties":[],"wallet_index":0,"privacy_setting":"secret_contact","first_name":"","last_name":"","icon_png":"","notes":"","next_send_trx_id":0,"send_trx_address":{"pub_key":"000000000000000000000000000000000000000000000000000000000000000000","chain_code":"0000000000000000000000000000000000000000000000000000000000000000"},"bitchat_recv_channels":[],"bitchat_broadcast_channels":[],"bitchat_recv_broadcast_key":"0000000000000000000000000000000000000000000000000000000000000000"}
2329489ms th_a       addressbook.cpp:58            open                 ] loading contact {"public_key":"0223ffec73f2f75b961a0f5054576a8b92f5c45c06319e3c4a133a9dd2b8fe7946","dac_id_hash":12774264012029919657,"dac_id_string":"b","properties":[],"wallet_index":1,"privacy_setting":"secret_contact","first_name":"","last_name":"","icon_png":"","notes":"","next_send_trx_id":0,"send_trx_address":{"pub_key":"000000000000000000000000000000000000000000000000000000000000000000","chain_code":"0000000000000000000000000000000000000000000000000000000000000000"},"bitchat_recv_channels":[],"bitchat_broadcast_channels":[],"bitchat_recv_broadcast_key":"0000000000000000000000000000000000000000000000000000000000000000"}
QMetaObject::connectSlotsByName: No matching signal for on_actionShow_details_toggled(bool)
QLayout: Attempting to add QLayout "" to Mailbox "inbox_page", which already has a layout
QMetaObject::connectSlotsByName: No matching signal for on_actionShow_details_toggled(bool)
QMetaObject::connectSlotsByName: No matching signal for on_actionShow_details_toggled(bool)
QMetaObject::connectSlotsByName: No matching signal for on_actionShow_details_toggled(bool)
QMetaObject::connectSlotsByName: No matching signal for on_actionShow_details_toggled(bool)
QLayout: Attempting to add QLayout "" to ContactsTable "contacts_page", which already has a layout
2333586ms th_a       AddressBookModel.cpp:334      reloadContacts       ] loading contacts...
2333586ms th_a       AddressBookModel.cpp:334      reloadContacts       ] loading contacts...
2333591ms th_a       KeyhoteeMainWindow.cpp:250    KeyhoteeMainWindow   ] idents: [{"public_key":"0345f42cf16f99ecef9415e93463cbaafa0991c54f1fdf5ef1b0f42baa39a348da","dac_id_hash":16509934557292852967,"dac_id_string":"a","properties":[],"wallet_ident":"a","mining_effort":0,"first_name":"","last_name":"","private_icon_png":""},{"public_key":"0223ffec73f2f75b961a0f5054576a8b92f5c45c06319e3c4a133a9dd2b8fe7946","dac_id_hash":12774264012029919657,"dac_id_string":"b","properties":[],"wallet_ident":"b","mining_effort":0,"first_name":"","last_name":"","private_icon_png":""}]
2333661ms th_a       application.cpp:59            connect_loop         ] 162.243.67.4:9876
2333661ms th_a       server.cpp:243                connect_to           ] connect to 162.243.67.4:9876
2334019ms th_a       application.cpp:64            connect_loop         ] unspecified
Broken pipe 
    {"message":"Broken pipe"}
    asio  asio.cpp:28 read_write_handler
error connecting to 162.243.67.4:9876
    {"ep":"162.243.67.4:9876"}
    th_a  connection.cpp:194 connect
unable to connect to 162.243.67.4:9876
    {"ep":"162.243.67.4:9876"}
    th_a  server.cpp:256 connect_to
2337020ms th_a       application.cpp:59            connect_loop         ] 162.243.67.4:9876
2337020ms th_a       server.cpp:243                connect_to           ] connect to 162.243.67.4:9876
2337310ms th_a       application.cpp:64            connect_loop         ] unspecified
Broken pipe 
    {"message":"Broken pipe"}
    asio  asio.cpp:28 read_write_handler
error connecting to 162.243.67.4:9876
    {"ep":"162.243.67.4:9876"}
    th_a  connection.cpp:194 connect
unable to connect to 162.243.67.4:9876
    {"ep":"162.243.67.4:9876"}
    th_a  server.cpp:256 connect_to
2340310ms th_a       application.cpp:59            connect_loop         ] 162.243.67.4:9876
2340311ms th_a       server.cpp:243                connect_to           ] connect to 162.243.67.4:9876
2340610ms th_a       application.cpp:64            connect_loop         ] unspecified
Broken pipe 
    {"message":"Broken pipe"}
    asio  asio.cpp:28 read_write_handler
error connecting to 162.243.67.4:9876
    {"ep":"162.243.67.4:9876"}
    th_a  connection.cpp:194 connect
unable to connect to 162.243.67.4:9876
    {"ep":"162.243.67.4:9876"}
    th_a  server.cpp:256 connect_to
Segmentation fault (core dumped)

**Comment by dnotestein** [comment]
Yuvaraj, can you test and confirm if this still happens with the new release?

**Comment by yuvarajgogoi** [comment]
its is not reproducible with the today's release.
