### ISSUE TITLE
selecting a message at Inbox, drafts and sent folders and deleting it should next select another mesage immediately next to it or the previous one if it is the last message?

### ISSUE THREAD

**Issue by yuvarajgogoi** [InvictusInnovations/keyhotee#179]

**Comment by vogel76** [comment]
Yes I think this is good enhancement.

**Comment by vogel76** [comment]
I think this issue is similar to this one:
https://github.com/InvictusInnovations/keyhotee/issues/172

**Comment by yuvarajgogoi** [comment]
no .. This issue is quite different from 172... 172 is a bug.  In scenario of 172, Proper highlight is not happening for contact after selecting. the focus of a row is not happening on the correct row after singleclick of the row. Details form is though populating properly.

**Comment by PaulEU** [comment]
Fixed at rev: https://github.com/InvictusInnovations/keyhotee/commit/52a987a1f20102da3f6dd41365b2dce4bfdcd068
