### ISSUE TITLE
closing a window at the time of creating the profile(process bar window) leads to segmentation fault

### ISSUE THREAD

**Issue by yuvarajgogoi** [InvictusInnovations/keyhotee#180]
Steps to reproduce:
1) create a profile.
2) Close immediately after finish button.
 segmentation fault occurs.

Tested on Ubuntu.

log:

yuvi@ubuntu:~/project/test/keyhotee$ ./bin/Keyhotee
520333ms th_a       KeyhoteeApplication.cpp:263   startup              ] .
520383ms th_a       application.cpp:217           get_profiles         ] profiles []
520437ms th_a       KeyhoteeApplication.cpp:186   displayProfileWizard ] .
551933ms th_a       application.cpp:258           create_profile       ] config_file: /home/yuvi/.local/share/Keyhotee/profiles/Y G/config.json

566620ms th_a       application.cpp:139           configure            ] external IP 106.51.163.20
566620ms th_a       server.cpp:206                configure            ] listening for stcp connections on port 0
567887ms th_a       bitname_db.cpp:92             load_indexes         ] load indexes
567887ms th_a       bitname_db.cpp:107            load_indexes         ] load indexes
567890ms th_a       bitname_db.cpp:162            init_timekeeper      ] ...init stats...
567890ms th_a       bitname_db.cpp:164            init_timekeeper      ] ...done init timekeeper...
567891ms th_a       bitname_db.cpp:214            open                 ] open name db
chain time: 20130822T183833
expected time: 20130822T183833
target difficulty: 1048576
target name difficulty: 1048576
571631ms th_a       rpc_server.cpp:245            configure            ] listening for rpc connections on port 0
571644ms th_a       rpc_server.cpp:247            configure            ] listening for rpc connections on port 52271
QMetaObject::connectSlotsByName: No matching signal for on_actionShow_details_toggled(bool)
QLayout: Attempting to add QLayout "" to Mailbox "inbox_page", which already has a layout
QMetaObject::connectSlotsByName: No matching signal for on_actionShow_details_toggled(bool)
QMetaObject::connectSlotsByName: No matching signal for on_actionShow_details_toggled(bool)
QMetaObject::connectSlotsByName: No matching signal for on_actionShow_details_toggled(bool)
QMetaObject::connectSlotsByName: No matching signal for on_actionShow_details_toggled(bool)
QLayout: Attempting to add QLayout "" to ContactsTable "contacts_page", which already has a layout
572329ms th_a       KeyhoteeMainWindow.cpp:250    KeyhoteeMainWindow   ] idents: []
Segmentation fault (core dumped)

**Comment by vogel76** [comment]
Fixed at rev: https://github.com/InvictusInnovations/keyhotee/commit/2038b400694d154591bbc225d28ae31759a6f0b7
