### ISSUE TITLE
Keyhotee not fully shutting down after creating new profile

### ISSUE THREAD

**Issue by dnotestein** [InvictusInnovations/keyhotee#187]
To duplicate, create a new profile, then shut down Keyhotee.  Kehotee gui goes away but console window remains. Last msg in console is "closing connections...".

**Comment by dnotestein** [comment]
In this case, we never hit breakpoint placed on TKeyhoteeApplication::run() line 166:
return _exit_status;

**Comment by vogel76** [comment]
Fixed at rev: https://github.com/InvictusInnovations/keyhotee/commit/175b954cb433d899816d0f94e2577110f6ea05d5
