### ISSUE TITLE
Crash when quit from Login Screen

### ISSUE THREAD

**Issue by bytemaster** [InvictusInnovations/keyhotee#188]
Thread 0 Crashed:: Dispatch queue: com.apple.main-thread
0   libsystem_kernel.dylib          0x00007fff92a3a212 __pthread_kill + 10
1   libsystem_c.dylib               0x00007fff8d3fab54 pthread_kill + 90
2   libsystem_c.dylib               0x00007fff8d43edce abort + 143
3   libstdc++.6.dylib               0x00000001089f7d76 __gnu_cxx::__verbose_terminate_handler() + 192
4   libstdc++.6.dylib               0x00000001089f6300 0x1089f3000 + 13056
5   libstdc++.6.dylib               0x00000001089f5673 0x1089f3000 + 9843
6   libstdc++.6.dylib               0x00000001089f5f1d __gxx_personality_v0 + 853
7   libunwind.dylib                 0x00007fff89c6f860 unwind_phase2 + 186
8   libunwind.dylib                 0x00007fff89c73230 _Unwind_Resume + 72
9   com.invictus-innovations.Keyhotee   0x0000000104f7ee37 fc::console_appender::log(fc::log_message const&) + 3767 (basic_string.h:539)
10  ???                             0x000000010aca8d00 0 + 4476013824

**Comment by vogel76** [comment]
Fixed at rev: https://github.com/InvictusInnovations/BitShares/commit/7307e7f2c020a535ce6cb4f7fd63f4ddfe25d0a9
