### ISSUE TITLE
Add status indicator to inbox messages to note whether they have been replied to or forwarded.

### ISSUE THREAD

**Issue by bytemaster** [InvictusInnovations/keyhotee#200]

**Comment by vogel76** [comment]
I think underlying storage for mail message should be enhanced by storage of related message (with flag determining kind: forward, reply). Maybe message digest could be sufficient (or other peristent data to uniquely identify a message). This was application will have  access to such related message, and gui can show a thread for given conversation and also allows to walk over messages included in it.
