### ISSUE TITLE
Check and Double Check Profile Seed / Password 

### ISSUE THREAD

**Issue by bytemaster** [InvictusInnovations/keyhotee#203]
Some people are unable to login after the log out.  We should check that we can 'unlock' the stretched seed after saving it and take extra precautions around managing that file to make sure we never corrupt it.

We also need to make sure we trim white space from all fields in the Profile Wizard and support UTF8

Lastly the First name field is required in the Profile Wizard, find out what happens when it is left blank.

**Comment by dnotestein** [comment]
Second and third parts of this are completed, and I'm not sure unlock check is useful. Problems to date associating with being unable to login have all been due to other issues, so going to close out this issue.
