### ISSUE TITLE
Deleting & Recreating an Identity 

### ISSUE THREAD

**Issue by bytemaster** [InvictusInnovations/keyhotee#209]
1. I Create an identity and then delete them, there's nowhere to recover the ID? I re-create the same ID, it reports 'you have created this ID...

**Comment by vipjeffreylee** [comment]
delete profile of the ID directory,then recreate profile,you can re-create the same ID. but lose old mail and　　address book etc data.

**Comment by vogel76** [comment]
I am not sure but maybe it somehow related problem: bts api doesn't provide a way to delete created identity. Thus deleting the implicit contact created for such identity removes just the contact (not identity). Then if you next time try to create again such identity application reports that such id already exists.

**Comment by dnotestein** [comment]
Closing as this duplicates issue https://github.com/InvictusInnovations/keyhotee/issues/166
