### ISSUE TITLE
Unable to load profile after unsuccessfull login

### ISSUE THREAD

**Issue by vogel76** [InvictusInnovations/keyhotee#210]
Create some profile. Then quit and try to log into using bad password. After 1st try (in the same instance of app) try to login using good password. Appears error 'Unable to load profile' because 1st login try established lock over underlying database. I think loaded databases should be somehow pooled by backend (to avoid 2nd loading & invalid lock error) or explictly released after unsuccessfull login.

**Comment by PaulEU** [comment]
related to issue #128

**Comment by vogel76** [comment]
Fixed at rev: https://github.com/InvictusInnovations/BitShares/commit/c8f64faca9a8e2e2d4efc321974f365413cfdfd8
