### ISSUE TITLE
Unicode Characters in Profile Name vs Filesystem

### ISSUE THREAD

**Issue by bytemaster** [InvictusInnovations/keyhotee#212]
One other problem: If the name contains special characters the folder generated in AppData contains wrong characters, looks like character set mismatch between what is used by the tool and what is written to the file system. I am using Windows 7 x64, running on standard NTFS file system which is using Unicode.
For example with First Name "Mister" and Last Name "Test ö Test ä Test ü Test á Test à Test â Test ß" the resulting folder name is: "Mister Test Ã¶ Test Ã¤ Test Ã¼ Test Ã¡ Test Ã  Test Ã¢ Test ÃŸ".

**Comment by vogel76** [comment]
Fixed at rev:
https://github.com/InvictusInnovations/keyhotee/commit/7ab0ed712f6cc63f75394caf1a304507d9560a0d
https://github.com/InvictusInnovations/BitShares/commit/9cc046f43c10b550586f589e69ca0b7bdd4143f1
https://github.com/InvictusInnovations/fc/commit/59f80e34d26fff9cce761cf22bcafea6d6553a0d
