### ISSUE TITLE
Build fails on Linux 32 bit - __mm_crc32_u64

### ISSUE THREAD

**Issue by arcke** [InvictusInnovations/keyhotee#216]
<pre><code>
/home/arcke/keyhotee/BitShares/fc/src/crypto/city.cpp: In function ‘void fc::CityHashCrc256Long(const char*, std::size_t, uint32_t, uint64_t*)’:
/home/arcke/keyhotee/BitShares/fc/src/crypto/city.cpp:428:5: error: ‘_mm_crc32_u64’ was not declared in this scope
/home/arcke/keyhotee/BitShares/fc/src/crypto/city.cpp:434:5: error: ‘_mm_crc32_u64’ was not declared in this scope
/home/arcke/keyhotee/BitShares/fc/src/crypto/city.cpp:439:5: error: ‘_mm_crc32_u64’ was not declared in this scope
compilation terminated due to -fmax-errors=3.
make[2]: *** [BitShares/fc/CMakeFiles/fc.dir/src/crypto/city.cpp.o] Error 1
make[1]: *** [BitShares/fc/CMakeFiles/fc.dir/all] Error 2
make: *** [all] Error 2
</code></pre>

This only happens on 32 bit installs of Linux. Confirmed on Mint and Debian.

See https://bitsharestalk.org/index.php?topic=1974.msg24033#msg24033

**Comment by xeroc** [comment]
Same issue here on Archlinux (32bit).

//EDIT: thanks for fixing

**Comment by dnotestein** [comment]
We need to use another hash algorithm for linux 32 bit I guess (see bitshares talk link above for details). Just do it with an #ifdef probably for Linux 32 bit.

**Comment by bytemaster** [comment]
Cannot do this if it breaks profile compatibility or proof of work compatibility.  Just be careful.

I believe there is a software implementation of mmcrc32_u64 somewhere around that will maintain compataiblity.

**Comment by yuvarajgogoi** [comment]
fixed. Arche, please check and let me know if its fine.

**Comment by arcke** [comment]
No, just pulled and compiled and got this error.

<pre><code>BitShares/fc/libfc.a(city.cpp.o): In function `CityHashCrc256Long':
/home/arcke/keyhotee/BitShares/fc/src/crypto/city.cpp:428: undefined reference to`_mm_crc32_u64(unsigned long long, unsigned long long)'
/home/arcke/keyhotee/BitShares/fc/src/crypto/city.cpp:428: undefined reference to `_mm_crc32_u64(unsigned long long, unsigned long long)'
/home/arcke/keyhotee/BitShares/fc/src/crypto/city.cpp:428: undefined reference to`_mm_crc32_u64(unsigned long long, unsigned long long)'
/home/arcke/keyhotee/BitShares/fc/src/crypto/city.cpp:428: undefined reference to `_mm_crc32_u64(unsigned long long, unsigned long long)'
/home/arcke/keyhotee/BitShares/fc/src/crypto/city.cpp:428: undefined reference to`_mm_crc32_u64(unsigned long long, unsigned long long)'
BitShares/fc/libfc.a(city.cpp.o):/home/arcke/keyhotee/BitShares/fc/src/crypto/city.cpp:428: more undefined references to `_mm_crc32_u64(unsigned long long, unsigned long long)' follow
collect2: error: ld returned 1 exit status
make[2]: **\* [bin/Keyhotee] Error 1
make[1]: **\* [CMakeFiles/Keyhotee.dir/all] Error 2
make: **\* [all] Error 2
</code>

**Comment by yuvarajgogoi** [comment]
Please check again now. Also please let me know your skype id or email id at yuvarajgogoi at gmail dot com so that we can discuss in more detail if the issue still persists. My skype id is yuvaraj.gogoi

**Comment by arcke** [comment]
It's fixed. Further contact information has been emailed to you.
