### ISSUE TITLE
crash seen on saving message on a particular scenario

### ISSUE THREAD

**Issue by yuvarajgogoi** [InvictusInnovations/keyhotee#217]
Steps to reproduce:
1) start 2 clients.
2) create 1 identity on a client.
3) add this contact on the other clinet.
4) Now compose a message to this client.
5) save this message

Now crash is seen

Tested on Ubuntu and is always reproducible.

log : 

561169ms       th_a              startup ] .            KeyhoteeApplication.cpp:263
561170ms       th_a         get_profiles ] /home/yuvi/.local/share/Keyhotee/profiles/Y G            application.cpp:308
561170ms       th_a         get_profiles ] /home/yuvi/.local/share/Keyhotee/profiles/J G            application.cpp:308
561170ms       th_a         get_profiles ] profiles ["Y G","J G"]           application.cpp:313
561170ms       th_a         displayLogin ] .            KeyhoteeApplication.cpp:171
561201ms       th_a         get_profiles ] /home/yuvi/.local/share/Keyhotee/profiles/Y G            application.cpp:308
561201ms       th_a         get_profiles ] /home/yuvi/.local/share/Keyhotee/profiles/J G            application.cpp:308
561201ms       th_a         get_profiles ] profiles ["Y G","J G"]           application.cpp:313
561201ms       th_a          LoginDialog ] profiles Y G         LoginDialog.cpp:28
561201ms       th_a          LoginDialog ] profiles J G         LoginDialog.cpp:28
565249ms       th_a            configure ] Failed to connect to external IP address: unspecified
process exited with: Connection refused 
    {"message":"Connection refused"}
    asio  asio.cpp:83 resolve_handler           application.cpp:235
565249ms       th_a            configure ] listening for stcp connections on port 9876          server.cpp:207
566352ms       th_a         load_indexes ] load indexes         bitname_db.cpp:92
566352ms       th_a         load_indexes ] load indexes         bitname_db.cpp:107
566354ms       th_a      init_timekeeper ] ...init stats...         bitname_db.cpp:162
566354ms       th_a      init_timekeeper ] ...done init timekeeper...           bitname_db.cpp:164
566354ms       th_a                 open ] open name db         bitname_db.cpp:214
569217ms       th_a            configure ] listening for rpc connections on port 9877           rpc_server.cpp:245
569217ms       th_a            configure ] listening for rpc connections on port 9877           rpc_server.cpp:247
569701ms       th_a                 open ] loading contact {"public_key":"034a5e140ff8e79c3df4f197554811a71d5e4e5e43cd78641c8df3799c2eced5c5","dac_id_hash":0,"dac_id_string":" ","properties":[],"wallet_index":0,"privacy_setting":"secret_contact","first_name":"","last_name":"","icon_png":"89504e470d0a1a0a0000000d4948445200000020000000200806000000737a7af4000000097048597300000ec400000ec401952b0e1b00000392494441545885c5565d685c45183ddf7767eedd9b266977d3ba9a606ab0d522be2885405bd0a850a48a2fcd922294f8d2580a0505695f24e44d057df1a969f1af08765350b10f0afe2315a38896a0fd71355ada1a4d03d5cdeebd77ef9dcf871aec9add6476b3a51fcccb70e69c33e7ce7c77801b5cd4cca23d3f84f7926090c46c0200213e2d8489f1bbbc6fafab81c7cf4aa71704e34cc8d5582b46900f53a93d6fde417fb5dcc0e049f15dbffc0913fa97c219c15751d91f98d842651b5eb63500af381619d31f24064b8dc8987e78c5315b5aab04b67cf1674797eb5d24a0dd062f40f17214769fdcb6eeefe5b0ca86d067bd358c8d95f8bfd5eeb3de0ae0fd96188812e9214803fa80807a6c705606ca1553646ecc80212ab6cc40548926855988c8eacc88889071276db0d6d770e307331f12f0a09501e0a373dbb30fd960ad1200803049f6433009a2554babcb3c08fb6d791bea84d977cf3f00e2091032b5c531073183338fddfaf1753100006d277eb9d98b9d0302de49909eabba7481608e872a79bef448dfef8df0597f82852a7d3d3d5beaee7e0bc06952b40102124101b139052e5e6e94cf3e81c3852c91799a140f43d34d60fa8f41001801123327091d95927911fb369e6f99013e7c762f7bce73e43a9d6000f56ea3082080c4a68404a371e1f5973036669a37909f72dd79ff35f29d5d70c83eaf85442ae6bd707e6e08239b4b8d1b38f48d4ef999b739e5ec80d3d4bb05108144c9a7e5901ec6137d412d48dddf719b9f7e59fb6a87a3180e51738319ca53f7b7b7f1abf5746a6e6dd5d19f73da57c748513d4843254620b119b9925b3fbeac81f4a1c26aa4f519c7e3ec8a95ab4d5c2957e24da55c759f58d40738ad9f511e678957bef36a625aed907ab604ecbb76ba4aa5ebc88f1deeda8edf58f19ad6aa5f2d01ca89a6db66b6dff2c7c25c5502a9b59d434ad39abaf77ca5068cf81c9861002fd434a05df52b1b131053aa0567efffe2a844663a367cecdaf94532ebdfb934a0148e2b4519cbf7c7d2c20be241f27d18941ebdb8abba45d754e8cd4ff779befb86d2ce3676a8a9300400441057c444417c2498a5a72e8df42cea88f5b9474779c33d4f0e6b4da35a732f3160958800228224164491f9322a570e4e0ff57e5e0fbe3c637ecabd53a7776acdbbd9e1fb1c4529225a744e4500930892d8ccc5b19ca88495577ecaf57eb61c7d43e9aecb4fb56774d766877137446e274627091901cd9a44ce4562be2b64ba4f6180e246786f68fd0376596dac58d6da930000000049454e44ae426082","notes":"","next_send_trx_id":0,"send_trx_address":{"pub_key":"000000000000000000000000000000000000000000000000000000000000000000","chain_code":"0000000000000000000000000000000000000000000000000000000000000000"},"bitchat_recv_channels":[],"bitchat_broadcast_channels":[],"bitchat_recv_broadcast_key":"0000000000000000000000000000000000000000000000000000000000000000"}          addressbook.cpp:58
572678ms       th_a       reloadContacts ] loading contacts...          AddressBookModel.cpp:356
572684ms       th_a   KeyhoteeMainWindow ] idents: []           KeyhoteeMainWindow.cpp:250
583807ms       th_a    accept_connection ] accepted connection from 127.0.0.1:41954         server.cpp:115
583808ms       th_a         on_connected ] on connected...          peer_channel.cpp:162
583809ms       th_a     handle_subscribe ] 127.0.0.1:41954: {"channels":[{"proto":"chat_proto","chan":0},{"proto":"name_proto","chan":0},{"proto":"peer_proto","chan":0}]}          peer_channel.cpp:339
583810ms       th_a request_block_header ] requesting block headers from 127.0.0.1:41954            bitname_channel.cpp:498
583810ms       th_a       handle_message ] get_headers_msg          bitname_channel.cpp:444
583811ms       th_a       handle_message ] headers_msg          bitname_channel.cpp:444
583811ms       th_a       handle_headers ] received ${x} block headers          bitname_channel.cpp:727
609956ms       th_a                 stop ] stopping at block version 0          bitname_miner.cpp:194
614507ms       th_a       handle_message ] block_inv_msg            bitname_channel.cpp:444
614507ms       th_a     handle_block_inv ] inv: {"block_ids":["0000070a215d5f47fe258512411bb9f24d2695faa4b14322bd2ad1a7"]}          bitname_channel.cpp:530
614514ms       th_a fetch_block_idx_from ] 0000070a215d5f47fe258512411bb9f24d2695faa4b14322bd2ad1a7         bitname_channel.cpp:390
614515ms       th_a fetch_block_idx_from ] con 0            bitname_channel.cpp:395
614515ms       th_a fetch_block_idx_from ] request {"block_id":"0000070a215d5f47fe258512411bb9f24d2695faa4b14322bd2ad1a7"}          bitname_channel.cpp:399
614515ms       th_a       handle_message ] block_index_msg          bitname_channel.cpp:444
614515ms       th_a   handle_block_index ] {"index":{"header":{"nonce":17512,"age":1,"utc_sec":"20140107T101012","trxs_hash":"162018234875081307372861003289426008907","name_hash":8980070599008415687,"repute_points":1,"master_key":"03331fa4c35357d3fa313d13653fe07a07cbf416d3557f86a0af002550dac5e75e","active_key":"03331fa4c35357d3fa313d13653fe07a07cbf416d3557f86a0af002550dac5e75e","change_sig":null,"prev":"df12d19b07ca6dfcc179adfb48ab4f0350882e9d84c735119b647f4f"},"name_trxs":[]}}          bitname_channel.cpp:631
614517ms       th_a            validated ] 0000070a215d5f47fe258512411bb9f24d2695faa4b14322bd2ad1a7   {"header":{"nonce":17512,"age":1,"utc_sec":"20140107T101012","trxs_hash":"162018234875081307372861003289426008907","name_hash":8980070599008415687,"repute_points":1,"master_key":"03331fa4c35357d3fa313d13653fe07a07cbf416d3557f86a0af002550dac5e75e","active_key":"03331fa4c35357d3fa313d13653fe07a07cbf416d3557f86a0af002550dac5e75e","change_sig":null,"prev":"df12d19b07ca6dfcc179adfb48ab4f0350882e9d84c735119b647f4f"},"name_trxs":[]}   true          broadcast_manager.hpp:129
614519ms       th_a     name_block_added ] name block added
{
  "nonce": 17512,
  "age": 1,
  "utc_sec": "20140107T101012",
  "trxs_hash": "162018234875081307372861003289426008907",
  "name_hash": 8980070599008415687,
  "repute_points": 1,
  "master_key": "03331fa4c35357d3fa313d13653fe07a07cbf416d3557f86a0af002550dac5e75e",
  "active_key": "03331fa4c35357d3fa313d13653fe07a07cbf416d3557f86a0af002550dac5e75e",
  "change_sig": null,
  "prev": "df12d19b07ca6dfcc179adfb48ab4f0350882e9d84c735119b647f4f",
  "name_trxs": []
}           bitname_client.cpp:60
614519ms       th_a                 stop ] stopping at block version 1          bitname_miner.cpp:194
617191ms       th_a       handle_message ] block_inv_msg            bitname_channel.cpp:444
617191ms       th_a     handle_block_inv ] inv: {"block_ids":["00000add397e44b9530ddf3d7e93b63b5dda3ebd0cedf11852242dfa"]}          bitname_channel.cpp:530
617201ms       th_a fetch_block_idx_from ] 00000add397e44b9530ddf3d7e93b63b5dda3ebd0cedf11852242dfa         bitname_channel.cpp:390
617214ms       th_a fetch_block_idx_from ] con 0            bitname_channel.cpp:395
617214ms       th_a fetch_block_idx_from ] request {"block_id":"00000add397e44b9530ddf3d7e93b63b5dda3ebd0cedf11852242dfa"}          bitname_channel.cpp:399
617215ms       th_a       handle_message ] block_index_msg          bitname_channel.cpp:444
617216ms       th_a   handle_block_index ] {"index":{"header":{"nonce":61141,"age":1,"utc_sec":"20140107T101017","trxs_hash":"42639633428805596840468947668259752689","name_hash":8980070599008415687,"repute_points":2,"master_key":"03331fa4c35357d3fa313d13653fe07a07cbf416d3557f86a0af002550dac5e75e","active_key":"03331fa4c35357d3fa313d13653fe07a07cbf416d3557f86a0af002550dac5e75e","change_sig":null,"prev":"0000070a215d5f47fe258512411bb9f24d2695faa4b14322bd2ad1a7"},"name_trxs":[]}}           bitname_channel.cpp:631
617216ms       th_a            validated ] 00000add397e44b9530ddf3d7e93b63b5dda3ebd0cedf11852242dfa   {"header":{"nonce":61141,"age":1,"utc_sec":"20140107T101017","trxs_hash":"42639633428805596840468947668259752689","name_hash":8980070599008415687,"repute_points":2,"master_key":"03331fa4c35357d3fa313d13653fe07a07cbf416d3557f86a0af002550dac5e75e","active_key":"03331fa4c35357d3fa313d13653fe07a07cbf416d3557f86a0af002550dac5e75e","change_sig":null,"prev":"0000070a215d5f47fe258512411bb9f24d2695faa4b14322bd2ad1a7"},"name_trxs":[]}   true           broadcast_manager.hpp:129
617218ms       th_a     name_block_added ] name block added
{
  "nonce": 61141,
  "age": 1,
  "utc_sec": "20140107T101017",
  "trxs_hash": "42639633428805596840468947668259752689",
  "name_hash": 8980070599008415687,
  "repute_points": 2,
  "master_key": "03331fa4c35357d3fa313d13653fe07a07cbf416d3557f86a0af002550dac5e75e",
  "active_key": "03331fa4c35357d3fa313d13653fe07a07cbf416d3557f86a0af002550dac5e75e",
  "change_sig": null,
  "prev": "0000070a215d5f47fe258512411bb9f24d2695faa4b14322bd2ad1a7",
  "name_trxs": []
}           bitname_client.cpp:60
617219ms       th_a                 stop ] stopping at block version 2          bitname_miner.cpp:194
622098ms       th_a       handle_message ] block_inv_msg            bitname_channel.cpp:444
622098ms       th_a     handle_block_inv ] inv: {"block_ids":["000003e1627954f86ec159548450b8d2a475f4d0f3d7ff0efc10a200"]}          bitname_channel.cpp:530
622117ms       th_a fetch_block_idx_from ] 000003e1627954f86ec159548450b8d2a475f4d0f3d7ff0efc10a200         bitname_channel.cpp:390
622117ms       th_a fetch_block_idx_from ] con 0            bitname_channel.cpp:395
622117ms       th_a fetch_block_idx_from ] request {"block_id":"000003e1627954f86ec159548450b8d2a475f4d0f3d7ff0efc10a200"}          bitname_channel.cpp:399
622118ms       th_a       handle_message ] block_index_msg          bitname_channel.cpp:444
622118ms       th_a   handle_block_index ] {"index":{"header":{"nonce":27383,"age":1,"utc_sec":"20140107T101022","trxs_hash":"183299756634697469565280190944310686430","name_hash":8980070599008415687,"repute_points":3,"master_key":"03331fa4c35357d3fa313d13653fe07a07cbf416d3557f86a0af002550dac5e75e","active_key":"03331fa4c35357d3fa313d13653fe07a07cbf416d3557f86a0af002550dac5e75e","change_sig":null,"prev":"00000add397e44b9530ddf3d7e93b63b5dda3ebd0cedf11852242dfa"},"name_trxs":[]}}          bitname_channel.cpp:631
622119ms       th_a            validated ] 000003e1627954f86ec159548450b8d2a475f4d0f3d7ff0efc10a200   {"header":{"nonce":27383,"age":1,"utc_sec":"20140107T101022","trxs_hash":"183299756634697469565280190944310686430","name_hash":8980070599008415687,"repute_points":3,"master_key":"03331fa4c35357d3fa313d13653fe07a07cbf416d3557f86a0af002550dac5e75e","active_key":"03331fa4c35357d3fa313d13653fe07a07cbf416d3557f86a0af002550dac5e75e","change_sig":null,"prev":"00000add397e44b9530ddf3d7e93b63b5dda3ebd0cedf11852242dfa"},"name_trxs":[]}   true          broadcast_manager.hpp:129
622120ms       th_a     name_block_added ] name block added
{
  "nonce": 27383,
  "age": 1,
  "utc_sec": "20140107T101022",
  "trxs_hash": "183299756634697469565280190944310686430",
  "name_hash": 8980070599008415687,
  "repute_points": 3,
  "master_key": "03331fa4c35357d3fa313d13653fe07a07cbf416d3557f86a0af002550dac5e75e",
  "active_key": "03331fa4c35357d3fa313d13653fe07a07cbf416d3557f86a0af002550dac5e75e",
  "change_sig": null,
  "prev": "00000add397e44b9530ddf3d7e93b63b5dda3ebd0cedf11852242dfa",
  "name_trxs": []
}           bitname_client.cpp:60
622120ms       th_a                 stop ] stopping at block version 3          bitname_miner.cpp:194
634066ms       th_a        store_contact ] to_string()          addressbook.cpp:110
634067ms       th_a        store_contact ] ... did it work?         addressbook.cpp:112
641185ms       th_a       handle_message ] name_inv_msg         bitname_channel.cpp:444
641185ms       th_a      handle_name_inv ] inv: {"name_trxs":[14845087726348464037]}            bitname_channel.cpp:519
641194ms       th_a fetch_name_from_best ] 14845087726348464037         bitname_channel.cpp:345
641194ms       th_a fetch_name_from_best ] con 0            bitname_channel.cpp:350
641194ms       th_a fetch_name_from_best ] request {"name_trx_id":14845087726348464037}         bitname_channel.cpp:356
641194ms       th_a       handle_message ] name_header_msg          bitname_channel.cpp:444
641195ms       th_a          handle_name ] {"trx":{"nonce":58016,"age":1,"utc_sec":"20140107T101041","trxs_hash":"123754613333783993256142821851723982507","name_hash":8980070599008415687,"repute_points":4,"master_key":"03331fa4c35357d3fa313d13653fe07a07cbf416d3557f86a0af002550dac5e75e","active_key":"03331fa4c35357d3fa313d13653fe07a07cbf416d3557f86a0af002550dac5e75e","change_sig":null,"prev":"000003e1627954f86ec159548450b8d2a475f4d0f3d7ff0efc10a200"}}          bitname_channel.cpp:674
641195ms       th_a            validated ] 14845087726348464037   {"nonce":58016,"age":1,"utc_sec":"20140107T101041","trxs_hash":"123754613333783993256142821851723982507","name_hash":8980070599008415687,"repute_points":4,"master_key":"03331fa4c35357d3fa313d13653fe07a07cbf416d3557f86a0af002550dac5e75e","active_key":"03331fa4c35357d3fa313d13653fe07a07cbf416d3557f86a0af002550dac5e75e","change_sig":null,"prev":"000003e1627954f86ec159548450b8d2a475f4d0f3d7ff0efc10a200"}   true            broadcast_manager.hpp:129
641195ms       th_a     pending_name_trx ] pending name trx  {"nonce":58016,"age":1,"utc_sec":"20140107T101041","trxs_hash":"123754613333783993256142821851723982507","name_hash":8980070599008415687,"repute_points":4,"master_key":"03331fa4c35357d3fa313d13653fe07a07cbf416d3557f86a0af002550dac5e75e","active_key":"03331fa4c35357d3fa313d13653fe07a07cbf416d3557f86a0af002550dac5e75e","change_sig":null,"prev":"000003e1627954f86ec159548450b8d2a475f4d0f3d7ff0efc10a200"}            bitname_client.cpp:50
641196ms       th_a         add_name_trx ] not currently mining, ignoring name trx          bitname_miner.cpp:212
644192ms       th_a       handle_message ] block_inv_msg            bitname_channel.cpp:444
644192ms       th_a     handle_block_inv ] inv: {"block_ids":["000005992540b1eb76927bbc0829a306558e7e88fdba0af7621a7ab3"]}          bitname_channel.cpp:530
644197ms       th_a fetch_block_idx_from ] 000005992540b1eb76927bbc0829a306558e7e88fdba0af7621a7ab3         bitname_channel.cpp:390
644197ms       th_a fetch_block_idx_from ] con 0            bitname_channel.cpp:395
644197ms       th_a fetch_block_idx_from ] request {"block_id":"000005992540b1eb76927bbc0829a306558e7e88fdba0af7621a7ab3"}          bitname_channel.cpp:399
644198ms       th_a       handle_message ] block_index_msg          bitname_channel.cpp:444
644198ms       th_a   handle_block_index ] {"index":{"header":{"nonce":58376,"age":1,"utc_sec":"20140107T101044","trxs_hash":"123754613333783993256142821851723982507","name_hash":8980070599008415687,"repute_points":4,"master_key":"03331fa4c35357d3fa313d13653fe07a07cbf416d3557f86a0af002550dac5e75e","active_key":"03331fa4c35357d3fa313d13653fe07a07cbf416d3557f86a0af002550dac5e75e","change_sig":null,"prev":"000003e1627954f86ec159548450b8d2a475f4d0f3d7ff0efc10a200"},"name_trxs":[]}}          bitname_channel.cpp:631
644198ms       th_a            validated ] 000005992540b1eb76927bbc0829a306558e7e88fdba0af7621a7ab3   {"header":{"nonce":58376,"age":1,"utc_sec":"20140107T101044","trxs_hash":"123754613333783993256142821851723982507","name_hash":8980070599008415687,"repute_points":4,"master_key":"03331fa4c35357d3fa313d13653fe07a07cbf416d3557f86a0af002550dac5e75e","active_key":"03331fa4c35357d3fa313d13653fe07a07cbf416d3557f86a0af002550dac5e75e","change_sig":null,"prev":"000003e1627954f86ec159548450b8d2a475f4d0f3d7ff0efc10a200"},"name_trxs":[]}   true          broadcast_manager.hpp:129
644201ms       th_a     name_block_added ] name block added
{
  "nonce": 58376,
  "age": 1,
  "utc_sec": "20140107T101044",
  "trxs_hash": "123754613333783993256142821851723982507",
  "name_hash": 8980070599008415687,
  "repute_points": 4,
  "master_key": "03331fa4c35357d3fa313d13653fe07a07cbf416d3557f86a0af002550dac5e75e",
  "active_key": "03331fa4c35357d3fa313d13653fe07a07cbf416d3557f86a0af002550dac5e75e",
  "change_sig": null,
  "prev": "000003e1627954f86ec159548450b8d2a475f4d0f3d7ff0efc10a200",
  "name_trxs": []
}           bitname_client.cpp:60
644201ms       th_a                 stop ] stopping at block version 4          bitname_miner.cpp:194
644955ms       th_a   displayFailureInfo ] assert
other.my->_key != nullptr: 
    {}
    th_a  elliptic.cpp:439 get_shared_secret            KeyhoteeApplication.cpp:205
644955ms       th_a   displayFailureInfo ] fatal error assert
other.my->_key != nullptr: 
    {}
    th_a  elliptic.cpp:439 get_shared_secret            KeyhoteeApplication.cpp:207

**Comment by vogel76** [comment]
Which KH instance has been used to create an email ? It was this one without identity created yet ?

**Comment by yuvarajgogoi** [comment]
yes

**Comment by vogel76** [comment]
This issue duplicates this one: https://github.com/InvictusInnovations/keyhotee/issues/131
