### ISSUE TITLE
inconsistent behavior of "DEL" key on CONTACTS of side_bar

### ISSUE THREAD

**Issue by yuvarajgogoi** [InvictusInnovations/keyhotee#218]
Steps to reproduce
1) select any contact on the contact list after show contact.
2) now select any contact on the CONTACTS of side_bar.
3) press "DEL"
4) deletion is fine
5) Now don't select any contact of the contact list (contacts_page)
6) select again select any contact on the CONTACTS of side_bar.
7) press DELETE.

Now deletion doesn't happen.

Tested on Ubuntu and is always reproducible

**Comment by PaulEU** [comment]
Fixed at rev:  https://github.com/InvictusInnovations/keyhotee/commit/8776fafa038fe3f8001f9975af5dc1d9358d2538  https://github.com/InvictusInnovations/keyhotee/commit/4edf0e29f4a461189bc5ad4a401930bdc29ce53e
