### ISSUE TITLE
user's profile can't be opened after src build of later version of keyhotee

### ISSUE THREAD

**Issue by dnotestein** [InvictusInnovations/keyhotee#224]
https://bitsharestalk.org/index.php?topic=1984.msg25394#msg25394
Maybe this is related to the keysym warning displayed near the top of his log?

**Comment by alexxy** [comment]
It's my issue. Also seems like its related to ipv6 (i have it @home) and dont have it using mobile wwan or work networks.

**Comment by dnotestein** [comment]
Alexxy, can you test and see if it occurs for you now with the latest source?

**Comment by alexxy** [comment]
Now it seems works. So you can close issue
