### ISSUE TITLE
in autocompletion of mail address in to_field, 2 suggestion are given for the same profile.

### ISSUE THREAD

**Issue by yuvarajgogoi** [InvictusInnovations/keyhotee#226]
Steps to reproduce
1) start client.
2) add a contact
3) In compose mail to_field try to write the contact's id.

Two suggestions are given for the same contact.

Same is the case for bcc and cc

Tested on Ubuntu and is always reproducible.

**Comment by vogel76** [comment]
This is an effect of functionality allowing to search through aliased names (concatenated AliasFn AliasLN) and kIDs. Maybe we should just filter out redundant texts (when such concatenated aliased name and kID are the same).

**Comment by yuvarajgogoi** [comment]
issue seen again

**Comment by PaulEU** [comment]
I just filter out redundant autocompletion (when aliased name and kID are the same) as suggested by vogel76.
I think the existing functionality is ok. 
We have autocompletion for kID and name.

**Comment by yuvarajgogoi** [comment]
Lets add simple a KHID but no last name and first name etc. Auto completion gives 2 suggestions. Is that ok?

**Comment by dnotestein** [comment]
I think having both suggestions is better. For one thing, the contact may not have a KeyhoteeID (sometimes the contact only has a first/last name and a public key).

**Comment by PaulEU** [comment]
I committed small fix: https://github.com/InvictusInnovations/keyhotee/commit/0172415ff04998e994c8a3d2b5558b0dd5682631
When KeyhoteeID is empty don't set empty suggestion.

**Comment by PaulEU** [comment]
Only one suggestion for the same contact but autocompletion works for fragments in the middle of a word https://github.com/InvictusInnovations/keyhotee/commit/5d323d7560a600a82f3e728df03016c33d2e7101
