### ISSUE TITLE
channel0 subdirectory created in current working directory

### ISSUE THREAD

**Issue by dnotestein** [InvictusInnovations/keyhotee#227]
Keyhotee attempts to create a channel0 subdirectory in the current working directory, regardless of what that directory is.  This is a mild nuisance when the user has write access to the current working directory.  When the user does not have write access to the current working directory (for example, /usr on a Linux system), my profile cannot be unlocked even when I enter the correct login password.

**Comment by vipjeffreylee** [comment]
ditto

**Comment by dnotestein** [comment]
Fixed in https://github.com/InvictusInnovations/BitShares/commit/6f60c79c631f73fd83f18305b888491d3ef65f71
