### ISSUE TITLE
Keyhotee Founder status is not updating during KH work

### ISSUE THREAD

**Issue by vogel76** [InvictusInnovations/keyhotee#229]
Previously, while mining has been enabled, Keyhotee founder status has been updated according to the Age associated to given kID. This is still done in the contact table part. Changing selection in this table caused to update lower view, so new data has been displayed. Nowadays it is impossible. kID founder status is not changing until application will be restarted.

**Comment by dnotestein** [comment]
This is just a side effect of registration reporting, since mining has been enabled for real use yet. Old functionality will be shortly restored in debug builds after Friday release.
