### ISSUE TITLE
Contacts list on the tree should contain the same elements as table of contacts

### ISSUE THREAD

**Issue by PaulEU** [InvictusInnovations/keyhotee#23]
Contacts list on the tree is empty after starting program.

**Comment by dnotestein** [comment]
The contacts list on the tree is not a full list of contacts, it is a list of "active contacts". Active in this context currently means someone who you have communicated with during the current program session via either chat or email. You can think of it as both a method for notifying users of new messages from contacts and a "recent contact" list.
