### ISSUE TITLE
Invalid kID/FounderKey pair & Keyhotee founder status displayed together

### ISSUE THREAD

**Issue by vogel76** [InvictusInnovations/keyhotee#230]
If I good understand it this makes non sense.
Below pasted image.
![bug](https://f.cloud.github.com/assets/6086581/1887001/46c1fef6-79f3-11e3-8fac-49caf2b741b9.png)

**Comment by alexxy** [comment]
Yeah. I have same one

**Comment by dnotestein** [comment]
This is an artifact of attempting to mine an id (mining doesn't really work right now). Mining in GUI should be disabled for now.

**Comment by vogel76** [comment]
Since mining option has been disabled temporary, I'm closing it.
