### ISSUE TITLE
Menu/Select command all should be dispatched to currently active view

### ISSUE THREAD

**Issue by vogel76** [InvictusInnovations/keyhotee#233]
This option should allow selection of all items depending on focused view. Of course it should not override standard command implemented ie inside QTextEdit/QLineEdit etc. 
As far as I analyzed it it should be handled especially:
- in mailbox view
- in contact table view

**Comment by PaulEU** [comment]
Fixed at rev: https://github.com/InvictusInnovations/keyhotee/commit/7d5ec0b866410eaaf1c6478600414fa8e88364ba
