### ISSUE TITLE
Show Keyhotee Founder Id's with a golden color in Address bars

### ISSUE THREAD

**Issue by dnotestein** [InvictusInnovations/keyhotee#24]
Keyhotee Founder Id's are users who purchased their name in the genesis block of the KeyhoteeId blockchain to help support our development efforts. These IDs will have an age of 1. Whenever these names are displayed in an email address bar, show them using a golden color instead of the default light blue color to indicate their special status.

**Comment by grzegorzs** [comment]
Added Keyhotee Founder Id's
- added fake function getAge()

9b59eb22157d49bab16af0998bd6ae004f8c0567
