### ISSUE TITLE
Compress messages prior to encrypting and sending message

### ISSUE THREAD

**Issue by dnotestein** [InvictusInnovations/keyhotee#241]
The compression should be done with the easylzma libary that is already incorporated into the Keyhotee project.

**Comment by dnotestein** [comment]
This should also eliminate most of the bloat from extra fields like the proposed hash code for chaining replied messages when they aren't needed, since the compression will mostly eliminate repeated 0s.

**Comment by dnotestein** [comment]
FC supports two compression types LZMA and short string compression. We probably want to have the code try each method, then select the one that works best, at runtime (of course that means encoding the compression method into the message, but they may do this already).

**Comment by grzegorzs** [comment]
Implemented lzma compression in fc InvictusInnovations/fc@8ad02176c67f7b866ced3befdea3f7b1aa63a0dc

Added compression, but required recompile the server application.
NOT working with current version of server. InvictusInnovations/BitShares@b107e39d35083f08ad141d4934a6a95bd6cfd5ab as new branch  compression_msg

**Comment by dnotestein** [comment]
Next step (in progress by Grzegorz) is to try both compression methods at runtime, then select whichever one compresses best.

**Comment by dnotestein** [comment]
In practice LZMA ended up always being better than SMAZ, as we're compressing several meta-data fields as well as the actual message, so closing out this issue.
