### ISSUE TITLE
Sometimes adding contact to the tree makes empty field (below image):

### ISSUE THREAD

**Issue by PaulEU** [InvictusInnovations/keyhotee#25]
![image](https://f.cloud.github.com/assets/6093796/1696028/a01d01f0-5ebc-11e3-8aea-f55ad0a0b321.png)

**Comment by dnotestein** [comment]
I guess this can happen if a contact is created that has an id, but a blank First/Last name. Is this the case here?

**Comment by PaulEU** [comment]
No. In this case empty field is mapping to "tom smith". I have just four contacts (no blank)
