### ISSUE TITLE
Implement Copy/Cut/Paste commands of menu edit

### ISSUE THREAD

**Issue by vogel76** [InvictusInnovations/keyhotee#250]
Handlers of such command should be delegated to currently active widget so best would be to implement/find some QT mechanism to do that.

**Comment by PaulEU** [comment]
Implemented in revs:
https://github.com/InvictusInnovations/keyhotee/commit/c328d088e4a02b14b3ffb13316287e7eeb28cce8
https://github.com/InvictusInnovations/keyhotee/commit/3570201a22ee18e74fc0d36cdc7a3474da2427c3
