### ISSUE TITLE
CmakeLists.txt has some error,I can't compile keyhotee in ubuntu 12.04.3

### ISSUE THREAD

**Issue by vipjeffreylee** [InvictusInnovations/keyhotee#251]
jeffrey@linux:~/Git/keyhotee/build$ cmake ..
-- Setting up additional QT Dependencies for Unix platform
-- XCB[XCB]: Found component XCB
-- Could NOT find XCB_COMPOSITE (missing:  XCB_COMPOSITE_LIBRARY XCB_COMPOSITE_INCLUDE_DIR) 
-- Could NOT find XCB_DAMAGE (missing:  XCB_DAMAGE_LIBRARY XCB_DAMAGE_INCLUDE_DIR) 
-- Could NOT find XCB_DRI2 (missing:  XCB_DRI2_LIBRARY XCB_DRI2_INCLUDE_DIR) 
-- Could NOT find XCB_EWMH (missing:  XCB_EWMH_LIBRARY XCB_EWMH_INCLUDE_DIR) 
-- Could NOT find XCB_GLX (missing:  XCB_GLX_LIBRARY XCB_GLX_INCLUDE_DIR) 
-- Could NOT find XCB_ICCCM (missing:  XCB_ICCCM_LIBRARY XCB_ICCCM_INCLUDE_DIR) 
-- Could NOT find XCB_IMAGE (missing:  XCB_IMAGE_LIBRARY XCB_IMAGE_INCLUDE_DIR) 
-- Could NOT find XCB_KEYSYMS (missing:  XCB_KEYSYMS_LIBRARY XCB_KEYSYMS_INCLUDE_DIR) 
-- Could NOT find XCB_RANDR (missing:  XCB_RANDR_LIBRARY XCB_RANDR_INCLUDE_DIR) 
-- Could NOT find XCB_RENDER (missing:  XCB_RENDER_LIBRARY XCB_RENDER_INCLUDE_DIR) 
-- Could NOT find XCB_RENDERUTIL (missing:  XCB_RENDERUTIL_LIBRARY XCB_RENDERUTIL_INCLUDE_DIR) 
-- Could NOT find XCB_SHAPE (missing:  XCB_SHAPE_LIBRARY XCB_SHAPE_INCLUDE_DIR) 
-- Could NOT find XCB_SHM (missing:  XCB_SHM_LIBRARY XCB_SHM_INCLUDE_DIR) 
-- Could NOT find XCB_SYNC (missing:  XCB_SYNC_LIBRARY XCB_SYNC_INCLUDE_DIR) 
-- Could NOT find XCB_UTIL (missing:  XCB_UTIL_LIBRARY XCB_UTIL_INCLUDE_DIR) 
-- Could NOT find XCB_XFIXES (missing:  XCB_XFIXES_LIBRARY XCB_XFIXES_INCLUDE_DIR) 
-- Could NOT find XCB_XTEST (missing:  XCB_XTEST_LIBRARY XCB_XTEST_INCLUDE_DIR) 
-- Could NOT find XCB_XV (missing:  XCB_XV_LIBRARY XCB_XV_INCLUDE_DIR) 
-- Could NOT find X11_XCB (missing:  X11_XCB_LIBRARIES X11_XCB_INCLUDE_DIR) 
-- Could NOT find Freetype (missing:  FREETYPE_LIBRARY FREETYPE_INCLUDE_DIRS) 
-- Some or all of the gtk libraries were not found. (missing:  GTK2_GTK_LIBRARY GTK2_GTK_INCLUDE_DIR GTK2_GDK_INCLUDE_DIR GTK2_GDKCONFIG_INCLUDE_DIR GTK2_GDK_LIBRARY) 
/home/jeffrey/Git/keyhotee/BitShares
-- Using invictus root: ./
-- Compiling on UNIX
-- Boost version: 1.54.0
-- Found the following Boost libraries:
--   thread
--   date_time
--   system
--   filesystem
--   program_options
--   signals
--   serialization
--   chrono
--   unit_test_framework
--   context
--   coroutine
CMake Warning at BitShares/CMakeLists.txt:19 (FIND_PACKAGE):
  By not providing "FindBerkeleyDB.cmake" in CMAKE_MODULE_PATH this project
  has asked CMake to find a package configuration file provided by
  "BerkeleyDB", but CMake did not find one.

  Could not find a package configuration file provided by "BerkeleyDB" with
  any of the following names:

```
BerkeleyDBConfig.cmake
berkeleydb-config.cmake
```

  Add the installation prefix of "BerkeleyDB" to CMAKE_PREFIX_PATH or set
  "BerkeleyDB_DIR" to a directory containing one of the above files.  If
  "BerkeleyDB" provides a separate development package or SDK, be sure it has
  been installed.

statusCompiling on UNIX
-- Boost version: 1.54.0
-- Found the following Boost libraries:
--   thread
--   date_time
--   system
--   filesystem
--   program_options
--   signals
--   serialization
--   chrono
--   unit_test_framework
--   context
--   coroutine
-- Boost version: 1.54.0
-- Found the following Boost libraries:
--   thread
--   date_time
--   system
--   filesystem
--   program_options
--   signals
--   serialization
--   chrono
--   unit_test_framework
--   context
BOOST_LIBRARIES=/usr/local/lib/libboost_thread.a/usr/local/lib/libboost_system.a/usr/local/lib/libboost_filesystem.a/usr/local/lib/libboost_date_time.a/usr/local/lib/libboost_chrono.a/usr/lib/x86_64-linux-gnu/libssl.so/usr/lib/x86_64-linux-gnu/libcrypto.so/usr/local/lib/libboost_coroutine.a/usr/local/lib/libboost_context.apthread
CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
FONTCONFIG_LIBRARY
    linked by target "Keyhotee" in directory /home/jeffrey/Git/keyhotee
FREETYPE_LIBRARY (ADVANCED)
    linked by target "Keyhotee" in directory /home/jeffrey/Git/keyhotee
QXcbStatic_LIBRARY
    linked by target "Keyhotee" in directory /home/jeffrey/Git/keyhotee
X11_ICE_LIB (ADVANCED)
    linked by target "Keyhotee" in directory /home/jeffrey/Git/keyhotee
X11_SM_LIB (ADVANCED)
    linked by target "Keyhotee" in directory /home/jeffrey/Git/keyhotee
X11_XCB_LIBRARIES (ADVANCED)
    linked by target "Keyhotee" in directory /home/jeffrey/Git/keyhotee
X11_Xi_LIB (ADVANCED)
    linked by target "Keyhotee" in directory /home/jeffrey/Git/keyhotee
X11_Xrender_LIB (ADVANCED)
    linked by target "Keyhotee" in directory /home/jeffrey/Git/keyhotee
XCB_GLX_LIBRARY (ADVANCED)
    linked by target "Keyhotee" in directory /home/jeffrey/Git/keyhotee

-- Configuring incomplete, errors occurred!
jeffrey@linux:~/Git/keyhotee/build$ clear

jeffrey@linux:~/Git/keyhotee/build$ cmake ..
-- Setting up additional QT Dependencies for Unix platform
-- XCB[XCB]: Found component XCB
-- Could NOT find XCB_COMPOSITE (missing:  XCB_COMPOSITE_LIBRARY XCB_COMPOSITE_INCLUDE_DIR) 
-- Could NOT find XCB_DAMAGE (missing:  XCB_DAMAGE_LIBRARY XCB_DAMAGE_INCLUDE_DIR) 
-- Could NOT find XCB_DRI2 (missing:  XCB_DRI2_LIBRARY XCB_DRI2_INCLUDE_DIR) 
-- Could NOT find XCB_EWMH (missing:  XCB_EWMH_LIBRARY XCB_EWMH_INCLUDE_DIR) 
-- Could NOT find XCB_GLX (missing:  XCB_GLX_LIBRARY XCB_GLX_INCLUDE_DIR) 
-- Could NOT find XCB_ICCCM (missing:  XCB_ICCCM_LIBRARY XCB_ICCCM_INCLUDE_DIR) 
-- Could NOT find XCB_IMAGE (missing:  XCB_IMAGE_LIBRARY XCB_IMAGE_INCLUDE_DIR) 
-- Could NOT find XCB_KEYSYMS (missing:  XCB_KEYSYMS_LIBRARY XCB_KEYSYMS_INCLUDE_DIR) 
-- Could NOT find XCB_RANDR (missing:  XCB_RANDR_LIBRARY XCB_RANDR_INCLUDE_DIR) 
-- Could NOT find XCB_RENDER (missing:  XCB_RENDER_LIBRARY XCB_RENDER_INCLUDE_DIR) 
-- Could NOT find XCB_RENDERUTIL (missing:  XCB_RENDERUTIL_LIBRARY XCB_RENDERUTIL_INCLUDE_DIR) 
-- Could NOT find XCB_SHAPE (missing:  XCB_SHAPE_LIBRARY XCB_SHAPE_INCLUDE_DIR) 
-- Could NOT find XCB_SHM (missing:  XCB_SHM_LIBRARY XCB_SHM_INCLUDE_DIR) 
-- Could NOT find XCB_SYNC (missing:  XCB_SYNC_LIBRARY XCB_SYNC_INCLUDE_DIR) 
-- Could NOT find XCB_UTIL (missing:  XCB_UTIL_LIBRARY XCB_UTIL_INCLUDE_DIR) 
-- Could NOT find XCB_XFIXES (missing:  XCB_XFIXES_LIBRARY XCB_XFIXES_INCLUDE_DIR) 
-- Could NOT find XCB_XTEST (missing:  XCB_XTEST_LIBRARY XCB_XTEST_INCLUDE_DIR) 
-- Could NOT find XCB_XV (missing:  XCB_XV_LIBRARY XCB_XV_INCLUDE_DIR) 
-- Could NOT find X11_XCB (missing:  X11_XCB_LIBRARIES X11_XCB_INCLUDE_DIR) 
-- Could NOT find Freetype (missing:  FREETYPE_LIBRARY FREETYPE_INCLUDE_DIRS) 
-- Some or all of the gtk libraries were not found. (missing:  GTK2_GTK_LIBRARY GTK2_GTK_INCLUDE_DIR GTK2_GDK_INCLUDE_DIR GTK2_GDKCONFIG_INCLUDE_DIR GTK2_GDK_LIBRARY) 
/home/jeffrey/Git/keyhotee/BitShares
-- Using invictus root: ./
-- Compiling on UNIX
-- Boost version: 1.54.0
-- Found the following Boost libraries:
--   thread
--   date_time
--   system
--   filesystem
--   program_options
--   signals
--   serialization
--   chrono
--   unit_test_framework
--   context
--   coroutine
CMake Warning at BitShares/CMakeLists.txt:19 (FIND_PACKAGE):
  By not providing "FindBerkeleyDB.cmake" in CMAKE_MODULE_PATH this project
  has asked CMake to find a package configuration file provided by
  "BerkeleyDB", but CMake did not find one.

  Could not find a package configuration file provided by "BerkeleyDB" with
  any of the following names:

```
BerkeleyDBConfig.cmake
berkeleydb-config.cmake
```

  Add the installation prefix of "BerkeleyDB" to CMAKE_PREFIX_PATH or set
  "BerkeleyDB_DIR" to a directory containing one of the above files.  If
  "BerkeleyDB" provides a separate development package or SDK, be sure it has
  been installed.

statusCompiling on UNIX
-- Boost version: 1.54.0
-- Found the following Boost libraries:
--   thread
--   date_time
--   system
--   filesystem
--   program_options
--   signals
--   serialization
--   chrono
--   unit_test_framework
--   context
--   coroutine
-- Boost version: 1.54.0
-- Found the following Boost libraries:
--   thread
--   date_time
--   system
--   filesystem
--   program_options
--   signals
--   serialization
--   chrono
--   unit_test_framework
--   context
BOOST_LIBRARIES=/usr/local/lib/libboost_thread.a/usr/local/lib/libboost_system.a/usr/local/lib/libboost_filesystem.a/usr/local/lib/libboost_date_time.a/usr/local/lib/libboost_chrono.a/usr/lib/x86_64-linux-gnu/libssl.so/usr/lib/x86_64-linux-gnu/libcrypto.so/usr/local/lib/libboost_coroutine.a/usr/local/lib/libboost_context.apthread
CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
FONTCONFIG_LIBRARY
    linked by target "Keyhotee" in directory /home/jeffrey/Git/keyhotee
FREETYPE_LIBRARY (ADVANCED)
    linked by target "Keyhotee" in directory /home/jeffrey/Git/keyhotee
QXcbStatic_LIBRARY
    linked by target "Keyhotee" in directory /home/jeffrey/Git/keyhotee
X11_ICE_LIB (ADVANCED)
    linked by target "Keyhotee" in directory /home/jeffrey/Git/keyhotee
X11_SM_LIB (ADVANCED)
    linked by target "Keyhotee" in directory /home/jeffrey/Git/keyhotee
X11_XCB_LIBRARIES (ADVANCED)
    linked by target "Keyhotee" in directory /home/jeffrey/Git/keyhotee
X11_Xi_LIB (ADVANCED)
    linked by target "Keyhotee" in directory /home/jeffrey/Git/keyhotee
X11_Xrender_LIB (ADVANCED)
    linked by target "Keyhotee" in directory /home/jeffrey/Git/keyhotee
XCB_GLX_LIBRARY (ADVANCED)
    linked by target "Keyhotee" in directory /home/jeffrey/Git/keyhotee

-- Configuring incomplete, errors occurred!

**Comment by vogel76** [comment]
As for X11, XCB, GTK libraries you should install proper development packages (e.g. libgtk2.0-dev, libfreetype6-dev
libreadline-dev).
QT should be linked statically. In keyhotee project is script build_qt.sh to compile QT 5.2 as static libraries.

**Comment by vogel76** [comment]
Hi, do you have still these build problems ?

**Comment by vipjeffreylee** [comment]
I modified SET(KH_STATIC_QT 1) to SET(KH_STATIC_QT 0), to solve this problem temporarily

**Comment by vogel76** [comment]
In current version you can pass -DKH_STATIC_QT=0 to the cmake commandline and this setting should be honored by build script. So I think you will not need to modify CmakeLists.txt in KH project. If this is acceptable solution for you please close the issue. If you still would like to build KH in static configuration (which really mostly make sense on our builder where we're doing public releases) you have to configure your machine and build QT, ICU, BerkeleyDb libs statically. keyhotee project contains some scripts to simplify it
