### ISSUE TITLE
Automatic download of linked images (into messages) should be disabled to Improve security

### ISSUE THREAD

**Issue by vogel76** [InvictusInnovations/keyhotee#256]
Right now message containing a link to an image tries to display it. This allows to identity some mail message receiver by sender by putting prepared link into message. As other programs does, images in the email should be loaded on demand - probably some option on the toolbar should be added,

**Comment by PaulEU** [comment]
Supporting load remote images into mail messages (Caching web page images)
de044760a11c7351b3129e0d5cd0e6942d998afd
