### ISSUE TITLE
crash from menu->help->about

### ISSUE THREAD

**Issue by pch957** [InvictusInnovations/keyhotee#257]
the _currentWidget(window about) had destroyed, but be called after

void MenuEditControl::setEnabled(QWidget *old, QWidget *now)
{  
  bool selectedText = false;

  selectedText = isSelected(now);
  _actionCopy->setEnabled(selectedText);
  _actionCut->setEnabled(selectedText);

  if (now == nullptr)
    return;

  if (now != _currentWidget)
  {
    connectSelectionChangedSignal(false, _currentWidget);

**Comment by PaulEU** [comment]
I can't generate this situation in the last commit.
Could you write steps how I can duplicate this. Where clicks ? What sequence ?

**Comment by vogel76** [comment]
Bug has been reproduced and it will be solved soon I hope.
