### ISSUE TITLE
Please do testing current linux release on various linux platform if possible

### ISSUE THREAD

**Issue by vogel76** [InvictusInnovations/keyhotee#262]
Prebuilt package can be downloaded from:
http://get.syncad.com/invictus/Keyhotee.gz

**Comment by yaago** [comment]
Tried and registered a founder ID,  _seems_ to work.

Linux Mint 13 (maya) MATE 64-bit

Registering other ID, it says "Unregistered". Also 0 connections to BitShares network. Should I open some port on the router?

Please send me a message: 6nXWdszeCWhzqTqYEVmk1Ri1xmF8TioTLNEGTiUo8FkrqYKFuC (yago)
