### ISSUE TITLE
crash on saving message after attaching  file 

### ISSUE THREAD

**Issue by yuvarajgogoi** [InvictusInnovations/keyhotee#272]
Step to reproduce
1) create new Message(Compose)
2) attach a  file
3) save the message.

crash is seen

Tested on Ubuntu 13.10 and is always reproducible

log : 
1596628ms       th_a              startup ] .           KeyhoteeApplication.cpp:286
1596628ms       th_a         get_profiles ] /home/yuvaraj/.local/share/Keyhotee/profiles/Y G            application.cpp:376
1596628ms       th_a         get_profiles ] /home/yuvaraj/.local/share/Keyhotee/profiles/J G            application.cpp:376
1596628ms       th_a         get_profiles ] profiles ["Y G","J G"]          application.cpp:383
1596629ms       th_a         displayLogin ] .           KeyhoteeApplication.cpp:216
1596648ms       th_a         get_profiles ] /home/yuvaraj/.local/share/Keyhotee/profiles/Y G            application.cpp:376
1596648ms       th_a         get_profiles ] /home/yuvaraj/.local/share/Keyhotee/profiles/J G            application.cpp:376
1596648ms       th_a         get_profiles ] profiles ["Y G","J G"]          application.cpp:383
1596648ms       th_a          LoginDialog ] profiles Y G            LoginDialog.cpp:34
1596648ms       th_a          LoginDialog ] profiles J G            LoginDialog.cpp:34
1602605ms       th_a                 open ] opening profile: /home/yuvaraj/.local/share/Keyhotee/profiles/J G           profile.cpp:99
1602606ms       th_a                 open ] loading master key file:.keyhotee_master.key            profile.cpp:112
1602606ms       th_a                 open ] opening profile databases           profile.cpp:124
1602722ms       th_a                 open ] loading contact {"public_key":"021851c53c066b766576d38f6f75771d30e54b4df57b07110ede5a101b0c4fc8d9","dac_id_hash":8980070599008415687,"dac_id_string":"j","properties":[],"wallet_index":0,"privacy_setting":"secret_contact","first_name":"","last_name":"","icon_png":"","notes":"","next_send_trx_id":0,"send_trx_address":{"pub_key":"000000000000000000000000000000000000000000000000000000000000000000","chain_code":"0000000000000000000000000000000000000000000000000000000000000000"},"bitchat_recv_channels":[],"bitchat_broadcast_channels":[],"bitchat_recv_broadcast_key":"0000000000000000000000000000000000000000000000000000000000000000"}           addressbook.cpp:58
1602723ms       th_a                 open ] loading contact {"public_key":"03e899ed05be25a7923d6edbf49ddf6ffa493233f709fd7d09c9a1f4b19464d283","dac_id_hash":0,"dac_id_string":"y","properties":[],"wallet_index":1,"privacy_setting":"secret_contact","first_name":"","last_name":"","icon_png":"89504e470d0a1a0a0000000d4948445200000020000000200806000000737a7af4000000097048597300000ec400000ec401952b0e1b00000392494441545885c5565d685c45183ddf7767eedd9b266977d3ba9a606ab0d522be2885405bd0a850a48a2fcd922294f8d2580a0505695f24e44d057df1a969f1af08765350b10f0afe2315a38896a0fd71355ada1a4d03d5cdeebd77ef9dcf871aec9add6476b3a51fcccb70e69c33e7ce7c77801b5cd4cca23d3f84f7926090c46c0200213e2d8489f1bbbc6fafab81c7cf4aa71704e34cc8d5582b46900f53a93d6fde417fb5dcc0e049f15dbffc0913fa97c219c15751d91f98d842651b5eb63500af381619d31f24064b8dc8987e78c5315b5aab04b67cf1674797eb5d24a0dd062f40f17214769fdcb6eeefe5b0ca86d067bd358c8d95f8bfd5eeb3de0ae0fd96188812e9214803fa80807a6c705606ca1553646ecc80212ab6cc40548926855988c8eacc88889071276db0d6d770e307331f12f0a09501e0a373dbb30fd960ad1200803049f6433009a2554babcb3c08fb6d791bea84d977cf3f00e2091032b5c531073183338fddfaf1753100006d277eb9d98b9d0302de49909eabba7481608e872a79bef448dfef8df0597f82852a7d3d3d5beaee7e0bc06952b40102124101b139052e5e6e94cf3e81c3852c91799a140f43d34d60fa8f41001801123327091d95927911fb369e6f99013e7c762f7bce73e43a9d6000f56ea3082080c4a68404a371e1f5973036669a37909f72dd79ff35f29d5d70c83eaf85442ae6bd707e6e08239b4b8d1b38f48d4ef999b739e5ec80d3d4bb05108144c9a7e5901ec6137d412d48dddf719b9f7e59fb6a87a3180e51738319ca53f7b7b7f1abf5746a6e6dd5d19f73da57c748513d4843254620b119b9925b3fbeac81f4a1c26aa4f519c7e3ec8a95ab4d5c2957e24da55c759f58d40738ad9f511e678957bef36a625aed907ab604ecbb76ba4aa5ebc88f1deeda8edf58f19ad6aa5f2d01ca89a6db66b6dff2c7c25c5502a9b59d434ad39abaf77ca5068cf81c9861002fd434a05df52b1b131053aa0567efffe2a844663a367cecdaf94532ebdfb934a0148e2b4519cbf7c7d2c20be241f27d18941ebdb8abba45d754e8cd4ff779befb86d2ce3676a8a9300400441057c444417c2498a5a72e8df42cea88f5b9474779c33d4f0e6b4da35a732f3160958800228224164491f9322a570e4e0ff57e5e0fbe3c637ecabd53a7776acdbbd9e1fb1c4529225a744e4500930892d8ccc5b19ca88495577ecaf57eb61c7d43e9aecb4fb56774d766877137446e274627091901cd9a44ce4562be2b64ba4f6180e246786f68fd0376596dac58d6da930000000049454e44ae426082","notes":"","next_send_trx_id":0,"send_trx_address":{"pub_key":"000000000000000000000000000000000000000000000000000000000000000000","chain_code":"0000000000000000000000000000000000000000000000000000000000000000"},"bitchat_recv_channels":[],"bitchat_broadcast_channels":[],"bitchat_recv_broadcast_key":"0000000000000000000000000000000000000000000000000000000000000000"}         addressbook.cpp:58
1603713ms       th_a                 open ] finished opening profile            profile.cpp:138
1603714ms       th_a            configure ] application::configure          application.cpp:212
1603714ms       th_a            configure ] calling get_external_ip         application.cpp:219
1603714ms       th_a      get_external_ip ] resolve ipecho.net port 80          ipecho.cpp:20
1605275ms       th_a      get_external_ip ] ip line=106.51.148.224
            ipecho.cpp:44
1605275ms       th_a            configure ] external IP 106.51.148.224          application.cpp:221
1605276ms       th_a            configure ] set_external_ip         application.cpp:230
1605276ms       th_a            configure ] configuring server          application.cpp:243
1605276ms       th_a            configure ] listening for stcp connections on port 10876            server.cpp:207
1605276ms       th_a            configure ] configure bitname client            application.cpp:249
1605581ms       th_a         load_indexes ] load indexes            bitname_db.cpp:92
1605581ms       th_a         load_indexes ] load indexes            bitname_db.cpp:107
1605584ms       th_a      init_timekeeper ] ...init stats...            bitname_db.cpp:162
1605584ms       th_a      init_timekeeper ] ...done init timekeeper...          bitname_db.cpp:164
1605584ms       th_a                 open ] open name db            bitname_db.cpp:214
1606247ms       th_a            configure ] configure bitchat client            application.cpp:259
1606458ms       th_a            configure ] configuring rpc_server          application.cpp:263
1606458ms       th_a            configure ] listening for rpc connections on port 10877         rpc_server.cpp:245
1606459ms       th_a            configure ] listening for rpc connections on port 10877         rpc_server.cpp:247
1606459ms       th_a            configure ] done configuring rpc_server         application.cpp:266
1606459ms       th_a            configure ] end application::configure          application.cpp:268
1606597ms       th_a       reloadContacts ] loading contacts...         AddressBookModel.cpp:356
1606598ms       th_a       reloadContacts ] loading contacts...         AddressBookModel.cpp:356
1606616ms       th_a   KeyhoteeMainWindow ] idents: [{"public_key":"021851c53c066b766576d38f6f75771d30e54b4df57b07110ede5a101b0c4fc8d9","dac_id_hash":8980070599008415687,"dac_id_string":"j","properties":[],"wallet_ident":"j","mining_effort":1,"first_name":"","last_name":"","private_icon_png":""}]           KeyhoteeMainWindow.cpp:272
1606628ms       th_a start_mail_connect_l ] start_mail_connect_loop         application.cpp:154
1606629ms       th_a         connect_loop ] 127.0.0.1:9876          application.cpp:108
1606629ms       th_a           connect_to ] connect to 127.0.0.1:9876           server.cpp:244
1606631ms       th_a              connect ]     connected to 127.0.0.1:9876         connection.cpp:192
1606631ms       th_a         on_connected ] on connected...         peer_channel.cpp:162
1606631ms       th_a     handle_subscribe ] 127.0.0.1:9876: {"channels":[{"proto":"chat_proto","chan":0},{"proto":"name_proto","chan":0},{"proto":"peer_proto","chan":0}]}          peer_channel.cpp:339
1606631ms       th_a request_block_header ] requesting block headers from 127.0.0.1:9876            bitname_channel.cpp:498
1606631ms       th_a       handle_message ] get_headers_msg         bitname_channel.cpp:444
1606631ms       th_a       handle_message ] headers_msg         bitname_channel.cpp:444
1606631ms       th_a       handle_headers ] received ${x} block headers         bitname_channel.cpp:727
1609631ms       th_a         connect_loop ] 127.0.0.1:9876          application.cpp:108
1609631ms       th_a           connect_to ] connect to 127.0.0.1:9876           server.cpp:244
1609632ms       th_a           connect_to ] already connected to 127.0.0.1:9876         server.cpp:248
1611630ms       th_a    mail_connect_loop ] mail connect 162.243.67.4:7896          application.cpp:80
1611631ms       th_a              connect ] connect to 162.243.67.4:7896 and resolved ["162.243.67.4:7896"]         mail_connection.cpp:208
1612091ms       th_a              connect ]     connected to 162.243.67.4:7896          mail_connection.cpp:199
1612632ms       th_a         connect_loop ] 127.0.0.1:9876          application.cpp:108
1612632ms       th_a           connect_to ] connect to 127.0.0.1:9876           server.cpp:244
1612632ms       th_a           connect_to ] already connected to 127.0.0.1:9876         server.cpp:248
1615633ms       th_a         connect_loop ] 127.0.0.1:9876          application.cpp:108
1615633ms       th_a           connect_to ] connect to 127.0.0.1:9876           server.cpp:244
1615634ms       th_a           connect_to ] already connected to 127.0.0.1:9876         server.cpp:248
1618634ms       th_a         connect_loop ] 127.0.0.1:9876          application.cpp:108
1618634ms       th_a           connect_to ] connect to 127.0.0.1:9876           server.cpp:244
1618635ms       th_a           connect_to ] already connected to 127.0.0.1:9876         server.cpp:248
1621635ms       th_a         connect_loop ] 127.0.0.1:9876          application.cpp:108
1621635ms       th_a           connect_to ] connect to 127.0.0.1:9876           server.cpp:244
1621635ms       th_a           connect_to ] already connected to 127.0.0.1:9876         server.cpp:248
1624636ms       th_a         connect_loop ] 127.0.0.1:9876          application.cpp:108
1624636ms       th_a           connect_to ] connect to 127.0.0.1:9876           server.cpp:244
1624636ms       th_a           connect_to ] already connected to 127.0.0.1:9876         server.cpp:248
1627637ms       th_a         connect_loop ] 127.0.0.1:9876          application.cpp:108
1627637ms       th_a           connect_to ] connect to 127.0.0.1:9876           server.cpp:244
1627637ms       th_a           connect_to ] already connected to 127.0.0.1:9876         server.cpp:248
1630637ms       th_a         connect_loop ] 127.0.0.1:9876          application.cpp:108
1630638ms       th_a           connect_to ] connect to 127.0.0.1:9876           server.cpp:244
1630638ms       th_a           connect_to ] already connected to 127.0.0.1:9876         server.cpp:248
1633638ms       th_a         connect_loop ] 127.0.0.1:9876          application.cpp:108
1633638ms       th_a           connect_to ] connect to 127.0.0.1:9876           server.cpp:244
1633639ms       th_a           connect_to ] already connected to 127.0.0.1:9876         server.cpp:248
1636639ms       th_a         connect_loop ] 127.0.0.1:9876          application.cpp:108
1636639ms       th_a           connect_to ] connect to 127.0.0.1:9876           server.cpp:244
1636639ms       th_a           connect_to ] already connected to 127.0.0.1:9876         server.cpp:248
1639640ms       th_a         connect_loop ] 127.0.0.1:9876          application.cpp:108
1639640ms       th_a           connect_to ] connect to 127.0.0.1:9876           server.cpp:244
1639640ms       th_a           connect_to ] already connected to 127.0.0.1:9876         server.cpp:248
1642640ms       th_a         connect_loop ] 127.0.0.1:9876          application.cpp:108
1642641ms       th_a           connect_to ] connect to 127.0.0.1:9876           server.cpp:244
1642641ms       th_a           connect_to ] already connected to 127.0.0.1:9876         server.cpp:248
1645641ms       th_a         connect_loop ] 127.0.0.1:9876          application.cpp:108
1646774ms       th_a           connect_to ] connect to 127.0.0.1:9876           server.cpp:244
1646774ms       th_a           connect_to ] already connected to 127.0.0.1:9876         server.cpp:248
1649774ms       th_a         connect_loop ] 127.0.0.1:9876          application.cpp:108
1649774ms       th_a           connect_to ] connect to 127.0.0.1:9876           server.cpp:244
1649774ms       th_a           connect_to ] already connected to 127.0.0.1:9876         server.cpp:248
1654205ms       th_a              decrypt ] we passed checksum test... unpack message..         bitchat_private_message.cpp:49
1656364ms       th_a   displayFailureInfo ] assert
size.value < MAX_ARRAY_ALLOC_SIZE: 
    {}
    th_a  raw.hpp:135 unpack
error decrypting message
    {}
    th_a  bitchat_private_message.cpp:62 decrypt            KeyhoteeApplication.cpp:259
1656364ms       th_a   displayFailureInfo ] fatal error assert
size.value < MAX_ARRAY_ALLOC_SIZE: 
    {}
    th_a  raw.hpp:135 unpack
error decrypting message
    {}
    th_a  bitchat_private_message.cpp:62 decrypt            KeyhoteeApplication.cpp:261

**Comment by vogel76** [comment]
It looks like we need to add check against max. message size also before saving a message.
