### ISSUE TITLE
attachment of files are possible even of  inbox mails.

### ISSUE THREAD

**Issue by yuvarajgogoi** [InvictusInnovations/keyhotee#278]
Steps to reproduce
1) Open a inbox mail by double click.
2) drag and drop file to the mail attachment widget.
3) Attachment works fine.
4) Clicking on save button leads to crash also.

Tested on Ubuntu 13.10 and is always reproducible.

**Comment by vogel76** [comment]
Looks like drag & drop/clipboard operations doesn't check read only flag.
