### ISSUE TITLE
Keyhotee window resizes to bigger window than the screen on selecting a mail with huge content or subject.

### ISSUE THREAD

**Issue by yuvarajgogoi** [InvictusInnovations/keyhotee#289]
Steps to reproduce
1) Select a message containing huge contents.
2) The Keyhotee main Window resizes to its content. So for huge content it resizes more than the monitor screen which becomes awefull to manage.

Tested on Ubuntu 13.10 and is always reproducible.

**Comment by yuvarajgogoi** [comment]
Issue also seen in this scenario:
1) open KH. 
2) send a mail to itself containing long subject line say 1000 letters. 
3) In inbox select this subjectline .... 

KH resizes to a very big window, the breath of the window becomes much more than the display monitor screen.

Tested on Debian

**Comment by vogel76** [comment]
There was set size limit for the max size. please take a look why it again won't work.
