### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by CourtJesterG** [InvictusInnovations/keyhotee#296]
I understand from watching the Keyhotee video on youtube how it works, yet what about all the information that has already been collected in the database of others with our accounts that we currently have? I mean are we to kinda make a new accounts? Kinda not following on that part. I mean Keyhotee communicates for us. Someone explain further please thanks.

**Comment by bytemaster** [comment]
Keyhotee can only help when it is used and is not much use to protect the information that has already leaked out into the world about you.
