### ISSUE TITLE
crash seen on selecting a contact after adding it by public key(in a specific scenario)

### ISSUE THREAD

**Issue by yuvarajgogoi** [InvictusInnovations/keyhotee#316]
Steps to reproduce:
1) Start 2 clients 
2) create an identity in 1 client.
3) enable mining.
4) create more identies in th same client.
5) delete the first created identity.
6) now add this first created identity by public key as New contact(since enabling mining will store this in block chain) 
7) Now close the client.
8) again open this same profile.
9) In contact list select the contact that is added by public key(step 6)

Crash is seen

Tested in Ubuntu and is always reproducible.

2951707ms       th_a              startup ] .           KeyhoteeApplication.cpp:286
2951707ms       th_a         get_profiles ] /home/yuvaraj/.local/share/Keyhotee/profiles/Y G            application.cpp:384
2951707ms       th_a         get_profiles ] /home/yuvaraj/.local/share/Keyhotee/profiles/J G            application.cpp:384
2951707ms       th_a         get_profiles ] profiles ["Y G","J G"]          application.cpp:391
2951707ms       th_a         displayLogin ] .           KeyhoteeApplication.cpp:216
2951720ms       th_a         get_profiles ] /home/yuvaraj/.local/share/Keyhotee/profiles/Y G            application.cpp:384
2951721ms       th_a         get_profiles ] /home/yuvaraj/.local/share/Keyhotee/profiles/J G            application.cpp:384
2951721ms       th_a         get_profiles ] profiles ["Y G","J G"]          application.cpp:391
2951721ms       th_a          LoginDialog ] profiles Y G            LoginDialog.cpp:42
2951721ms       th_a          LoginDialog ] profiles J G            LoginDialog.cpp:42
2959092ms       th_a                 open ] opening profile: /home/yuvaraj/.local/share/Keyhotee/profiles/J G           profile.cpp:103
2959092ms       th_a                 open ] loading master key file:.keyhotee_master.key            profile.cpp:116
2959093ms       th_a                 open ] opening profile databases           profile.cpp:128
2959094ms       th_a              onLogin ] error db_in_use
Unable to open database /home/yuvaraj/.local/share/Keyhotee/profiles/J G/addressbook/contact_db
    IO error: lock /home/yuvaraj/.local/share/Keyhotee/profiles/J G/addressbook/contact_db/LOCK: Resource temporarily unavailable
    {"db":"/home/yuvaraj/.local/share/Keyhotee/profiles/J G/addressbook/contact_db","msg":"IO error: lock /home/yuvaraj/.local/share/Keyhotee/profiles/J G/addressbook/contact_db/LOCK: Resource temporarily unavailable"}
    th_a  level_pod_map.hpp:44 open

```
{"directory":"/home/yuvaraj/.local/share/Keyhotee/profiles/J G/addressbook"}
th_a  addressbook.cpp:71 open

{"profile_dir":"/home/yuvaraj/.local/share/Keyhotee/profiles/J G"}
th_a  profile.cpp:143 open

{}
th_a  application.cpp:313 loadProfile           LoginDialog.cpp:74
```

2968018ms       th_a                 open ] opening profile: /home/yuvaraj/.local/share/Keyhotee/profiles/Y G           profile.cpp:103
2968018ms       th_a                 open ] loading master key file:.keyhotee_master.key            profile.cpp:116
2968019ms       th_a                 open ] opening profile databases           profile.cpp:128
2968159ms       th_a UpgradeDbIfNecessary ] Database /home/yuvaraj/.local/share/Keyhotee/profiles/Y G/addressbook/contact_db is not upgradeable         upgrade_leveldb.cpp:24
2968159ms       th_a                 open ] loading contact {"public_key":"039f346b679bb39c0014b90f34ac8ec02de39c384a0d6e18904454355fb994c358","dac_id_hash":3063318953795315473,"dac_id_string":"hhh","properties":[],"wallet_index":1,"privacy_setting":"secret_contact","first_name":"","last_name":"","icon_png":"","notes":"","next_send_trx_id":0,"send_trx_address":{"pub_key":"000000000000000000000000000000000000000000000000000000000000000000","chain_code":"0000000000000000000000000000000000000000000000000000000000000000"},"bitchat_recv_channels":[],"bitchat_broadcast_channels":[],"bitchat_recv_broadcast_key":"0000000000000000000000000000000000000000000000000000000000000000"}         addressbook.cpp:59
2968160ms       th_a                 open ] loading contact {"public_key":"02ed7ab452510c60f070a2c154596140b0ac4cbaaded1ceed19bfe69b835290d01","dac_id_hash":16821335187958279111,"dac_id_string":"hhgjhjgh","properties":[],"wallet_index":2,"privacy_setting":"secret_contact","first_name":"","last_name":"","icon_png":"","notes":"","next_send_trx_id":0,"send_trx_address":{"pub_key":"000000000000000000000000000000000000000000000000000000000000000000","chain_code":"0000000000000000000000000000000000000000000000000000000000000000"},"bitchat_recv_channels":[],"bitchat_broadcast_channels":[],"bitchat_recv_broadcast_key":"0000000000000000000000000000000000000000000000000000000000000000"}           addressbook.cpp:59
2968161ms       th_a                 open ] loading contact {"public_key":"03eb9505ab6cea892f22b63c818b4ce1ed1e3cce8eba6287ef99a110cefec54151","dac_id_hash":0,"dac_id_string":"","properties":[],"wallet_index":3,"privacy_setting":"secret_contact","first_name":"","last_name":"","icon_png":"89504e470d0a1a0a0000000d4948445200000020000000200806000000737a7af4000000097048597300000ec400000ec401952b0e1b00000392494441545885c5565d685c45183ddf7767eedd9b266977d3ba9a606ab0d522be2885405bd0a850a48a2fcd922294f8d2580a0505695f24e44d057df1a969f1af08765350b10f0afe2315a38896a0fd71355ada1a4d03d5cdeebd77ef9dcf871aec9add6476b3a51fcccb70e69c33e7ce7c77801b5cd4cca23d3f84f7926090c46c0200213e2d8489f1bbbc6fafab81c7cf4aa71704e34cc8d5582b46900f53a93d6fde417fb5dcc0e049f15dbffc0913fa97c219c15751d91f98d842651b5eb63500af381619d31f24064b8dc8987e78c5315b5aab04b67cf1674797eb5d24a0dd062f40f17214769fdcb6eeefe5b0ca86d067bd358c8d95f8bfd5eeb3de0ae0fd96188812e9214803fa80807a6c705606ca1553646ecc80212ab6cc40548926855988c8eacc88889071276db0d6d770e307331f12f0a09501e0a373dbb30fd960ad1200803049f6433009a2554babcb3c08fb6d791bea84d977cf3f00e2091032b5c531073183338fddfaf1753100006d277eb9d98b9d0302de49909eabba7481608e872a79bef448dfef8df0597f82852a7d3d3d5beaee7e0bc06952b40102124101b139052e5e6e94cf3e81c3852c91799a140f43d34d60fa8f41001801123327091d95927911fb369e6f99013e7c762f7bce73e43a9d6000f56ea3082080c4a68404a371e1f5973036669a37909f72dd79ff35f29d5d70c83eaf85442ae6bd707e6e08239b4b8d1b38f48d4ef999b739e5ec80d3d4bb05108144c9a7e5901ec6137d412d48dddf719b9f7e59fb6a87a3180e51738319ca53f7b7b7f1abf5746a6e6dd5d19f73da57c748513d4843254620b119b9925b3fbeac81f4a1c26aa4f519c7e3ec8a95ab4d5c2957e24da55c759f58d40738ad9f511e678957bef36a625aed907ab604ecbb76ba4aa5ebc88f1deeda8edf58f19ad6aa5f2d01ca89a6db66b6dff2c7c25c5502a9b59d434ad39abaf77ca5068cf81c9861002fd434a05df52b1b131053aa0567efffe2a844663a367cecdaf94532ebdfb934a0148e2b4519cbf7c7d2c20be241f27d18941ebdb8abba45d754e8cd4ff779befb86d2ce3676a8a9300400441057c444417c2498a5a72e8df42cea88f5b9474779c33d4f0e6b4da35a732f3160958800228224164491f9322a570e4e0ff57e5e0fbe3c637ecabd53a7776acdbbd9e1fb1c4529225a744e4500930892d8ccc5b19ca88495577ecaf57eb61c7d43e9aecb4fb56774d766877137446e274627091901cd9a44ce4562be2b64ba4f6180e246786f68fd0376596dac58d6da930000000049454e44ae426082","notes":"","next_send_trx_id":0,"send_trx_address":{"pub_key":"000000000000000000000000000000000000000000000000000000000000000000","chain_code":"0000000000000000000000000000000000000000000000000000000000000000"},"bitchat_recv_channels":[],"bitchat_broadcast_channels":[],"bitchat_recv_broadcast_key":"0000000000000000000000000000000000000000000000000000000000000000"}          addressbook.cpp:59
2968305ms       th_a UpgradeDbIfNecessary ] Database /home/yuvaraj/.local/share/Keyhotee/profiles/Y G/idents is not upgradeable         upgrade_leveldb.cpp:24
2968396ms       th_a UpgradeDbIfNecessary ] Database /home/yuvaraj/.local/share/Keyhotee/profiles/Y G/mail/inbox/index is not upgradeable           upgrade_leveldb.cpp:24
2968486ms       th_a UpgradeDbIfNecessary ] Database /home/yuvaraj/.local/share/Keyhotee/profiles/Y G/mail/inbox/digest_to_data is not upgradeable          upgrade_leveldb.cpp:24
2968566ms       th_a UpgradeDbIfNecessary ] Database /home/yuvaraj/.local/share/Keyhotee/profiles/Y G/mail/draft/index is not upgradeable           upgrade_leveldb.cpp:24
2968645ms       th_a UpgradeDbIfNecessary ] Database /home/yuvaraj/.local/share/Keyhotee/profiles/Y G/mail/draft/digest_to_data is not upgradeable          upgrade_leveldb.cpp:24
2968748ms       th_a UpgradeDbIfNecessary ] Database /home/yuvaraj/.local/share/Keyhotee/profiles/Y G/mail/pending/index is not upgradeable         upgrade_leveldb.cpp:24
2968839ms       th_a UpgradeDbIfNecessary ] Database /home/yuvaraj/.local/share/Keyhotee/profiles/Y G/mail/pending/digest_to_data is not upgradeable            upgrade_leveldb.cpp:24
2968929ms       th_a UpgradeDbIfNecessary ] Database /home/yuvaraj/.local/share/Keyhotee/profiles/Y G/mail/sent/index is not upgradeable            upgrade_leveldb.cpp:24
2969020ms       th_a UpgradeDbIfNecessary ] Database /home/yuvaraj/.local/share/Keyhotee/profiles/Y G/mail/sent/digest_to_data is not upgradeable           upgrade_leveldb.cpp:24
2969110ms       th_a UpgradeDbIfNecessary ] Database /home/yuvaraj/.local/share/Keyhotee/profiles/Y G/chat/index is not upgradeable         upgrade_leveldb.cpp:24
2969190ms       th_a UpgradeDbIfNecessary ] Database /home/yuvaraj/.local/share/Keyhotee/profiles/Y G/chat/digest_to_data is not upgradeable            upgrade_leveldb.cpp:24
2969190ms       th_a                 open ] finished opening profile            profile.cpp:142
2969190ms       th_a            configure ] application::configure          application.cpp:219
2969190ms       th_a            configure ] configuring server          application.cpp:251
2969190ms       th_a            configure ] listening for stcp connections on port 9876         server.cpp:208
2969191ms       th_a            configure ] configure bitname client            application.cpp:257
2969291ms       th_a UpgradeDbIfNecessary ] Database /home/yuvaraj/.local/share/Keyhotee/profiles/Y G/data/bitname/bitname/channel/block_num_to_header is not upgradeable           upgrade_leveldb.cpp:24
2969383ms       th_a UpgradeDbIfNecessary ] Database /home/yuvaraj/.local/share/Keyhotee/profiles/Y G/data/bitname/bitname/channel/block_num_to_name_trxs is not upgradeable            upgrade_leveldb.cpp:24
2969473ms       th_a UpgradeDbIfNecessary ] Database /home/yuvaraj/.local/share/Keyhotee/profiles/Y G/data/bitname/bitname/channel/name_hash_to_locs is not upgradeable         upgrade_leveldb.cpp:24
2969474ms       th_a         load_indexes ] load indexes            bitname_db.cpp:100
2969474ms       th_a         load_indexes ] load indexes            bitname_db.cpp:115
2969475ms       th_a      init_timekeeper ] ...init stats...            bitname_db.cpp:170
2969475ms       th_a      init_timekeeper ] ...done init timekeeper...          bitname_db.cpp:172
2969475ms       th_a                 open ] open name db            bitname_db.cpp:222
2969609ms       th_a UpgradeDbIfNecessary ] Database /home/yuvaraj/.local/share/Keyhotee/profiles/Y G/data/bitname/bitname/channel/forks/headers is not upgradeable         upgrade_leveldb.cpp:24
2969744ms       th_a UpgradeDbIfNecessary ] Database /home/yuvaraj/.local/share/Keyhotee/profiles/Y G/data/bitname/bitname/channel/forks/blocks is not upgradeable          upgrade_leveldb.cpp:24
2969858ms       th_a UpgradeDbIfNecessary ] Database /home/yuvaraj/.local/share/Keyhotee/profiles/Y G/data/bitname/bitname/channel/forks/forks is not upgradeable           upgrade_leveldb.cpp:24
2969948ms       th_a UpgradeDbIfNecessary ] Database /home/yuvaraj/.local/share/Keyhotee/profiles/Y G/data/bitname/bitname/channel/forks/nexts is not upgradeable           upgrade_leveldb.cpp:24
2970040ms       th_a UpgradeDbIfNecessary ] Database /home/yuvaraj/.local/share/Keyhotee/profiles/Y G/data/bitname/bitname/channel/forks/unknown is not upgradeable         upgrade_leveldb.cpp:24
2970043ms       th_a            configure ] configure bitchat client            application.cpp:267
2970142ms       th_a UpgradeDbIfNecessary ] Database /home/yuvaraj/.local/share/Keyhotee/profiles/Y G/data/bitchat/channel0/cache_chan_2/message_cache/by_id is not upgradeable         upgrade_leveldb.cpp:24
2970232ms       th_a UpgradeDbIfNecessary ] Database /home/yuvaraj/.local/share/Keyhotee/profiles/Y G/data/bitchat/channel0/cache_chan_2/message_cache/age_index is not upgradeable         upgrade_leveldb.cpp:24
2970233ms       th_a            configure ] configuring rpc_server          application.cpp:271
2970233ms       th_a            configure ] listening for rpc connections on port 9877          rpc_server.cpp:245
2970233ms       th_a            configure ] listening for rpc connections on port 9877          rpc_server.cpp:247
2970233ms       th_a            configure ] done configuring rpc_server         application.cpp:274
2970233ms       th_a            configure ] end application::configure          application.cpp:276
2970378ms       th_a       reloadContacts ] loading contacts...         AddressBookModel.cpp:306
2970379ms       th_a       reloadContacts ] loading contacts...         AddressBookModel.cpp:306
2970380ms       th_a       reloadContacts ] loading contacts...         AddressBookModel.cpp:306
2970394ms       th_a   KeyhoteeMainWindow ] idents: [{"public_key":"02ed7ab452510c60f070a2c154596140b0ac4cbaaded1ceed19bfe69b835290d01","dac_id_hash":16821335187958279111,"dac_id_string":"hhgjhjgh","properties":[],"wallet_ident":"hhgjhjgh","mining_effort":25,"first_name":"","last_name":"","private_icon_png":""},{"public_key":"039f346b679bb39c0014b90f34ac8ec02de39c384a0d6e18904454355fb994c358","dac_id_hash":3063318953795315473,"dac_id_string":"hhh","properties":[],"wallet_ident":"hhh","mining_effort":25,"first_name":"","last_name":"","private_icon_png":""}]          KeyhoteeMainWindow.cpp:299
2970411ms       th_a start_mail_connect_l ] start_mail_connect_loop         application.cpp:154
2970414ms       th_a    accept_connection ] accepted connection from 127.0.0.1:53388            server.cpp:116
2970414ms       th_a         on_connected ] on connected...         peer_channel.cpp:162
2970415ms       th_a     handle_subscribe ] 127.0.0.1:53388: {"channels":[{"proto":"chat_proto","chan":0},{"proto":"name_proto","chan":0},{"proto":"peer_proto","chan":0}]}         peer_channel.cpp:339
2970415ms       th_a request_block_header ] requesting block headers from 127.0.0.1:53388           bitname_channel.cpp:499
2970415ms       th_a       handle_message ] get_headers_msg         bitname_channel.cpp:445
2970454ms       th_a       handle_message ] headers_msg         bitname_channel.cpp:445
2970454ms       th_a       handle_headers ] received ${x} block headers         bitname_channel.cpp:728
2973775ms       th_a   displayFailureInfo ] assert
!"invalid contact id": 
    {}
    th_a  AddressBookModel.cpp:271 getContactRow            KeyhoteeApplication.cpp:259
2973775ms       th_a   displayFailureInfo ] fatal error assert
!"invalid contact id": 
    {}
    th_a  AddressBookModel.cpp:271 getContactRow            KeyhoteeApplication.cpp:261

**Comment by dnotestein** [comment]
Fixed in old commit.
