### ISSUE TITLE
autocompletion works even for substrings in a contact.

### ISSUE THREAD

**Issue by yuvarajgogoi** [InvictusInnovations/keyhotee#318]
Steps to reproduce
1)create 2 contacts. "f" and "gf" .
2) Now try to autocomplete with "f"

both the contacts are shown in auto completion.

Tested on Ubuntu and is always reproducible

**Comment by PaulEU** [comment]
A lot of programs use autocompletion with substring matching in an address book. It's useful if you don't remember first letters of your contact. So, I'm closing this issue.
