### ISSUE TITLE
Login dialog should display list of available profiles

### ISSUE THREAD

**Issue by vogel76** [InvictusInnovations/keyhotee#32]
1) The login dialog should display a list of available profiles stored in the Invictus directory under appData that stores the profiles.If no profiles exist, login dialog should not be opened: instead of profile wizard should be launched.
2) Last used profile should be stored in application settings (QT associated). Then application should automatically select the last used profile to simplify login process
3) If the user specifies a profile on the command line and specified profile exists, this specified profile should override "last used profile" stored in application settings and should be selected.
4) Right now, login dialog is opened after profile is loaded, so above changes will require some changes in ordering of startup code I think. In particular, this dialog will now need to first load the profile, then verify that password is correct for loaded profile.
5) BTW, Don't eliminate graphics view in this dialog (it will be filled in eventually by results of a contest on keyhotee Forum.

**Comment by bytemaster** [comment]
I implemented this.
