### ISSUE TITLE
Bad message that causes crash

### ISSUE THREAD

**Issue by dnotestein** [InvictusInnovations/keyhotee#320]
From forum post by yellowecho:
https://bitsharestalk.org/index.php?topic=1984.msg40683#msg40683

Keyhotee is bugging out for me.
I sent myself a message and the app shut down unexpectedly.  It seems to be stuck in a loop or something now.  Every time I open the app, it retrieves a new copy of the message then closes itself again.

**Comment by vogel76** [comment]
Maybe we could get some more info related to it. Maybe we could get debug log contents to see the message contents, etc.

**Comment by dnotestein** [comment]
I'm pretty sure this is a duplicate of the duplicate message error that's been fixed, so closing this issue.
