### ISSUE TITLE
Can't close application

### ISSUE THREAD

**Issue by grzegorzs** [InvictusInnovations/keyhotee#331]
At each attempt to close the application I get the message:
![close_error](https://f.cloud.github.com/assets/6090084/2398194/2620f9d8-a9f3-11e3-9fe7-08c71371cb72.png)

**Comment by vogel76** [comment]
Fixed at rev: https://github.com/InvictusInnovations/BitShares/commit/781a8d92faf64dfde2b75af2309cb4f05017244d
