### ISSUE TITLE
The "Date Sent" in Sent mailbox takes up the time of test machine.

### ISSUE THREAD

**Issue by yuvarajgogoi** [InvictusInnovations/keyhotee#337]
Steps to reproduce
1) change the time of your test machine to some earlier time.
2) start a profile
3) send a message.
4) Check "Date sent" of the mail

It shows the time of the test machine.

Tested in Debian and is always reproducible.

**Comment by dnotestein** [comment]
I think this is probably how we want it to work, so I'm closing this one out.
