### ISSUE TITLE
How to get some bitshares network nodes?

### ISSUE THREAD

**Issue by vipjeffreylee** [InvictusInnovations/keyhotee#34]
Keyhotee main windows show Number of active connections to bitshares network is zero,How to get some network nodes?

**Comment by dnotestein** [comment]
I've posted some instructions on connecting nodes in keyhotee directory in file called: communicating_between_keyhotee_clients.txt

**Comment by vipjeffreylee** [comment]
Where is keyhoteed?

**Comment by dnotestein** [comment]
it's the exe for the program, it may be keyhotee instead (keyhoteed is for the debug version of the build, which is what I normally build). It's built to INVICTUS_ROOT/bin (you have to define this INVICTUS_ROOT variable to specify where your binary is built).

**Comment by vipjeffreylee** [comment]
Oh,Isee, you call keyhoteed whitch is not keyhotee daemon  in communicating_between_keyhotee_clients.txt ,but I think keyhoteed is keyhotee daemon before.

**Comment by dnotestein** [comment]
yes, I guessed that might be what you were thinking, sorry for the confusion. I guess I'll add a clarification to the document.

**Comment by vipjeffreylee** [comment]
waht is meaning \* Run "keyhoteed second" and create a new identity ?
I run keyhotee second ,I selected New identity,it show Not supported.

**Comment by dnotestein** [comment]
Sorry, you don't actually have to select "New Identity" (that's not yet implemented, as msg indicates). By passing a parameter to keyhotee, you have told it to create a new profile (in this case we're creating a profile called "second"). Whenever you create a new profile, the program forces you to create an identity (after the wallet wizard, it asks you what this identity's kId will be.

**Comment by dnotestein** [comment]
I've pushed some important corrections to my document for connecting Keyhotee clients, please pull before following procedure.

**Comment by vipjeffreylee** [comment]
thanks I see!

2013/12/11 dnotestein notifications@github.com

**Comment by vipjeffreylee** [comment]
Second can find first and self,but first can't find second.first can find itselft too.
