### ISSUE TITLE
message recieved is not updated in GUI

### ISSUE THREAD

**Issue by yuvarajgogoi** [InvictusInnovations/keyhotee#345]
Steps to reproduce:

1) send mail to an id 
2) close the client after 3-4 seconds(just before recieving the mail such that the mail is recieved after pressing close , You can verify this from the log) 
3) close is done.
4) restart KH. 

Issue is the message recieved in step 2 was not updated in gui.

Tested in Debain and is hard to reproduce.

log : 

2712090ms th_a       KeyhoteeApplication.cpp:436   startup              ] .
2712090ms th_a       application.cpp:454           get_profiles         ] /home/yuvaraj/.local/share/Keyhotee/profiles/Y G
2712090ms th_a       application.cpp:461           get_profiles         ] profiles ["Y G"]
2712090ms th_a       KeyhoteeApplication.cpp:373   displayLogin         ] .
2712098ms th_a       application.cpp:454           get_profiles         ] /home/yuvaraj/.local/share/Keyhotee/profiles/Y G
2712098ms th_a       application.cpp:461           get_profiles         ] profiles ["Y G"]
2712098ms th_a       LoginDialog.cpp:42            LoginDialog          ] profiles Y G
2714665ms th_a       profile.cpp:111               open                 ] opening profile: /home/yuvaraj/.local/share/Keyhotee/profiles/Y G
2714665ms th_a       profile.cpp:126               open                 ] loading master key file:.keyhotee_master.key
2714666ms th_a       profile.cpp:138               open                 ] opening profile databases
2714811ms th_a       upgrade_leveldb.cpp:24        UpgradeDbIfNecessary ] Database /home/yuvaraj/.local/share/Keyhotee/profiles/Y G/addressbook/contact_db is not upgradeable
2714811ms th_a       addressbook.cpp:59            open                 ] loading contact {"public_key":"022f38db332be8ccd9432464297cb7e3c782d7324c1497ed213a7409c93b982264","dac_id_hash":9871701508635294881,"dac_id_string":"y","properties":[],"wallet_index":0,"auth_status":"unauthorized","privacy_setting":"secret_contact","first_name":"","last_name":"","icon_png":"","notes":"","next_send_trx_id":0,"send_trx_address":{"pub_key":"000000000000000000000000000000000000000000000000000000000000000000","chain_code":"0000000000000000000000000000000000000000000000000000000000000000"},"bitchat_recv_channels":[],"bitchat_broadcast_channels":[],"bitchat_recv_broadcast_key":"0000000000000000000000000000000000000000000000000000000000000000"}
2714967ms th_a       upgrade_leveldb.cpp:24        UpgradeDbIfNecessary ] Database /home/yuvaraj/.local/share/Keyhotee/profiles/Y G/idents is not upgradeable
2715168ms th_a       upgrade_leveldb.cpp:24        UpgradeDbIfNecessary ] Database /home/yuvaraj/.local/share/Keyhotee/profiles/Y G/mail/inbox/index is not upgradeable
2715392ms th_a       upgrade_leveldb.cpp:24        UpgradeDbIfNecessary ] Database /home/yuvaraj/.local/share/Keyhotee/profiles/Y G/mail/inbox/digest_to_data is not upgradeable
2715615ms th_a       upgrade_leveldb.cpp:24        UpgradeDbIfNecessary ] Database /home/yuvaraj/.local/share/Keyhotee/profiles/Y G/mail/inbox/digest_to_header is not upgradeable
2715771ms th_a       upgrade_leveldb.cpp:24        UpgradeDbIfNecessary ] Database /home/yuvaraj/.local/share/Keyhotee/profiles/Y G/mail/draft/index is not upgradeable
2715930ms th_a       upgrade_leveldb.cpp:24        UpgradeDbIfNecessary ] Database /home/yuvaraj/.local/share/Keyhotee/profiles/Y G/mail/draft/digest_to_data is not upgradeable
2716075ms th_a       upgrade_leveldb.cpp:24        UpgradeDbIfNecessary ] Database /home/yuvaraj/.local/share/Keyhotee/profiles/Y G/mail/draft/digest_to_header is not upgradeable
2716276ms th_a       upgrade_leveldb.cpp:24        UpgradeDbIfNecessary ] Database /home/yuvaraj/.local/share/Keyhotee/profiles/Y G/mail/pending/index is not upgradeable
2716478ms th_a       upgrade_leveldb.cpp:24        UpgradeDbIfNecessary ] Database /home/yuvaraj/.local/share/Keyhotee/profiles/Y G/mail/pending/digest_to_data is not upgradeable
2716701ms th_a       upgrade_leveldb.cpp:24        UpgradeDbIfNecessary ] Database /home/yuvaraj/.local/share/Keyhotee/profiles/Y G/mail/pending/digest_to_header is not upgradeable
2716924ms th_a       upgrade_leveldb.cpp:24        UpgradeDbIfNecessary ] Database /home/yuvaraj/.local/share/Keyhotee/profiles/Y G/mail/sent/index is not upgradeable
2717148ms th_a       upgrade_leveldb.cpp:24        UpgradeDbIfNecessary ] Database /home/yuvaraj/.local/share/Keyhotee/profiles/Y G/mail/sent/digest_to_data is not upgradeable
2717538ms th_a       upgrade_leveldb.cpp:24        UpgradeDbIfNecessary ] Database /home/yuvaraj/.local/share/Keyhotee/profiles/Y G/mail/sent/digest_to_header is not upgradeable
2717696ms th_a       upgrade_leveldb.cpp:24        UpgradeDbIfNecessary ] Database /home/yuvaraj/.local/share/Keyhotee/profiles/Y G/chat/index is not upgradeable
2717808ms th_a       upgrade_leveldb.cpp:24        UpgradeDbIfNecessary ] Database /home/yuvaraj/.local/share/Keyhotee/profiles/Y G/chat/digest_to_data is not upgradeable
2717921ms th_a       upgrade_leveldb.cpp:24        UpgradeDbIfNecessary ] Database /home/yuvaraj/.local/share/Keyhotee/profiles/Y G/chat/digest_to_header is not upgradeable
2718033ms th_a       upgrade_leveldb.cpp:24        UpgradeDbIfNecessary ] Database /home/yuvaraj/.local/share/Keyhotee/profiles/Y G/request/index is not upgradeable
2718156ms th_a       upgrade_leveldb.cpp:24        UpgradeDbIfNecessary ] Database /home/yuvaraj/.local/share/Keyhotee/profiles/Y G/request/digest_to_data is not upgradeable
2718290ms th_a       upgrade_leveldb.cpp:24        UpgradeDbIfNecessary ] Database /home/yuvaraj/.local/share/Keyhotee/profiles/Y G/request/digest_to_header is not upgradeable
2718424ms th_a       upgrade_leveldb.cpp:24        UpgradeDbIfNecessary ] Database /home/yuvaraj/.local/share/Keyhotee/profiles/Y G/authorization/index is not upgradeable
2718558ms th_a       upgrade_leveldb.cpp:24        UpgradeDbIfNecessary ] Database /home/yuvaraj/.local/share/Keyhotee/profiles/Y G/authorization/digest_to_data is not upgradeable
2718692ms th_a       upgrade_leveldb.cpp:24        UpgradeDbIfNecessary ] Database /home/yuvaraj/.local/share/Keyhotee/profiles/Y G/authorization/digest_to_header is not upgradeable
2718692ms th_a       profile.cpp:156               open                 ] loaded last_sync_time = 20140414T095947.832829
2718692ms th_a       profile.cpp:157               open                 ] finished opening profile
2718693ms th_a       application.cpp:289           configure            ] application::configure
2718693ms th_a       application.cpp:321           configure            ] configuring server
2718693ms th_a       server.cpp:208                configure            ] listening for stcp connections on port 0
2718693ms th_a       application.cpp:327           configure            ] configure bitname client
2718815ms th_a       upgrade_leveldb.cpp:24        UpgradeDbIfNecessary ] Database /home/yuvaraj/.local/share/Keyhotee/profiles/Y G/data/bitname/bitname/channel/block_num_to_header is not upgradeable
2718927ms th_a       upgrade_leveldb.cpp:24        UpgradeDbIfNecessary ] Database /home/yuvaraj/.local/share/Keyhotee/profiles/Y G/data/bitname/bitname/channel/block_num_to_name_trxs is not upgradeable
2719039ms th_a       upgrade_leveldb.cpp:24        UpgradeDbIfNecessary ] Database /home/yuvaraj/.local/share/Keyhotee/profiles/Y G/data/bitname/bitname/channel/name_hash_to_locs is not upgradeable
2719039ms th_a       bitname_db.cpp:100            load_indexes         ] load indexes
2719039ms th_a       bitname_db.cpp:115            load_indexes         ] load indexes
2719041ms th_a       bitname_db.cpp:170            init_timekeeper      ] ...init stats...
2719041ms th_a       bitname_db.cpp:172            init_timekeeper      ] ...done init timekeeper...
2719042ms th_a       bitname_db.cpp:222            open                 ] open name db
chain time: 20130822T183833
expected time: 20130822T183833
target difficulty: 268435456
target name difficulty: 268435456
2719242ms th_a       upgrade_leveldb.cpp:24        UpgradeDbIfNecessary ] Database /home/yuvaraj/.local/share/Keyhotee/profiles/Y G/data/bitname/bitname/channel/forks/headers is not upgradeable
2719410ms th_a       upgrade_leveldb.cpp:24        UpgradeDbIfNecessary ] Database /home/yuvaraj/.local/share/Keyhotee/profiles/Y G/data/bitname/bitname/channel/forks/blocks is not upgradeable
2719611ms th_a       upgrade_leveldb.cpp:24        UpgradeDbIfNecessary ] Database /home/yuvaraj/.local/share/Keyhotee/profiles/Y G/data/bitname/bitname/channel/forks/forks is not upgradeable
2719745ms th_a       upgrade_leveldb.cpp:24        UpgradeDbIfNecessary ] Database /home/yuvaraj/.local/share/Keyhotee/profiles/Y G/data/bitname/bitname/channel/forks/nexts is not upgradeable
2719890ms th_a       upgrade_leveldb.cpp:24        UpgradeDbIfNecessary ] Database /home/yuvaraj/.local/share/Keyhotee/profiles/Y G/data/bitname/bitname/channel/forks/unknown is not upgradeable
2719893ms th_a       application.cpp:337           configure            ] configure bitchat client
2720046ms th_a       upgrade_leveldb.cpp:24        UpgradeDbIfNecessary ] Database /home/yuvaraj/.local/share/Keyhotee/profiles/Y G/data/bitchat/channel0/cache_chan_2/message_cache/by_id is not upgradeable
2720192ms th_a       upgrade_leveldb.cpp:24        UpgradeDbIfNecessary ] Database /home/yuvaraj/.local/share/Keyhotee/profiles/Y G/data/bitchat/channel0/cache_chan_2/message_cache/age_index1 is not upgradeable
2720192ms th_a       application.cpp:341           configure            ] configuring rpc_server
2720192ms th_a       rpc_server.cpp:245            configure            ] listening for rpc connections on port 0
2720192ms th_a       rpc_server.cpp:247            configure            ] listening for rpc connections on port 50066
2720192ms th_a       application.cpp:344           configure            ] done configuring rpc_server
2720192ms th_a       application.cpp:346           configure            ] end application::configure
QMetaObject::connectSlotsByName: No matching signal for on_actionShow_details_toggled(bool)
QLayout: Attempting to add QLayout "" to Mailbox "inbox_page", which already has a layout
QMetaObject::connectSlotsByName: No matching signal for on_actionShow_details_toggled(bool)
QMetaObject::connectSlotsByName: No matching signal for on_actionShow_details_toggled(bool)
QMetaObject::connectSlotsByName: No matching signal for on_actionShow_details_toggled(bool)
QMetaObject::connectSlotsByName: No matching signal for on_actionShow_details_toggled(bool)
QLayout: Attempting to add QLayout "" to ContactsTable "contacts_page", which already has a layout
2720303ms th_a       AddressBookModel.cpp:310      reloadContacts       ] loading contacts...
2720324ms th_a       KeyhoteeMainWindow.cpp:241    KeyhoteeMainWindow   ] idents: [{"public_key":"022f38db332be8ccd9432464297cb7e3c782d7324c1497ed213a7409c93b982264","dac_id_hash":9871701508635294881,"dac_id_string":"y","properties":[],"wallet_ident":"y","mining_effort":25,"first_name":"","last_name":"","private_icon_png":""}]
2720350ms th_a       application.cpp:196           start_mail_connect_l ] start_mail_connect_loop
2720351ms th_a       application.cpp:200           operator()           ] Closing the mail connection (which may not be open)
2720351ms th_a       application.cpp:202           operator()           ] Done closing the mail connection
2725351ms th_a       application.cpp:81            mail_connect_loop    ] mail connect 162.243.67.4:7896, send sync_time=20140414T095947.832829
2725352ms th_a       mail_connection.cpp:211       connect              ] connect to 162.243.67.4:7896 and resolved ["162.243.67.4:7896"]
2725853ms th_a       mail_connection.cpp:202       connect              ]     connected to 162.243.67.4:7896
2726067ms th_a       bitchat_private_message.cpp:55 decrypt              ] we passed checksum test... unpack message..
2726068ms th_a       bitchat_private_message.cpp:63 decrypt              ] type: 6
2726070ms th_a       application.cpp:216           bitchat_message_rece ] received {"msg_type":"email_msg1","data":"0001022f38db332be8ccd9432464297cb7e3c782d7324c1497ed213a7409c93b982264004b676767676767676767676767676767676767676767676767676767676767676767676767676767676767676767676767676767676767676767676767676767676767676767676767676767dd033c21444f43545950452048544d4c205055424c494320222d2f2f5733432f2f4454442048544d4c20342e302f2f454e222022687474703a2f2f7777772e77332e6f72672f54522f5245432d68746d6c34302f7374726963742e647464223e0a3c68746d6c3e3c686561643e3c6d657461206e616d653d227172696368746578742220636f6e74656e743d223122202f3e3c7374796c6520747970653d22746578742f637373223e0a702c206c69207b2077686974652d73706163653a207072652d777261703b207d0a3c2f7374796c653e3c2f686561643e3c626f6479207374796c653d2220666f6e742d66616d696c793a2753616e73205365726966273b20666f6e742d73697a653a3970743b20666f6e742d7765696768743a3430303b20666f6e742d7374796c653a6e6f726d616c3b223e0a3c70207374796c653d222d71742d7061726167726170682d747970653a656d7074793b206d617267696e2d746f703a3070783b206d617267696e2d626f74746f6d3a3070783b206d617267696e2d6c6566743a3070783b206d617267696e2d72696768743a3070783b202d71742d626c6f636b2d696e64656e743a303b20746578742d696e64656e743a3070783b223e3c6272202f3e3c2f703e3c2f626f64793e3c2f68746d6c3e000000","sig_time":"20140414T094459.744178","from_sig":"20b611787043573be8ae1111ea2119260e6d3bbccb539587cd640dae141fdb4423f51320fa9582f80c87712589cccdc29dc21a41a9327a89d313fa1988f5f0a949"}
2726071ms th_a       application.cpp:251           bitchat_message_rece ] email message 1 {"from_keyhotee_id":"","to_list":["022f38db332be8ccd9432464297cb7e3c782d7324c1497ed213a7409c93b982264"],"cc_list":[],"subject":"ggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggg","body":"<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\np, li { white-space: pre-wrap; }\n</style></head><body style=\" font-family:'Sans Serif'; font-size:9pt; font-weight:400; font-style:normal;\">\n<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>","attachments":[],"bcc_list":[],"src_msg_id":null}
2726072ms th_a       application.cpp:154           on_connection_messag ] last_sync_time now: 20140414T095947.832829
2726072ms th_a       profile.cpp:83                set_last_sync_time   ] time=20140414T100012.053439
2732655ms th_a       bitchat_private_message.cpp:55 decrypt              ] we passed checksum test... unpack message..
2732655ms th_a       bitchat_private_message.cpp:63 decrypt              ] type: 6
2732671ms th_a       application.cpp:580           send_email           ] send_email at 20140414T094532.670985
2732676ms th_a       bitchat_private_message.cpp:55 decrypt              ] we passed checksum test... unpack message..
2732676ms th_a       bitchat_private_message.cpp:63 decrypt              ] type: 6
2741068ms th_a       bitchat_private_message.cpp:55 decrypt              ] we passed checksum test... unpack message..
2741070ms th_a       bitchat_private_message.cpp:63 decrypt              ] type: 6
2741072ms th_a       application.cpp:216           bitchat_message_rece ] received {"msg_type":"email_msg1","data":"0001022f38db332be8ccd9432464297cb7e3c782d7324c1497ed213a7409c93b982264004b676767676767676767676767676767676767676767676767676767676767676767676767676767676767676767676767676767676767676767676767676767676767676767676767676767dd033c21444f43545950452048544d4c205055424c494320222d2f2f5733432f2f4454442048544d4c20342e302f2f454e222022687474703a2f2f7777772e77332e6f72672f54522f5245432d68746d6c34302f7374726963742e647464223e0a3c68746d6c3e3c686561643e3c6d657461206e616d653d227172696368746578742220636f6e74656e743d223122202f3e3c7374796c6520747970653d22746578742f637373223e0a702c206c69207b2077686974652d73706163653a207072652d777261703b207d0a3c2f7374796c653e3c2f686561643e3c626f6479207374796c653d2220666f6e742d66616d696c793a2753616e73205365726966273b20666f6e742d73697a653a3970743b20666f6e742d7765696768743a3430303b20666f6e742d7374796c653a6e6f726d616c3b223e0a3c70207374796c653d222d71742d7061726167726170682d747970653a656d7074793b206d617267696e2d746f703a3070783b206d617267696e2d626f74746f6d3a3070783b206d617267696e2d6c6566743a3070783b206d617267696e2d72696768743a3070783b202d71742d626c6f636b2d696e64656e743a303b20746578742d696e64656e743a3070783b223e3c6272202f3e3c2f703e3c2f626f64793e3c2f68746d6c3e000000","sig_time":"20140414T094532.663729","from_sig":"203c52f6d4eb755643dcc4070fc6260f138262f33d96c94069221d5629814b0d06f49462b6cb8411820ca62dfb8a4f5cc9633a67c851ec2c54e37197e3b173663f"}
2741073ms th_a       application.cpp:251           bitchat_message_rece ] email message 1 {"from_keyhotee_id":"","to_list":["022f38db332be8ccd9432464297cb7e3c782d7324c1497ed213a7409c93b982264"],"cc_list":[],"subject":"ggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggg","body":"<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\np, li { white-space: pre-wrap; }\n</style></head><body style=\" font-family:'Sans Serif'; font-size:9pt; font-weight:400; font-style:normal;\">\n<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>","attachments":[],"bcc_list":[],"src_msg_id":null}
2741073ms th_a       application.cpp:154           on_connection_messag ] last_sync_time now: 20140414T100012.053439
2741073ms th_a       profile.cpp:83                set_last_sync_time   ] time=20140414T100044.983265
2741351ms th_a       server.cpp:34                 close                ] closing connections...
2741352ms th_a       server.cpp:162                accept_loop          ] accept loop canceled
2741352ms th_a       mail_connection.cpp:184       close                ] waiting for socket to close
2741353ms th_a       mail_connection.cpp:82        read_loop            ] disconnected canceled
Operation canceled 
    {"message":"Operation canceled"}
    asio  asio.cpp:17 read_write_handler

```
{"len":16}
th_a  stcp_socket.cpp:59 readsome
```

2741353ms th_a       mail_connection.cpp:186       close                ] socket closed
2741353ms th_a       rpc_server.cpp:37             accept_loop          ] fatal: error opening socket for rpc connection: canceled
Operation canceled 
    {"message":"Operation canceled"}
    asio  asio.cpp:45 error_handler
Unable to accept connection on socket.
    {}
    th_a  tcp_socket.cpp:143 accept
2741354ms th_a       rpc_server.cpp:57             register_methods     ] login!
2741354ms th_a       json_connection.cpp:269       add_method           ] add method login
2741354ms th_a       json_connection.cpp:269       add_method           ] add method lookup_name
2741354ms th_a       json_connection.cpp:269       add_method           ] add method reverse_name_lookup
2741354ms th_a       json_connection.cpp:269       add_method           ] add method verify_signature
2741354ms th_a       json_connection.cpp:269       add_method           ] add method sign_message
2741354ms th_a       json_connection.cpp:269       add_method           ] add method load_profile
2741355ms th_a       json_connection.cpp:269       add_method           ] add method mine_name
2741355ms th_a       json_connection.cpp:269       add_method           ] add method add_nodes
2741355ms th_a       json_connection.cpp:269       add_method           ] add method get_connections
2741355ms th_a       thread.cpp:135                quit                 ] joining... upnp
2741355ms th_a       thread.cpp:139                quit                 ] done joining...upnp
2741355ms th_a       bitchat_client.cpp:67         ~client              ] 
2741356ms th_a       json_connection.cpp:225       close                ] close unspecified
Bad file descriptor 
    {"message":"Bad file descriptor"}
    asio  asio.cpp:28 read_write_handler
2741358ms th_a       thread.cpp:135                quit                 ] joining... bitname1
2741359ms th_a       thread.cpp:139                quit                 ] done joining...bitname1
2741370ms th_a       server.cpp:34                 close                ] closing connections...

**Comment by grzegorzs** [comment]
I committed small fix.
Yuvarajgogoi can you check if the problem still occurs?
I did not reproduce this problem.

**Comment by yuvarajgogoi** [comment]
The issue is still reproducible.

**Comment by grzegorzs** [comment]
Please send me logs before and after restart KH. Logs is in temporary dir (tmp or TMPDIR), in file something like qt_temp.Hp####, for example qt_temp.Hp3468

**Comment by yuvarajgogoi** [comment]
![qt_temp j19918](https://cloud.githubusercontent.com/assets/5823578/2711119/4b9f7bfc-c4ca-11e3-84f5-e032249b1c3e.png)
![qt_temp j19953](https://cloud.githubusercontent.com/assets/5823578/2711120/4ba25b06-c4ca-11e3-918c-4bebbf160a8e.png)

**Comment by yuvarajgogoi** [comment]
Please rename the files as qt_temp.J19918 and qt_temp.J19953 respectively

**Comment by grzegorzs** [comment]
I committed another fix.
https://github.com/InvictusInnovations/BitShares/commit/4bd346c953120c8db95f9b231283a529981f60ee
Yuvarajgogoi can you check it?

**Comment by yuvarajgogoi** [comment]
fixed.
