### ISSUE TITLE
recieving chat messages in a scenario even if identity is deleted.

### ISSUE THREAD

**Issue by yuvarajgogoi** [InvictusInnovations/keyhotee#348]
Steps to reproduce
1) create 2 identity on 1 client(KH 1) 
2) create 1 identity on other client.(KH 2) 
3) add all the identities on each other contacts of each client. 
4) Now from the client with 1 identity(KH 2) send chat messages to the 2 contacts of other client. This chat messages are successful. 
5) Now delete only 1 identity from 2 identity from KH 1. 
6) from KH 2 again send chat messages to each of the 2 contacts.

Issue is all the 2 chat messages of KH 2 are recieved at KH 1

Tested in Debain and is always reproducible.

**Comment by dnotestein** [comment]
It sounds like we're not deleting the keys associated with the identity. We should delete at least the message key (and probably any contact authorization keys created for that identity also).

I'm going to file a new issue on a related subject (recovery of message history and key recovery when moving an identity to a new KH client).

**Comment by yuvarajgogoi** [comment]
Fixed at https://github.com/InvictusInnovations/BitShares/commit/4ccb35b8d4ee661ef40f9fb922dcafc6b86b2460

and f937a6cab1a42ffb5e644909087f92d56f29f443
