### ISSUE TITLE
Add controls to New Identity to download identity history

### ISSUE THREAD

**Issue by dnotestein** [InvictusInnovations/keyhotee#349]
Modify the New Identity dialog as follows: add a dropdown box with a static title: Download Identity History. Drop-down string options: 1 week, 1 month, 3 months, 6 months, 1 year, 2 years, 3 years, 5 years, all

This will be used when a user is re-creating an identity that already exists, so that he can download his message history to the profile.

**Comment by vogel76** [comment]
Just prepare the UI for now. Further spec will be defined later how to use these entered data.
