### ISSUE TITLE
Fix display of Keyhotee on retina display devices

### ISSUE THREAD

**Issue by dnotestein** [InvictusInnovations/keyhotee#352]
We need to modify the info.plist file generated by cmake as decribed here:
https://blog.qt.digia.com/blog/2013/04/25/retina-display-support-for-mac-os-ios-and-x11/\

More specifically, high DPI mode is controlled by the following keys in the Info.Plist file:

<key>NSPrincipalClass</key>
<string>NSApplication</string>
<key>NSHighResolutionCapable</key>
<string>True</string>
If NSHighResolutionCapable is set to false, or the keys are missing, then the application will be rendered at the “normal” resolution and scaled up. This looks horrible and should be avoided, especially since the high-dpi mode is very backwards compatible and the application gets a lot of high-dpi support for free.

To modify cmake to generate this info.plist file:
http://stackoverflow.com/questions/1792632/how-to-add-an-extra-plist-property-using-cmake

**Comment by grzegorzs** [comment]
Fixed at f6dc802bf4bfcd5d1ca0bc143e496b3534e0fe67
