### ISSUE TITLE
I am able to add a random public key like this: "66gfAFHc5yDPiyQo2MQxQNistqW5Fptk1vxdZ6fz9kAr37Upk8"

### ISSUE THREAD

**Issue by yuvarajgogoi** [InvictusInnovations/keyhotee#353]
Steps to reproduce
1) Do new contacts add this key 66gfAFHc5yDPiyQo2MQxQNistqW5Fptk1vxdZ6fz9kAr37Upk8" in contacts and it shows that it is a valid key.

I got this kind of public key like this:
1) Do New Identity 
2) write something in Keyhotee ID. 
3) a public key will be generated. Copy this public key and cancel the identity creation.
4) Try to add this public key in contacts. I am able to add 1 such public key.

Tested in Debain and is always reproducible.

**Comment by vogel76** [comment]
Since key has been produced by application so it is syntactically & semantically valid. Then there is no objections to define such contact (application really don't check if public key points to any existing contact).
