### ISSUE TITLE
wrong no of connections shown in Bitshares network

### ISSUE THREAD

**Issue by yuvarajgogoi** [InvictusInnovations/keyhotee#356]
Steps to reproduce:
1)start 2 clients in 2 different hosts 
2) modify config.json so that chat is successfull between the two. 
3) Now the number of active connections in Bitshares Network shows as 1. 
4) add identity of client 2 as contacts in client. 
5) Now do request authorization of this contact in client 1. 
5) Now remove the network connection of the 1st host(in which client 1 is present) 
6) Accept the Request Authorization in client 2 
7) Make make the network up for the host in client 1. 

Issue is Now Bitshares network shows 2 for client 1 and 1 for client 2.

**Comment by grzegorzs** [comment]
duplicate with #343
