### ISSUE TITLE
 Date Sent time doesn't match with sent and recived items 

### ISSUE THREAD

**Issue by yuvarajgogoi** [InvictusInnovations/keyhotee#357]
Steps to reproduce

1) Start 2 KH in different hosts.
2) Send mail from one KH to another.
Issue is  "Date Sent" time for the sent items in client 1 is different from the one that is recieved on the other client

Tested with one KH in Debain and the other in Windows 7

**Comment by grzegorzs** [comment]
InvictusInnovations/BitShares@ac66e30d912b48dbb34dd1d6b1c1b59cd4b0710a

**Comment by grzegorzs** [comment]
InvictusInnovations/BitShares@ac66e30
The differences arise from the changes introduced in the above commit.
The solution would involve the extension of the structure of the message. Since this is a irrelevant bug remains as it is.

**Comment by dnotestein** [comment]
yes, this condition is intentional, and is not considered a real problem
