### ISSUE TITLE
crash seen on closing the KH client(reproduced only once)

### ISSUE THREAD

**Issue by yuvarajgogoi** [InvictusInnovations/keyhotee#359]
Scenario
1) I ran my client for whole day.
2) closed the client

crash is seen.

Tested in Debian and is reproduced only once

log is attached:
please rename qt_temp.TJ2525.png to qt_temp.TJ2525

Please contact me for the core dump.

![qt_temp tj2525](https://cloud.githubusercontent.com/assets/5823578/2789419/554efe72-cbad-11e3-819d-5fa460cc2086.png)

**Comment by PaulEU** [comment]
Is connected with #370 issue
