### ISSUE TITLE
crash on closing window in a scenario

### ISSUE THREAD

**Issue by yuvarajgogoi** [InvictusInnovations/keyhotee#364]
Steps to reproduce
1) start KH
2) Do New Identity
3) close KH.

crash is seen

Tested in Debain and is always reproducible.

log : 

3593124ms th_a       KeyhoteeApplication.cpp:439   startup              ] .
3593124ms th_a       application.cpp:460           get_profiles         ] /home/yuvaraj/.local/share/Keyhotee/profiles/Y G
3593124ms th_a       application.cpp:467           get_profiles         ] profiles ["Y G"]
3593124ms th_a       KeyhoteeApplication.cpp:376   displayLogin         ] .
3593135ms th_a       application.cpp:460           get_profiles         ] /home/yuvaraj/.local/share/Keyhotee/profiles/Y G
3593136ms th_a       application.cpp:467           get_profiles         ] profiles ["Y G"]
3593136ms th_a       LoginDialog.cpp:42            LoginDialog          ] profiles Y G
3596247ms th_a       profile.cpp:111               open                 ] opening profile: /home/yuvaraj/.local/share/Keyhotee/profiles/Y G
3596247ms th_a       profile.cpp:126               open                 ] loading master key file:.keyhotee_master.key
3596248ms th_a       profile.cpp:138               open                 ] opening profile databases
3596432ms th_a       upgrade_leveldb.cpp:24        UpgradeDbIfNecessary ] Database /home/yuvaraj/.local/share/Keyhotee/profiles/Y G/addressbook/contact_db is not upgradeable
3596433ms th_a       addressbook.cpp:59            open                 ] loading contact {"public_key":"025cfbdb083ac3b52275cf4484832e5af82fde27e228d9c7a51e2ee7423a0f6751","dac_id_hash":9871701508635294881,"dac_id_string":"y","properties":[],"wallet_index":0,"auth_status":"unauthorized","privacy_setting":"secret_contact","first_name":"","last_name":"","icon_png":"","notes":"","next_send_trx_id":0,"send_trx_address":{"pub_key":"000000000000000000000000000000000000000000000000000000000000000000","chain_code":"0000000000000000000000000000000000000000000000000000000000000000"},"bitchat_recv_channels":[],"bitchat_broadcast_channels":[],"bitchat_recv_broadcast_key":"0000000000000000000000000000000000000000000000000000000000000000"}
3596601ms th_a       upgrade_leveldb.cpp:24        UpgradeDbIfNecessary ] Database /home/yuvaraj/.local/share/Keyhotee/profiles/Y G/idents is not upgradeable
3596735ms th_a       upgrade_leveldb.cpp:24        UpgradeDbIfNecessary ] Database /home/yuvaraj/.local/share/Keyhotee/profiles/Y G/mail/inbox/index is not upgradeable
3596870ms th_a       upgrade_leveldb.cpp:24        UpgradeDbIfNecessary ] Database /home/yuvaraj/.local/share/Keyhotee/profiles/Y G/mail/inbox/digest_to_data is not upgradeable
3597094ms th_a       upgrade_leveldb.cpp:24        UpgradeDbIfNecessary ] Database /home/yuvaraj/.local/share/Keyhotee/profiles/Y G/mail/inbox/digest_to_header is not upgradeable
3597184ms th_a       upgrade_leveldb.cpp:24        UpgradeDbIfNecessary ] Database /home/yuvaraj/.local/share/Keyhotee/profiles/Y G/mail/draft/index is not upgradeable
3597274ms th_a       upgrade_leveldb.cpp:24        UpgradeDbIfNecessary ] Database /home/yuvaraj/.local/share/Keyhotee/profiles/Y G/mail/draft/digest_to_data is not upgradeable
3597399ms th_a       upgrade_leveldb.cpp:24        UpgradeDbIfNecessary ] Database /home/yuvaraj/.local/share/Keyhotee/profiles/Y G/mail/draft/digest_to_header is not upgradeable
3597545ms th_a       upgrade_leveldb.cpp:24        UpgradeDbIfNecessary ] Database /home/yuvaraj/.local/share/Keyhotee/profiles/Y G/mail/pending/index is not upgradeable
3597714ms th_a       upgrade_leveldb.cpp:24        UpgradeDbIfNecessary ] Database /home/yuvaraj/.local/share/Keyhotee/profiles/Y G/mail/pending/digest_to_data is not upgradeable
3597882ms th_a       upgrade_leveldb.cpp:24        UpgradeDbIfNecessary ] Database /home/yuvaraj/.local/share/Keyhotee/profiles/Y G/mail/pending/digest_to_header is not upgradeable
3598062ms th_a       upgrade_leveldb.cpp:24        UpgradeDbIfNecessary ] Database /home/yuvaraj/.local/share/Keyhotee/profiles/Y G/mail/sent/index is not upgradeable
3598266ms th_a       upgrade_leveldb.cpp:24        UpgradeDbIfNecessary ] Database /home/yuvaraj/.local/share/Keyhotee/profiles/Y G/mail/sent/digest_to_data is not upgradeable
3598401ms th_a       upgrade_leveldb.cpp:24        UpgradeDbIfNecessary ] Database /home/yuvaraj/.local/share/Keyhotee/profiles/Y G/mail/sent/digest_to_header is not upgradeable
3598490ms th_a       upgrade_leveldb.cpp:24        UpgradeDbIfNecessary ] Database /home/yuvaraj/.local/share/Keyhotee/profiles/Y G/chat/index is not upgradeable
3598592ms th_a       upgrade_leveldb.cpp:24        UpgradeDbIfNecessary ] Database /home/yuvaraj/.local/share/Keyhotee/profiles/Y G/chat/digest_to_data is not upgradeable
3598682ms th_a       upgrade_leveldb.cpp:24        UpgradeDbIfNecessary ] Database /home/yuvaraj/.local/share/Keyhotee/profiles/Y G/chat/digest_to_header is not upgradeable
3598772ms th_a       upgrade_leveldb.cpp:24        UpgradeDbIfNecessary ] Database /home/yuvaraj/.local/share/Keyhotee/profiles/Y G/request/index is not upgradeable
3598862ms th_a       upgrade_leveldb.cpp:24        UpgradeDbIfNecessary ] Database /home/yuvaraj/.local/share/Keyhotee/profiles/Y G/request/digest_to_data is not upgradeable
3598951ms th_a       upgrade_leveldb.cpp:24        UpgradeDbIfNecessary ] Database /home/yuvaraj/.local/share/Keyhotee/profiles/Y G/request/digest_to_header is not upgradeable
3599063ms th_a       upgrade_leveldb.cpp:24        UpgradeDbIfNecessary ] Database /home/yuvaraj/.local/share/Keyhotee/profiles/Y G/authorization/index is not upgradeable
3599175ms th_a       upgrade_leveldb.cpp:24        UpgradeDbIfNecessary ] Database /home/yuvaraj/.local/share/Keyhotee/profiles/Y G/authorization/digest_to_data is not upgradeable
3599278ms th_a       upgrade_leveldb.cpp:24        UpgradeDbIfNecessary ] Database /home/yuvaraj/.local/share/Keyhotee/profiles/Y G/authorization/digest_to_header is not upgradeable
3599279ms th_a       profile.cpp:156               open                 ] loaded last_sync_time = 20140425T081103.659429
3599279ms th_a       profile.cpp:157               open                 ] finished opening profile
3599279ms th_a       application.cpp:295           configure            ] application::configure
3599279ms th_a       application.cpp:327           configure            ] configuring server
3599279ms th_a       server.cpp:208                configure            ] listening for stcp connections on port 9876
3599279ms th_a       application.cpp:333           configure            ] configure bitname client
3599368ms th_a       upgrade_leveldb.cpp:24        UpgradeDbIfNecessary ] Database /home/yuvaraj/.local/share/Keyhotee/profiles/Y G/data/bitname/bitname/channel/block_num_to_header is not upgradeable
3599458ms th_a       upgrade_leveldb.cpp:24        UpgradeDbIfNecessary ] Database /home/yuvaraj/.local/share/Keyhotee/profiles/Y G/data/bitname/bitname/channel/block_num_to_name_trxs is not upgradeable
3599548ms th_a       upgrade_leveldb.cpp:24        UpgradeDbIfNecessary ] Database /home/yuvaraj/.local/share/Keyhotee/profiles/Y G/data/bitname/bitname/channel/name_hash_to_locs is not upgradeable
3599548ms th_a       bitname_db.cpp:100            load_indexes         ] load indexes
3599548ms th_a       bitname_db.cpp:115            load_indexes         ] load indexes
3599549ms th_a       bitname_db.cpp:170            init_timekeeper      ] ...init stats...
3599549ms th_a       bitname_db.cpp:172            init_timekeeper      ] ...done init timekeeper...
3599549ms th_a       bitname_db.cpp:222            open                 ] open name db
chain time: 20130822T183833
expected time: 20130822T183833
target difficulty: 268435456
target name difficulty: 268435456
3599683ms th_a       upgrade_leveldb.cpp:24        UpgradeDbIfNecessary ] Database /home/yuvaraj/.local/share/Keyhotee/profiles/Y G/data/bitname/bitname/channel/forks/headers is not upgradeable
3599828ms th_a       upgrade_leveldb.cpp:24        UpgradeDbIfNecessary ] Database /home/yuvaraj/.local/share/Keyhotee/profiles/Y G/data/bitname/bitname/channel/forks/blocks is not upgradeable
3599974ms th_a       upgrade_leveldb.cpp:24        UpgradeDbIfNecessary ] Database /home/yuvaraj/.local/share/Keyhotee/profiles/Y G/data/bitname/bitname/channel/forks/forks is not upgradeable
86ms th_a       upgrade_leveldb.cpp:24        UpgradeDbIfNecessary ] Database /home/yuvaraj/.local/share/Keyhotee/profiles/Y G/data/bitname/bitname/channel/forks/nexts is not upgradeable
189ms th_a       upgrade_leveldb.cpp:24        UpgradeDbIfNecessary ] Database /home/yuvaraj/.local/share/Keyhotee/profiles/Y G/data/bitname/bitname/channel/forks/unknown is not upgradeable
192ms th_a       application.cpp:343           configure            ] configure bitchat client
279ms th_a       upgrade_leveldb.cpp:24        UpgradeDbIfNecessary ] Database /home/yuvaraj/.local/share/Keyhotee/profiles/Y G/data/bitchat/channel0/cache_chan_2/message_cache/by_id is not upgradeable
369ms th_a       upgrade_leveldb.cpp:24        UpgradeDbIfNecessary ] Database /home/yuvaraj/.local/share/Keyhotee/profiles/Y G/data/bitchat/channel0/cache_chan_2/message_cache/age_index1 is not upgradeable
369ms th_a       application.cpp:347           configure            ] configuring rpc_server
369ms th_a       rpc_server.cpp:245            configure            ] listening for rpc connections on port 9877
370ms th_a       rpc_server.cpp:247            configure            ] listening for rpc connections on port 9877
370ms th_a       application.cpp:350           configure            ] done configuring rpc_server
370ms th_a       application.cpp:352           configure            ] end application::configure
QMetaObject::connectSlotsByName: No matching signal for on_actionShow_details_toggled(bool)
QLayout: Attempting to add QLayout "" to Mailbox "inbox_page", which already has a layout
QMetaObject::connectSlotsByName: No matching signal for on_actionShow_details_toggled(bool)
QMetaObject::connectSlotsByName: No matching signal for on_actionShow_details_toggled(bool)
QMetaObject::connectSlotsByName: No matching signal for on_actionShow_details_toggled(bool)
QMetaObject::connectSlotsByName: No matching signal for on_actionShow_details_toggled(bool)
QLayout: Attempting to add QLayout "" to ContactsTable "contacts_page", which already has a layout
423ms th_a       AddressBookModel.cpp:310      reloadContacts       ] loading contacts...
448ms th_a       KeyhoteeMainWindow.cpp:240    KeyhoteeMainWindow   ] idents: [{"public_key":"025cfbdb083ac3b52275cf4484832e5af82fde27e228d9c7a51e2ee7423a0f6751","dac_id_hash":9871701508635294881,"dac_id_string":"y","properties":[],"wallet_ident":"y","mining_effort":25,"first_name":"","last_name":"","private_icon_png":""}]
461ms th_a       application.cpp:202           start_mail_connect_l ] start_mail_connect_loop
461ms th_a       application.cpp:206           operator()           ] Closing the mail connection (which may not be open)
461ms th_a       application.cpp:208           operator()           ] Done closing the mail connection
463ms th_a       server.cpp:116                accept_connection    ] accepted connection from 192.168.1.3:50806
463ms th_a       peer_channel.cpp:162          on_connected         ] on connected...
469ms th_a       peer_channel.cpp:339          handle_subscribe     ] 192.168.1.3:50806: {"channels":[{"proto":"peer_proto","chan":0},{"proto":"name_proto","chan":0},{"proto":"chat_proto","chan":0}]}
469ms th_a       bitname_channel.cpp:501       request_block_header ] requesting block headers from 192.168.1.3:50806
472ms th_a       bitname_channel.cpp:447       handle_message       ] get_headers_msg
475ms th_a       bitname_channel.cpp:447       handle_message       ] headers_msg
475ms th_a       bitname_channel.cpp:730       handle_headers       ] received 0 block headers
terminate called after throwing an instance of '(anonymous namespace)::TSegmentationFaultException'
  what():  std::exception
Aborted (core dumped)

**Comment by vogel76** [comment]
New identity dialog should be modal.
