### ISSUE TITLE
Use webkitwidget browser to hookup up to web-based wallet GUI

### ISSUE THREAD

**Issue by dnotestein** [InvictusInnovations/keyhotee#365]
The design for the wallet has changed: rather than implement the wallet using QT controls, we're going to implement the wallet GUI (for multiple currencies) using a web interface. Keyhotee will interface to this web interface using a QT web browser wideget (QT webkit widget). So essentially clicking on the wallet interface in the navigation bar will bring up a large webkit widget in the modal pane of the Keyhotee main window pointing to the URL of the web-based wallet interface. Getting the webkit widget to work on Windows is a huge pain, so it's going to be a bit of a chore to get this working on windows.

Other guys will be working on the web interface itself (bytemaster initially and new guy, Nikita). We just need to display it.

**Comment by PaulEU** [comment]
Implemented at revisions:
11792968278bd82f843adf25414510736cf92d18
769a5bdae4cc2ecea7b6ad0fd90fa5188c2f9f72
f94b22015a26cb4898bcf649994bf6a7d8827c41
