### ISSUE TITLE
messges send from non-authorized contact is at Inbox in a scenario

### ISSUE THREAD

**Issue by yuvarajgogoi** [InvictusInnovations/keyhotee#368]
Steps to reproduce
1)Start 2 KH.
2) send messages to each other.
Issue is messages send to 2nd KH client at marked at Inbox even if they come from non-authorized contacts.

Tested in Debian and is always reproducible.

**Comment by grzegorzs** [comment]
Whether a message from non-authorized contact goes to the Spam is dependent on the settings (File-> Option-> Privacy-> Allow mail message from ...)
- Anyone - message from anyone (authorized, unauthorized, unknown contact) goes to Inbox
- Authorized Contacts - only messages from authorized contacts goes to Inbox, the remaining messages goes to Spam

Yuvaraj check the settings and let me know if it works.

**Comment by yuvarajgogoi** [comment]
This scenario is working fine.
