### ISSUE TITLE
Implement a header over mail box list and contact list

### ISSUE THREAD

**Issue by vogel76** [InvictusInnovations/keyhotee#381]
Such header should display name of selected folder (Inbox, Outbox, Draft etc) what will increase readibility of application. For contacts view right now should display 'Contact list' in the title. All wallet views shall not contain any addtional header.

**Comment by vogel76** [comment]
After selecting select blocked contact lists old title is displayed (contact list) but it should be 'Blocked contact lists'

**Comment by PaulEU** [comment]
f069c09ed160e9abb7e0896ad6c8b4aae55fd88f
6c2ca8beb17eeffc39b0cc7bf609b93ff757a90e
