### ISSUE TITLE
Unblock not working in a scenario.

### ISSUE THREAD

**Issue by yuvarajgogoi** [InvictusInnovations/keyhotee#389]
Steps to reproduce:
1) send contact authorization to another client.
2) in the 2nd client , block this authorization.
3) Then unblock it.

Unblock didn't occur for this contact

Tested in Debian with local mail_server.

**Comment by grzegorzs** [comment]
Yuvaraj, could you check you can still reproduce this issue?

**Comment by yuvarajgogoi** [comment]
fixed
