### ISSUE TITLE
Add 'Show details' common toolbar option

### ISSUE THREAD

**Issue by vogel76** [InvictusInnovations/keyhotee#4]
This option (2-state toolbar button) should determine when to show or not detail pane for currently selected email or contact.
The application should save this setting value for each email folder and contact list separately.

**Comment by grzegorzs** [comment]
https://github.com/InvictusInnovations/keyhotee/commit/f0c46e7364d95ad9f6d908b0c829f199a7fb1002

**Comment by PaulEU** [comment]
"Show details" don't work when you click on the contact item  (when you click on the contacts_root is ok)
