### ISSUE TITLE
The connection frame status shows as disconnected for sometime if we try to create an identity with download identity history

### ISSUE THREAD

**Issue by yuvarajgogoi** [InvictusInnovations/keyhotee#409]
Steps to reproduce:
1) start Kh.
2) create an identity with download identity history.

Tested in Debian and is always reproducible.

**Comment by PaulEU** [comment]
I consulted it with Dnotestein.
Disconnecting and reconnecting to mail server is required to send and update synchronize time when identity history is downloaded.
