### ISSUE TITLE
bug  "EQUAL" "" Unknown arguments specified

### ISSUE THREAD

**Issue by vipjeffreylee** [InvictusInnovations/keyhotee#41]
CMake Error at CMakeLists.txt:41 (IF):
  if given arguments:
    "EQUAL" ""
  Unknown arguments specified
-- Configuring incomplete, errors occurred!

Could not validate code before you submit it?

**Comment by vogel76** [comment]
Hi Jeffrey, I have validated it, and it worked for me. I had to change your solution since it didn't work for us on windows (at least). Maybe we have different versions of cmake. I'm using:
cmake version 2.8.12.1
so maybe you have some older one

**Comment by vipjeffreylee** [comment]
My cmake version is cmake-2.8.12.1-Linux-i386.

**Comment by vipjeffreylee** [comment]
Can you add IF(UNIX) use my solution ?

**Comment by vogel76** [comment]
I don't like such platform branching if not needed. Strange since our cmake versions seems to be the same. I of course also checked it on linux. I will try to use STREQUAL operator there which probably is better in this context. Could you also check if it works for you with STREQUAL ?

**Comment by vipjeffreylee** [comment]
Yes STREQUAL is corrected.
Code is:
 41 IF(INVICTUS_ROOT STREQUAL "")
 42     SET(INVICTUS_ROOT .)
 43 ENDIF(INVICTUS_ROOT STREQUAL "")

**Comment by vipjeffreylee** [comment]
if $ENV{INVICTUS_ROOT} not define , INVICTUS_ROOT value is not "", I think INVICTUS_ROOT value is not define.

**Comment by vogel76** [comment]
Ok, found cause of a problem. I think it will be fixed in a sec

**Comment by vipjeffreylee** [comment]
I advice you should add install cmake command in CMakeLists.txt.  delete env INVICTUS_ROOT
We can install keyhotee with make install.

**Comment by vipjeffreylee** [comment]
208 set(CMAKE_RUNTIME_OUTPUT_DIRECTORY $ENV{INVICTUS_ROOT}/bin)
209 set(CMAKE_RUNTIME_OUTPUT_DIRECTORY_RELEASE $ENV{INVICTUS_ROOT}/bin)
210 set(CMAKE_RUNTIME_OUTPUT_DIRECTORY_DEBUG $ENV{INVICTUS_ROOT}/bin)

modify

208 set(CMAKE_RUNTIME_OUTPUT_DIRECTORY bin)
209 set(CMAKE_RUNTIME_OUTPUT_DIRECTORY_RELEASE bin)
210 set(CMAKE_RUNTIME_OUTPUT_DIRECTORY_DEBUG bin)

**Comment by vogel76** [comment]
fix is committed. Please pull and close issue if it works (what I hope). I'd like to have INVICTUS_ROOT env still because of windows development purposes

**Comment by vipjeffreylee** [comment]
Yes,It is very good!
Thank you very much!
