### ISSUE TITLE
Missing contact icon control in contact info/edit page

### ISSUE THREAD

**Issue by vogel76** [InvictusInnovations/keyhotee#45]
In previous version there was displaye contact icon (it can be customized by end-user). Editable view should allow to change it, as it was done previously.

**Comment by vogel76** [comment]
Application should allow to set/change icon for any contact defined in address book.

**Comment by PaulEU** [comment]
In the previous version this icon does'n work when you click on it.
I fixed it in the new version.

**Comment by dnotestein** [comment]
Hi Paul, can you add a link to the commit where you fixed this when you close an issue?

**Comment by PaulEU** [comment]
Hi Dan,
https://github.com/InvictusInnovations/keyhotee/commit/1dc812433b9bf0db6cd796775220b4f6703339c2
File: AddressBook/ContactView.cpp
Line: 109 and 596
Something is wrong ?
Icon is not storage yet.
