### ISSUE TITLE
Invalid config.json file hangs up the application while starting

### ISSUE THREAD

**Issue by vogel76** [InvictusInnovations/keyhotee#46]
config.json with following contents will hang application at start. During a file parse exception is generated but it is ignored by application and execution continues.
Then, improperly read/uninitialized data are causing to wait for infinite delay one of threads (named "upnp").
The file is broken since default node address doesn't contain double quotas
{
  "data_dir": "C:/Users/vogel/AppData/Local/Invictus Innovations, Inc/Keyhotee/second/data",
  "network_port": 9876,
  "rpc_config": {
    "port": 9877,
    "user": "",
    "pass": ""
  },
  "enable_upnp": false,
  "default_nodes": [
    127.0.0.1:9876
  ]
}

**Comment by dnotestein** [comment]
Yuvaraj, can you look into this issue and see if it still occurs nowadays? If so, please look into adding an exception catch block to eliminate this error.

**Comment by yuvarajgogoi** [comment]
this issue is no longer reproducible in the latest build
