### ISSUE TITLE
Crash after entering initial user information

### ISSUE THREAD

**Issue by arcke** [InvictusInnovations/keyhotee#49]
After building succesfully on Arch Linux the application crashes after supplying the initial user information.

<code>[arcke@localhost keyhotee]$ bin/Keyhotee 
"Qt Warning - invalid keysym: dead_actute" 
contents:  "" 
error status:  0 
2544740ms th_a       main.cpp:43                   load_config          ] config_file: /home/arcke/.local/share/Invictus Innovations, Inc/Keyhotee/default/config.json
2545074ms th_a       application.cpp:110           configure            ] external IP 83.117.26.21
2545074ms th_a       server.cpp:206                configure            ] listening for stcp connections on port 9876
2545367ms th_a       bitname_db.cpp:92             load_indexes         ] load indexes
2545367ms th_a       bitname_db.cpp:107            load_indexes         ] load indexes
2545369ms th_a       bitname_db.cpp:162            init_timekeeper      ] ...init stats...
2545369ms th_a       bitname_db.cpp:164            init_timekeeper      ] ...done init timekeeper...
2545369ms th_a       bitname_db.cpp:214            open                 ] open name db
chain time: 20130822T183833
expected time: 20130822T183833
target difficulty: 256
target name difficulty: 256
2546439ms th_a       rpc_server.cpp:237            configure            ] listening for rpc connections on port 9877
2577335ms stretch_s  keychain.cpp:24               operator()           ] stretchign seed
2577335ms stretch_s  keychain.cpp:27               operator()           ] .
Illegal instruction (core dumped)</code>

Using GDB we find the illegal instruction to be this:

<code>[Switching to Thread 0x7fffc4f04700 (LWP 21069)]
fc::CityHashCrc256Long (s=s@entry=0x7fffc4f03900 "\250ć?n\234\216\357\340+\036\060tj۴\201\203\332\n]\034\361rQ\024\255\245\237\231", <incomplete sequence \317>, len=0, len@entry=240, seed=seed@entry=4294967263, 
    result=result@entry=0x7fffc4f03a20) at /home/arcke/src/keyhotee/BitShares/fc/src/crypto/city.cpp:428
428</code>

Full GDB log + backtrace: http://pastebin.com/db2nwNs9

**Comment by bytemaster** [comment]
What CPU were you trying to run this on?

**Comment by dnotestein** [comment]
Arke, possibly your CPU didn't support SSE4, we've since changed the compilation process to not require SSE4. Please update and see if it works better you now.

**Comment by arcke** [comment]
Ive tried again, recompiled and created my ID. The above error persists. This is my CPU:

<code>[arcke@localhost keyhotee]$ cat /proc/cpuinfo 
processor   : 0
vendor_id   : AuthenticAMD
cpu family  : 17
model       : 3
model name  : AMD Athlon(tm) X2 Dual-Core QL-64
stepping    : 1
microcode   : 0x2000057
cpu MHz     : 1050.000
cache size  : 512 KB
physical id : 0
siblings    : 2
core id     : 0
cpu cores   : 2
apicid      : 0
initial apicid  : 0
fpu     : yes
fpu_exception   : yes
cpuid level : 1
wp      : yes
flags       : fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ht syscall nx mmxext fxsr_opt rdtscp lm 3dnowext 3dnow constant_tsc rep_good nopl nonstop_tsc extd_apicid pni cx16 lahf_lm cmp_legacy svm extapic cr8_legacy 3dnowprefetch osvw skinit hw_pstate lbrv svm_lock nrip_save
bogomips    : 4201.29
TLB size    : 1024 4K pages
clflush size    : 64
cache_alignment : 64
address sizes   : 40 bits physical, 48 bits virtual
power management: ts ttp tm stc 100mhzsteps hwpstate</code>

<code>processor : 1
vendor_id   : AuthenticAMD
cpu family  : 17
model       : 3
model name  : AMD Athlon(tm) X2 Dual-Core QL-64
stepping    : 1
microcode   : 0x2000057
cpu MHz     : 1050.000
cache size  : 512 KB
physical id : 0
siblings    : 2
core id     : 1
cpu cores   : 2
apicid      : 1
initial apicid  : 1
fpu     : yes
fpu_exception   : yes
cpuid level : 1
wp      : yes
flags       : fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ht syscall nx mmxext fxsr_opt rdtscp lm 3dnowext 3dnow constant_tsc rep_good nopl nonstop_tsc extd_apicid pni cx16 lahf_lm cmp_legacy svm extapic cr8_legacy 3dnowprefetch osvw skinit hw_pstate lbrv svm_lock nrip_save
bogomips    : 4201.29
TLB size    : 1024 4K pages
clflush size    : 64
cache_alignment : 64
address sizes   : 40 bits physical, 48 bits virtual
power management: ts ttp tm stc 100mhzsteps hwpstate
</code>

**Comment by eblack1** [comment]
I also use Arch Linux and have been experiencing this issue, but as of commit f12659e41133a7cada7f9910e04968d06e2f400d today, I no longer experience this bug.  I enter my initial information, then the main Keyhotee window appears.  I even generated the public key for my Keyhotee Founder ID and tested out mining.

If @arcke can confirm that this bug no longer occurs, this issue could be closed.

**Comment by arcke** [comment]
@eblack1 Confirmed

Bug no longer occurs here. Tested on Arch Linux and Debian GNU/Linux.
