### ISSUE TITLE
Selecting contact on recent list should synchronize it in main list

### ISSUE THREAD

**Issue by vogel76** [InvictusInnovations/keyhotee#51]
Right now selecting item on recent list just updates contact info view. Selected item on contact list also should be synchronized, and made visible.

**Comment by grzegorzs** [comment]
Fixed at: 701dfecf7f688899be637455410f5083c82fa08f

**Comment by PaulEU** [comment]
if you sort main list, synchronize doesn't work.

**Comment by grzegorzs** [comment]
Now, after sorting the list of contacts, sync works, but...
if you delete, not last contact (or identity) and add new contact (or identity) in address book are two contacts with the same wallet_index
