### ISSUE TITLE
Contact editor/viewer does not handle email, phone and notes attributes properly

### ISSUE THREAD

**Issue by vogel76** [InvictusInnovations/keyhotee#53]
Viewer doesn't load these data for display, editor don't save them.
Please use following Contact members for loading/saving these data:
  QString getEmail() const;
  void setEmail(const QString& email);
  QString getPhone() const;
  void setPhone(const QString& phone);
  QString getNotes() const;
  void setNotes(const QString& phone);

**Comment by vogel76** [comment]
These features are postponed for now. Please hide controls related to email/phone number from this page.

**Comment by PaulEU** [comment]
https://github.com/InvictusInnovations/keyhotee/commit/506febd48d28411e5dcc718857c05c86b82af128
notes handle: https://github.com/InvictusInnovations/keyhotee/commit/8aff106e61fa6982a8fdb15873fc870c68d87912
