### ISSUE TITLE
Sending Email to Self

### ISSUE THREAD

**Issue by bytemaster** [InvictusInnovations/keyhotee#61]
Does not show up in Sent Mail
Does not show up in Inbox

**Comment by dnotestein** [comment]
This is actual part of the larger task to put mail in a pending queue, with a separate thread that sends mail from the queue when it's proof-of-work is complete. Mail sent to self will just go on this queue like any other mail.

**Comment by vogel76** [comment]
Even mail queue was implemented this feature (sending email to self) still doesn't work. Looks like there is some problem in send_email implementation

**Comment by dnotestein** [comment]
I think this has been fixed, at least in current server code. Maybe it's a problem for peer-to-peer communications still, but I'm going to close it for now.
