### ISSUE TITLE
Toolbar Menus on Contact Edit should never dynamically change

### ISSUE THREAD

**Issue by bytemaster** [InvictusInnovations/keyhotee#65]
After creating a new contact the "Save" button turns into a "Send Email" button... unsupported buttons should be grayed out.

**Comment by PaulEU** [comment]
https://github.com/InvictusInnovations/keyhotee/commit/d8949ff66341aa33f7dc59b71e071df2a80632f8

**Comment by vogel76** [comment]
Why 'Share' and 'Request authorisation' options disappeared from toolbar ?

**Comment by PaulEU** [comment]
I'v hidden it because are unsupported now.
User may be confused when icons are grayed.
Ok, I will gray out.

**Comment by PaulEU** [comment]
https://github.com/InvictusInnovations/keyhotee/commit/4182406e8bb1f31cb8738c04ab64a6d5fa2a7d6f
