### ISSUE TITLE
Saving after Edit creates DUPLICATES

### ISSUE THREAD

**Issue by bytemaster** [InvictusInnovations/keyhotee#66]
If you edit then save a contact it will create duplicate entries.

**Comment by vogel76** [comment]
Unfortunetely I cannot reproduce such behaviour (checked on rev:
https://github.com/InvictusInnovations/keyhotee/commit/bce5edbd922743929b63127f9182691b9783c1f5) .
Could you better describe the operations you have done and assign back this issue to me ?

**Comment by dnotestein** [comment]
No one currently current able to duplicate, keep on the lookout for it.
