### ISSUE TITLE
Public Key Copy / Paste

### ISSUE THREAD

**Issue by bytemaster** [InvictusInnovations/keyhotee#68]
User should be able to select (but not change) the text in the public key field and then copy to the clipboard with normal keyboard shortcuts. 

When the click on the key, it should always select the whole text.

**Comment by PaulEU** [comment]
https://github.com/InvictusInnovations/keyhotee/commit/bc47e2c3a4baa14bbe8b4ecb158962fda05b842c
https://github.com/InvictusInnovations/keyhotee/commit/1ead4694fac6c6767dc116f5afbc9d5110054941
