### ISSUE TITLE
No way to toggle between editor windows... 

### ISSUE THREAD

**Issue by bytemaster** [InvictusInnovations/keyhotee#79]
CMD ~ should toggle between all Keyhotee windows

Add Window menu that allows you to bring any window to focus.

**Comment by vogel76** [comment]
I'd like to suggest to defer this feature to another milestone. Probably best would be to rethink GUI architecture (maybe made it MDI application where email documents are displayed in such MDI windows and got such feature and many more implemented).

**Comment by dnotestein** [comment]
Investigate if we can easily just add a Window menu in Qt for this.

**Comment by dnotestein** [comment]
danL reports that CMD ~ now works on Mac OS after recent menubar changes. He'd still like a Window menu at some point.

**Comment by grzegorzs** [comment]
Added option to toggle between editor windows by "Window" menu and shortcut Ctrl+Tab (Ctrl+Shift+Tab)
3f4478b9834f845804c83c3e88143df275c91433
