### ISSUE TITLE
Quickly Create contact from Sender of Email

### ISSUE THREAD

**Issue by bytemaster** [InvictusInnovations/keyhotee#81]
In the body of the email... where it reads FROM  HASH_OF_PUB_KEY

Replace HASH_OF_PUB_KEY with FULL PUBLIC KEY 
Add "+" button next key label that will create a new contact with the public key filled in.

**Comment by grzegorzs** [comment]
In MailViewer, on "From", "To", "CC" added context menu. Added possibility to add contact to the address book or find contact in address book.
923cba65153b8d597ac12b3ff4172cdb50a4a7a1

like as: 512bac6
