### ISSUE TITLE
Unable to add again just removed contact

### ISSUE THREAD

**Issue by vogel76** [InvictusInnovations/keyhotee#85]
1) select any contact in contact list
2) remove them using delete command
3) try to define new contact using the same kID as deleted one. Application disallows it by displaying error message that given contact is already placed on list (what is not true). The problem disappears after application restart what suggests some improper caching of contact list.

**Comment by grzegorzs** [comment]
Removing contact from address book
file:

<pre>InvictusRoot\keyhotee\BitShares\src\addressbook\addressbook.cpp</pre>

line 119:
<pre><code>void addressbook::remove_contact(uint32_t wallet_index)</pre></code>
it does not remove the contact from lookup_tables

**Comment by dnotestein** [comment]
Added code to clear auxilariy tables in call to remove contact. Fixed in https://github.com/InvictusInnovations/keyhotee/commit/5885ed918573189cea9390e5271679f771de3757.
