### ISSUE TITLE
Trash on screen when double click on mail message

### ISSUE THREAD

**Issue by vogel76** [InvictusInnovations/keyhotee#86]
I suppose it should be opened (and probably it is) but the opened window is displayed incorrectly.
![untitled](https://f.cloud.github.com/assets/6086581/1765286/0bf43482-6734-11e3-8ef9-0298af1c5a2a.png)

**Comment by dnotestein** [comment]
This used to open a separate window for viewing the mail message. It was working as of last night. Anyone know why this was changed?

**Comment by vogel76** [comment]
Fixed at rev:
https://github.com/InvictusInnovations/keyhotee/commit/5780010056a21676a4165820ecbdb94c1d86e492
