### ISSUE TITLE
Crash while sending an email

### ISSUE THREAD

**Issue by vogel76** [InvictusInnovations/keyhotee#87]
KH application crashes when I'm trying to send an email (bad_alloc exception is thrown).
Crash callstack:

>   msvcr110d.dll!_CxxThrowException(void \* pExceptionObject=0x063bf20c, const _s__ThrowInfo \* pThrowInfo=0x5d027548) Line 152  C++
>     msvcr110d.dll!operator new(unsigned int size=1073741824) Line 63    C++
>     KeyhoteeD.exe!bts::hashtable::hashtable() Line 33   C++
>     KeyhoteeD.exe!bts::momentum_search(fc::sha256 head={...}) Line 72   C++
>     KeyhoteeD.exe!bts::bitchat::encrypted_message::do_proof_work(unsigned __int64 tar_per_kb=1) Line 80 C++
>     KeyhoteeD.exe!<lambda_e7ea0e7f931e9568fc48847a39d0c11f>::operator()() Line 84   C++
>     KeyhoteeD.exe!fc::detail::void_functor_run<<lambda_e7ea0e7f931e9568fc48847a39d0c11f> >::run(void \* functor=0x05a048f8, void \* prom=0x05a04980) Line 53  C++
>     KeyhoteeD.exe!fc::task_base::run() Line 17  C++

**Comment by bytemaster** [comment]
You must not have much RAM?   I added the proof-of-work to the message sending.

**Comment by dnotestein** [comment]
No, the problem is win32 doesn't like this much memory allocated all in one block. I had to make modifications in the past for win32 to support the proof-of-work for the miner: I guess those changes have been lost. That's why this issue is assigned to me, so I can correct it again. Last time I made a slightly more complicated hashtable to account for this issue.

**Comment by bytemaster** [comment]
I think we can reduce the memory-hardness by tweaking the momentum parameters to only require 256 MB rather than 768 to 1 GB.   Many of our users will not have a ton of RAM.

Dan

**Comment by dnotestein** [comment]
Ok, I just enabled my original change for WIN32. I'll tweak it more later to further reduce memory required.

**Comment by vogel76** [comment]
Fixed at rev:
https://github.com/InvictusInnovations/BitShares/commit/82f22b1fbe3d9cc5bf79f5a000cb3f539f03cb71
