### ISSUE TITLE
Redesign main window menu

### ISSUE THREAD

**Issue by vogel76** [InvictusInnovations/keyhotee#9]
File: Exit
Edit: Copy, Cut, Paste | Select All | Delete. Select all, delete options should be context dependent and also operate on mail list and contact list. Copy, Cut, Paste just works in editing context.
Identity: New identity | Enable mining 
Mail: Compose, Forward, Reply, Reply all | Save attachement
Help: Diagnostic | About

**Comment by grzegorzs** [comment]
https://github.com/InvictusInnovations/keyhotee/commit/f2d64b50bb992f2ec5652c150cffb3b0749abffa
