### ISSUE TITLE
Remove Set Icon Menu Item from Contact Menu

### ISSUE THREAD

**Issue by bytemaster** [InvictusInnovations/keyhotee#90]
Instead allow the user to click the icon image to 'set' the icon when they are in Edit mode.

**Comment by vogel76** [comment]
Setting the icon is of course possible from contact edit view (by clicking icon box). This option was designed as fast shortcut for it, and also to show users operations which they can perform on the contact. To be honest this 'Contact' menu should be supplemented by others operations like Edit, Share, Request authorisation. So maybe let's leave it to be supplemented in next mileston ?
