### ISSUE TITLE
Replace Chat / Info Tabs.... 

### ISSUE THREAD

**Issue by bytemaster** [InvictusInnovations/keyhotee#95]
The info TAB should be the only tab when in the contact view.

Move the chat box so that it fills the screen when selected on the left under contacts.  

When the user clicks the CONTACTS item in the tree view it they should be presented with the SPIT pain list on top / cards on bottom.

When the user as an open chat conversation with another user it should appear on the left UNDER contacts. 

On the Contact Info page place a button to open the chat window.

You should be able to remove a contact from the left side bar WITHOUT DELETING THE CONTACT... this just closes the chat window.

**Comment by vogel76** [comment]
1) deleting tree node @ CONTACTS should close chat and activate contact info page
2) double click on tree node should activate chat window and focus it
3) beside of 'mail' button please also add 'chat' button to activate chat tab.

**Comment by PaulEU** [comment]
Implemented in:
https://github.com/InvictusInnovations/keyhotee/commit/546f36564f97e9d0ae7af9de1a487bfebdd37962
https://github.com/InvictusInnovations/keyhotee/commit/ae1dd27000a7ad75bc2ac2f15d06e4655d0ef2aa
https://github.com/InvictusInnovations/keyhotee/commit/cc08ed27208f25707aa20c0f3171251d78ae54c9

**Comment by vogel76** [comment]
Bug still appears. When I click delete button on toolbar (having selected recent-contact node) delete confirmation dialog appears. Same applies to 'Del' shortcut. It should behave as described above - remove contact node from recent list and close chat.
