### ISSUE TITLE
bts::profile::identities() returns broken wallet_identity objects

### ISSUE THREAD

**Issue by vogel76** [InvictusInnovations/keyhotee#97]
Such methods returns wallet_identity where some members are broken. At least first_name, last_name, public_key does not contain valid data.

**Comment by dnotestein** [comment]
Now contact info is filled into identity when it's created during profile wizard. Something similar will still need to be done when we implement New Identity, but that's for another day. 
https://github.com/InvictusInnovations/keyhotee/commit/0038067c897dd9383e3088000699bda5542f911f

**Comment by vogel76** [comment]
Looks like latest changes (probably related to profile or identity management) again broken it. <b>It blocks further development of mail queue</b>

**Comment by dnotestein** [comment]
Hopefully fixed in https://github.com/InvictusInnovations/keyhotee/commit/86d1d6bb1b07f3e5c844072afb90c1d13e17ba60.
