### ISSUE TITLE
Backed communication doesn't work 

### ISSUE THREAD

**Issue by vogel76** [InvictusInnovations/keyhotee#98]
After Bitshares update to rev:
https://github.com/InvictusInnovations/BitShares/commit/45e5807846f90bf72637392005c717fbd5161061
communication doesn't work.
Before deleting a profile it was unable to send emails. After deleting profile I cannot add new contact to another [mined] identity since application does not find it.
Last good revision:
https://github.com/InvictusInnovations/BitShares/commit/16c1637682f20f8732291050ba41cc12a84d0b67

**Comment by dnotestein** [comment]
I think this is fixed, I can't duplicate it. I created two new profiles with identities and they had no problem finding each other.
